// GENERATED by pipeline/build_archive.py — do not edit.
(function () {
  window.AX_GRAPH = {"nodes":[{"id":"design/a","label":"헤드라인 a","section":"design","accent":"#0070f3","date":"2026-09-01","url":"https://example.com/a","val":1}],"links":[]};
})();
