/* AUTO-GENERATED by pipeline/build_data.py — do not hand-edit.
   Source of truth: pipeline/news_data.json */
(function () {
  window.AX_SECTIONS = {
  "design": {
    "label": "Design",
    "news": [
      {
        "id": "flux3",
        "eyebrow": "AI NEWS",
        "headline": "FLUX 3, 소리까지 담은\n20초 영상 생성으로 확장",
        "body": "블랙포레스트랩스가 이미지에 더해 소리까지 담은 20초 영상을 만드는 FLUX 3를 한정 공개했다.",
        "tool": "KeyShot",
        "source": "VentureBeat",
        "url": "https://venturebeat.com/technology/black-forest-labs-launches-flux-3-capable-of-generating-images-and-20-second-video-with-audio-but-in-limited-release-to-start",
        "accent": "#f5a623",
        "motif": "sphere",
        "image": "pipeline/media/flux3.png",
        "hasFull": true
      },
      {
        "id": "chaossplat",
        "eyebrow": "AI NEWS",
        "headline": "가우시안 스플랫에 조명을\n다시 입히는 카오스 V-Ray",
        "body": "카오스가 V-Ray 7.4에서 스캔한 가우시안 스플랫을 CG 조명으로 다시 밝히는 리라이팅 기능을 열었다.",
        "tool": "KeyShot",
        "source": "Creative Bloq",
        "url": "https://www.creativebloq.com/3d/chaos-just-fixed-one-of-the-biggest-problems-with-gaussian-splats-you-can-finally-relight-them",
        "accent": "#3b6bff",
        "motif": "sphere",
        "image": "pipeline/media/chaossplat.jpg",
        "hasFull": true
      },
      {
        "id": "mediocre",
        "eyebrow": "AI NEWS",
        "headline": "생성 도구가 끌어내리는\n'적당히 평범한' 결과물",
        "body": "크리스 R 베커는 생성 도구에 기댈수록 작업이 '적당한 평범함'에 갇힌다며 그 기본값을 넘어서는 법을 짚는다.",
        "tool": "AI Workflow",
        "source": "UX Collective",
        "url": "https://uxdesign.cc/the-aggressively-mediocre-fight-ed47b3f9f8f4",
        "accent": "#ff5a4d",
        "motif": "frame",
        "image": "pipeline/media/mediocre.png",
        "hasFull": true
      },
      {
        "id": "landing7",
        "eyebrow": "AI NEWS",
        "headline": "AI 티 안 나는 랜딩페이지\n만드는 구체적인 7가지",
        "body": "AI로 만든 랜딩페이지가 뻔해 보이는 색·서체·여백 같은 일곱 대목을 짚어 고치는 법을 알려준다.",
        "tool": "Figma",
        "source": "DEV Community",
        "url": "https://dev.to/parweb/how-to-make-a-landing-page-that-doesnt-look-ai-generated-7-concrete-fixes-i83",
        "accent": "#0070f3",
        "motif": "frame",
        "image": "pipeline/media/landing7.png",
        "hasFull": true
      }
    ],
    "days": [
      {
        "date": "2026-07-20",
        "cards": [
          {
            "id": "meta-regret",
            "eyebrow": "AI NEWS",
            "tool": "AI Workflow",
            "headline": "메타의 AI 툴 철회 사과, 창작자를 향한 진심일까",
            "body": "접었던 AI 창작 툴에 메타가 뒤늦게 건넨 사과, 창작자를 위한 진심인지 그저 뒷수습인지 되묻는다.",
            "source": "Creative Bloq",
            "url": "https://www.creativebloq.com/design/metas-regret-over-its-scrapped-ai-tool-is-like-a-burglar-apologising-for-the-mess",
            "accent": "#ff5a4d",
            "motif": "frame",
            "image": "pipeline/media/meta-regret.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-21",
        "cards": [
          {
            "id": "nvidia",
            "eyebrow": "AI NEWS",
            "tool": "AI Workflow",
            "headline": "어도비·블렌더·언리얼 안으로 AI 에이전트가 들어오다",
            "body": "MCP 연동으로 AI 에이전트가 어도비·블렌더·언리얼 안에서 장면을 살피고 색 오류를 짚어낸다.",
            "source": "NVIDIA Blog",
            "url": "https://blogs.nvidia.com/blog/siggraph-news-2026/",
            "accent": "#ff5a4d",
            "motif": "frame",
            "image": "pipeline/media/nvidia.jpg",
            "hasFull": true
          },
          {
            "id": "lightcraft",
            "eyebrow": "AI NEWS",
            "tool": "KeyShot",
            "headline": "대본을 가상 촬영장으로 아이폰 한 대로 완성한다",
            "body": "대본만으로 가상 세트를 짓고, 실제 장소 없이 아이폰 한 대로 장면을 찍게 해주는 도구다.",
            "source": "Creative Bloq",
            "url": "https://www.creativebloq.com/3d/i-watched-lightcraft-turn-a-screenplay-into-a-virtual-film-set-using-an-iphone",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/lightcraft.jpg",
            "hasFull": true
          },
          {
            "id": "inversphere",
            "eyebrow": "AI NEWS",
            "tool": "KeyShot",
            "headline": "360도 세계를 통째로 하나의 구에 접어 담다",
            "body": "개발자 VoxelKei가 360도 환경 전체를 하나의 구에 접어 3D 가우시안 스플래팅으로 보여준다.",
            "source": "80 Level",
            "url": "https://80.lv/articles/folding-entire-360-degree-worlds-into-one-sphere-with-3dgs",
            "accent": "#3b6bff",
            "motif": "sphere",
            "image": "pipeline/media/inversphere.jpg",
            "hasFull": true
          },
          {
            "id": "style-refs",
            "eyebrow": "AI NEWS",
            "tool": "AI Workflow",
            "headline": "프롬프트를 늘리기보다 스타일 레퍼런스를 건네라",
            "body": "프롬프트에 단어를 더 쌓을수록 효과는 줄고, 시각 레퍼런스를 주는 편이 결과를 안정적으로 되풀이한다.",
            "source": "DEV Community",
            "url": "https://dev.to/chen_mensen_ac0fc78dae2a4/i-stopped-making-my-ai-image-prompts-longer-style-references-helped-more-4h2m",
            "accent": "#eb367f",
            "motif": "frame",
            "image": "pipeline/media/style-refs.png",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-22",
        "cards": [
          {
            "id": "vray74",
            "eyebrow": "AI NEWS",
            "tool": "KeyShot",
            "headline": "Chaos, 블렌더용 V-Ray 7.4 공개",
            "body": "Chaos가 블렌더용 V-Ray 7.4를 내놓으며 태양광 코스틱과 UDIM, 사이클스 조명 변환 기능을 새로 담았다.",
            "source": "CG Channel",
            "url": "https://www.cgchannel.com/2026/07/chaos-releases-v-ray-7-4-for-blender/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/vray74.jpg",
            "hasFull": true
          },
          {
            "id": "smartroto",
            "eyebrow": "AI NEWS",
            "tool": "KeyShot",
            "headline": "Foundry, Nuke에 AI 로토 스마트로토를 붙이다",
            "body": "Foundry가 Nuke용 SmartRoto를 선보여, 로토 스플라인을 샷 전체에 자동 전파·변형해 수작업보다 최대 4배 빠르다.",
            "source": "CG Channel",
            "url": "https://www.cgchannel.com/2026/07/foundry-releases-new-ai-powered-smartroto-add-on-for-nuke/",
            "accent": "#3b6bff",
            "motif": "sphere",
            "hasFull": true
          },
          {
            "id": "meshy",
            "eyebrow": "AI NEWS",
            "tool": "AI Workflow",
            "headline": "Meshy, 프롬프트 대신 대화하는 3D 파트너로",
            "body": "Meshy의 새 대화형 3D 에이전트는 세션 내내 맥락을 기억해, 스타일이 일관된 3D 에셋을 뽑아낸다.",
            "source": "80 Level",
            "url": "https://80.lv/articles/meshy-wants-ai-to-feel-less-like-a-prompt-and-more-like-a-creative-partner",
            "accent": "#ff5a4d",
            "motif": "frame",
            "image": "pipeline/media/meshy.png",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-23",
        "cards": [
          {
            "id": "maya20262",
            "eyebrow": "AI NEWS",
            "tool": "KeyShot",
            "headline": "마야 2026.2, 스튜디오가 직접 AI 애니메이션을 학습시킨다",
            "body": "새 '브링 유어 오운 데이터'로 자체 키프레임과 모캡을 넣어 모션메이커 AI 모델을 직접 길들일 수 있다.",
            "source": "CG Channel",
            "url": "https://www.cgchannel.com/2026/07/maya-2026-2-lets-you-train-your-own-ai-animation-models/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/maya20262.jpg",
            "hasFull": true
          },
          {
            "id": "3dsmax20262",
            "eyebrow": "AI NEWS",
            "tool": "KeyShot",
            "headline": "3ds Max 2026.2, 가우시안 스플랫을 직접 편집한다",
            "body": "3D 가우시안 스플랫을 불러와 편집하고 조명을 다시 넣어 렌더까지, 방사휘도 캡처가 주류 파이프라인에 들어온다.",
            "source": "CG Channel",
            "url": "https://www.cgchannel.com/2026/07/autodesk-releases-3ds-max-2026-2-with-editable-gaussian-splats/",
            "accent": "#3b6bff",
            "motif": "sphere",
            "image": "pipeline/media/3dsmax20262.jpg",
            "hasFull": true
          },
          {
            "id": "ux-review-ai",
            "eyebrow": "AI NEWS",
            "tool": "AI Workflow",
            "headline": "UX 리뷰를 AI에게 통째로 맡겨 봤다",
            "body": "AI는 UX 리뷰의 든든한 파트너지만 전문가를 대신하진 못하고, 정확도는 모델이 아니라 넣어 준 전문성에서 나온다.",
            "source": "UX Collective",
            "url": "https://uxdesign.cc/i-handed-a-ux-review-over-to-ai-heres-what-happened-0511e73e4ffe",
            "accent": "#ff5a4d",
            "motif": "frame",
            "image": "pipeline/media/ux-review-ai.jpg",
            "hasFull": true
          },
          {
            "id": "screens-demoted",
            "eyebrow": "AI NEWS",
            "tool": "AI Workflow",
            "headline": "화면은 이제 주인공 자리에서 밀려난다",
            "body": "AI가 유능해질수록 화면 UI는 중심에서 물러나고, 디자이너의 일은 어떤 화면이 정말 필요한지 가리는 쪽으로 바뀐다.",
            "source": "UX Collective",
            "url": "https://uxdesign.cc/the-screens-are-getting-demoted-6b40120fcf04",
            "accent": "#eb367f",
            "motif": "frame",
            "image": "pipeline/media/screens-demoted.png",
            "hasFull": true
          },
          {
            "id": "art-director-edge",
            "eyebrow": "AI NEWS",
            "tool": "AI Workflow",
            "headline": "AI 시대, 아트 디렉터의 진짜 무기는 안목이다",
            "body": "생성형 워크플로의 승부처는 더 나은 프롬프트나 도구가 아니라 방향과 취향, 비평으로 다듬은 훈련된 눈이다.",
            "source": "DEV Community",
            "url": "https://dev.to/designbytk/art-directors-advantage-in-the-ai-gen-era-4a3k",
            "accent": "#7928ca",
            "motif": "frame",
            "image": "pipeline/media/art-director-edge.png",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-24",
        "cards": [
          {
            "id": "agentface",
            "eyebrow": "AI NEWS",
            "tool": "Figma",
            "headline": "AI를 기능이 아니라 다음 사용자로 에이전트에게도 얼굴을 준다",
            "body": "AI를 기능이 아닌 다음 사용자로 보고 에이전트에게도 상태가 보이는 화면을 준다.",
            "source": "Builder.io",
            "url": "https://www.builder.io/blog/why-every-agent-needs-a-face",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/agentface.png",
            "hasFull": true
          },
          {
            "id": "ailegible",
            "eyebrow": "AI NEWS",
            "tool": "Design Tokens",
            "headline": "핸드오프 문서의 첫 독자가 개발자에서 에이전트로 바뀌었다",
            "body": "에이전트가 먼저 읽는 스펙엔 토큰과 컴포넌트 이름, 다섯 가지 상태가 들어간다.",
            "source": "DEV Community",
            "url": "https://dev.to/chris_fa_8fca9f4ba09d963/the-design-handoff-changed-heres-what-ai-legible-specs-look-like-38ki",
            "accent": "#2ec5c5",
            "motif": "swatch",
            "image": "pipeline/media/ailegible.png",
            "hasFull": true
          },
          {
            "id": "figmotion",
            "eyebrow": "AI NEWS",
            "tool": "Social",
            "headline": "모션 툴이 무서운 사람을 위한 Figma Motion 수업",
            "body": "Figma 에이전트가 애니메이션 초안을 만들고 디자이너가 캔버스에서 다듬는다.",
            "source": "Figma (YouTube)",
            "url": "https://www.youtube.com/watch?v=OxoV79nv4v0",
            "accent": "#ff2d55",
            "motif": "frame",
            "image": "pipeline/media/figmotion.jpg",
            "hasFull": true
          },
          {
            "id": "trusttest",
            "eyebrow": "AI NEWS",
            "tool": "AI Workflow",
            "headline": "Figma에도 물어야 할 AI 학습 신뢰 질문 네 가지",
            "body": "동의·대칭·고지·탈출 네 질문으로 디자인 도구의 AI 학습 기본값을 따져 묻는다.",
            "source": "UX Collective",
            "url": "https://uxdesign.cc/the-trust-test-four-questions-every-tool-should-answer-even-figma-about-ai-training-model-usage-4f1150f91a30",
            "accent": "#ff5a4d",
            "motif": "frame",
            "image": "pipeline/media/trusttest.png",
            "hasFull": true
          },
          {
            "id": "zcaptis",
            "eyebrow": "AI NEWS",
            "tool": "Text-to-CAD",
            "headline": "HP Z Captis, 스캔한 물성이 Adobe Substance 소재가 된다",
            "body": "HP Z Captis의 소재 캡처가 Adobe Substance 3D 파이프라인과 이어졌다.",
            "source": "DEVELOP3D",
            "url": "https://develop3d.com/3d-scanning/hp-z-captis-adobe-substance/",
            "accent": "#7928ca",
            "motif": "cube",
            "image": "pipeline/media/zcaptis.jpg",
            "hasFull": true
          }
        ]
      }
    ]
  },
  "music": {
    "label": "Music",
    "news": [
      {
        "id": "maqam-archive",
        "eyebrow": "AI NEWS",
        "headline": "미분음 아랍 마캄 튜닝을\nDAW 안으로 가져오는 무료 플러그인",
        "body": "카얌 알라미 연구팀이 수백 개 아랍 마캄 튜닝을 무료 아카이브와 오픈소스 플러그인 탕힘으로 함께 공개했다.",
        "tool": "Music",
        "source": "CDM Create Digital Music",
        "url": "https://cdm.link/digital-arabic-maqam-archive-and-open-source-midi-plug-in/",
        "accent": "#ff2d55",
        "motif": "sphere",
        "image": "pipeline/media/maqam-archive.png",
        "hasFull": true
      },
      {
        "id": "talk-to-spotify",
        "eyebrow": "AI NEWS",
        "headline": "스포티파이 대화형 AI가\n음악 발견의 규칙을 바꾼다",
        "body": "스포티파이가 챗봇형 ‘토크 투 스포티파이’를 베타 공개하며, 프롬프트로 음악을 찾는 대화형 발견을 실험한다.",
        "tool": "Music",
        "source": "Hypebot",
        "url": "https://www.hypebot.com/talk-to-spotify-what-ai-chatbots-mean-for-music-marketing/",
        "accent": "#0070f3",
        "motif": "sphere",
        "image": "pipeline/media/talk-to-spotify.png",
        "hasFull": true
      },
      {
        "id": "landr-fair-trade",
        "eyebrow": "AI NEWS",
        "headline": "AI 학습에 쓰인 곡값을\n인디 아티스트에게 돌려준다",
        "body": "랜더가 AI 학습용 데이터셋 라이선스 순수익의 25%를 참여 아티스트에게 나누고 곡당 5달러도 선지급한다.",
        "tool": "Music",
        "source": "Digital Music News",
        "url": "https://www.digitalmusicnews.com/2026/07/14/landr-fair-trade-ai-program-indie-artists/",
        "accent": "#f5a623",
        "motif": "sphere",
        "image": "pipeline/media/landr-fair-trade.png",
        "hasFull": true
      },
      {
        "id": "lorde-about-the-song",
        "eyebrow": "AI NEWS",
        "headline": "로드가 스포티파이 AI 곡 해설\n기능을 공개적으로 밀어냈다",
        "body": "로드가 자기 곡을 잘못 설명한 스포티파이 AI ‘어바웃 더 송’을 공개 비판하자, 스포티파이가 해당 문구를 지웠다.",
        "tool": "Music",
        "source": "Digital Music News",
        "url": "https://www.digitalmusicnews.com/2026/07/16/lorde-spotify-about-the-song-feature/",
        "accent": "#7928ca",
        "motif": "sphere",
        "image": "pipeline/media/lorde-about-the-song.png",
        "hasFull": true
      }
    ],
    "days": [
      {
        "date": "2026-07-20",
        "cards": [
          {
            "id": "google-ai-mode-ytmusic",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "구글 AI 모드가 유튜브 뮤직과 이어져 대화만으로 플레이리스트를 짠다",
            "body": "구글 검색의 AI 모드가 유튜브 뮤직과 이어졌다. 프롬프트 한 줄로 플레이리스트를 만들고 대화로 결을 맞춘다.",
            "source": "Engadget",
            "url": "https://www.engadget.com/2216707/google-ai-mode-now-integrates-with-canva-youtube-music-and-instacart/",
            "accent": "#ff2d55",
            "motif": "sphere",
            "image": "pipeline/media/google-ai-mode-ytmusic.jpg",
            "hasFull": true
          },
          {
            "id": "almudio-3d-panner",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "헤드폰 믹싱용 무료 바이노럴 패너 알무디오 3D 패너 공개",
            "body": "알무디오가 헤드폰 믹싱과 VR·게임 오디오를 겨냥한 무료 바이노럴 패너 '3D 패너'를 얼리 액세스로 내놨다.",
            "source": "Bedroom Producers Blog",
            "url": "https://bedroomproducersblog.com/2026/07/10/almudio-3d-panner/",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/almudio-3d-panner.jpg",
            "hasFull": true
          },
          {
            "id": "bbc-ai-transparency",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "인간의 창작을 우선하되 BBC, AI 사용을 밝히라 요구한다",
            "body": "BBC는 '의미 있는 인간 창작'을 우선하되, 음악을 제출할 때 AI 도구를 어떻게 썼는지 밝혀 달라고 요구한다.",
            "source": "Complete Music Update",
            "url": "https://completemusicupdate.com/bbcs-music-boss-lorna-clarke-outlines-broadcasters-ai-transparency-commitments-but-can-it-actually-meet-them/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/bbc-ai-transparency.png",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-21",
        "cards": [
          {
            "id": "audiotool3",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "오디오툴 3.0, 브라우저 협업 DAW를 창작 도구 오픈 플랫폼으로",
            "body": "오픈소스 SDK 넥서스로 창작자가 악기와 AI 도구를 브라우저 DAW에 직접 붙여 쓴다.",
            "source": "MusicTech",
            "url": "https://musictech.com/news/gear/audiotool-3-nexus/",
            "accent": "#ff2d55",
            "motif": "sphere",
            "image": "pipeline/media/audiotool3.jpg",
            "hasFull": true
          },
          {
            "id": "aimusiclabel",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "음반업계, 스트리밍 AI 표시제 제안",
            "body": "IFPI 등 8개 단체가 완전 AI 곡은 'AI 제작', AI 활용 곡은 'AI 지원'으로 표시하자고 제안했다.",
            "source": "Music Business Worldwide",
            "url": "https://www.musicbusinessworldwide.com/record-industry-proposes-ai-labeling-system-for-streaming-platforms/",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/aimusiclabel.jpg",
            "hasFull": true
          },
          {
            "id": "eldoraudio",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "기타 연주를 편집 가능한 MIDI로 변환",
            "body": "악기별 모델로 기타 녹음을 편집 가능한 MIDI로 바꿔, 손으로 채보하던 단계를 없앤다.",
            "source": "gearnews",
            "url": "https://www.gearnews.com/guitar-audio-to-midi-eldoraudio-tech/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/eldoraudio.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-22",
        "cards": [
          {
            "id": "suno-imessage",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "수노, 아이메시지 안에서 프롬프트로 30초 AI 곡 생성",
            "body": "아이폰 사용자가 메시지 앱 안에서 텍스트나 음성 프롬프트로 30초짜리 AI 곡을 만든다.",
            "source": "Engadget",
            "url": "https://www.engadget.com/2216558/suno-brings-gen-ai-music-gunk-to-imessage/",
            "accent": "#ff2d55",
            "motif": "sphere",
            "image": "pipeline/media/suno-imessage.jpg",
            "hasFull": true
          },
          {
            "id": "mcp-music",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "AI의 새 USB 포트 MCP, 음악 산업 도구를 하나로 연결",
            "body": "MCP 표준이 음악 플랫폼의 카탈로그와 데이터를 챗GPT·클로드 같은 AI 비서에 곧바로 연결한다.",
            "source": "Music Ally",
            "url": "https://musically.com/2026/07/20/ais-new-usb-port-what-the-mcp-standard-means-for-the-music-industry/",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/mcp-music.png",
            "hasFull": true
          },
          {
            "id": "deezer-ai",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "디저 업로드 절반 이상이 이제 완전 AI 생성 음악",
            "body": "디저는 완전 AI 생성 음악이 하루 업로드의 절반을 넘어 6월 기준 하루 약 9만 곡에 이른다고 밝혔다.",
            "source": "Complete Music Update",
            "url": "https://completemusicupdate.com/ai-generated-tracks-now-account-for-more-than-50-of-deezers-uploads/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/deezer-ai.png",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-23",
        "cards": [
          {
            "id": "lydia",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "직접 만든 AI 모델을 무대 위에서 연주한다",
            "body": "롤랜드와 뉴톤이 만든 시제품 페달은 연주자가 직접 학습시킨 AI 모델로 실시간 연주를 이어가게 해준다.",
            "source": "MusicTech",
            "url": "https://musictech.com/features/interviews/roland-neutone-project-lydia/",
            "accent": "#ff2d55",
            "motif": "sphere",
            "image": "pipeline/media/lydia.jpg",
            "hasFull": true
          },
          {
            "id": "acestudio2",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "강력해진 AI 보컬, 작업 흐름은 아직 거칠다",
            "body": "140종이 넘는 보이스를 갖춘 ACE Studio 2는 성능은 뛰어나지만 느린 렌더링이 발목을 잡는다.",
            "source": "MusicTech",
            "url": "https://musictech.com/reviews/digital-audio-workstations/ace-studio-2-review/",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/acestudio2.jpg",
            "hasFull": true
          },
          {
            "id": "meawchain",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "텍스트 한 줄로 믹싱 체인을 만든다",
            "body": "사파리 오디오의 Meaw Chain은 프롬프트만으로 플러그인 체인을 짜 완성된 믹스에 다가가게 해준다.",
            "source": "MusicTech",
            "url": "https://musictech.com/reviews/plug-ins/meaw-chain-review/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/meawchain.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-24",
        "cards": [
          {
            "id": "concatenator",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "스튜디오 잼을 AI 샘플러에 통째로 넣어 Charli XCX의 드럼이 나왔다",
            "body": "A. G. Cook은 잼 녹음을 Concatenator에 넣어 드럼 패턴을 짰다.",
            "source": "MusicRadar",
            "url": "https://www.musicradar.com/artists/we-were-running-around-the-studio-with-as-many-things-plugged-in-as-possible-just-doing-the-worst-sounds-trying-to-find-the-ugliest-things-how-charli-xcxs-producers-ran-a-jam-session-through-an-ai-sampling-plugin-to-make-no-one-lasts-forever",
            "accent": "#ff2d55",
            "motif": "sphere",
            "image": "pipeline/media/concatenator.jpg",
            "hasFull": true
          },
          {
            "id": "peelstems2",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "스템 분리 지연을 절반으로 줄인 zplane Peel Stems 2",
            "body": "44.1kHz 처리 지연이 483ms에서 245ms로 줄고 잡음도 함께 줄었다.",
            "source": "Sound On Sound",
            "url": "https://www.soundonsound.com/news/peel-stems-2-zplane",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/peelstems2.jpg",
            "hasFull": true
          },
          {
            "id": "sonyudio2",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "소니가 녹음 3만여 건으로 Udio를 다시 고소했다",
            "body": "녹음 3만여 건을 따로 묶은 새 소송으로 배상액이 45억 달러를 넘길 수 있다.",
            "source": "Complete Music Update",
            "url": "https://completemusicupdate.com/sony-music-sues-udio-for-a-second-time-with-the-extra-30-000-recordings-that-could-result-in-4-5-billion-damages/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/sonyudio2.jpg",
            "hasFull": true
          },
          {
            "id": "socanmai",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "AI가 누구 음악을 참고했는지 SOCAN이 추적하기로 했다",
            "body": "SOCAN과 Musical AI가 회원 곡이 AI 결과물에 섞인 정도를 가려낸다.",
            "source": "Hypebot",
            "url": "https://www.hypebot.com/socan-and-musical-ai-to-track-and-eventually-pay-creators-for-ai-use/",
            "accent": "#2ec5c5",
            "motif": "sphere",
            "image": "pipeline/media/socanmai.jpg",
            "hasFull": true
          },
          {
            "id": "aiacts61m",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "AI 아티스트 상위 10팀이 610만 달러를 벌었다",
            "body": "상위 10개 AI 아티스트가 재생 23억 회로 약 610만 달러를 벌었다.",
            "source": "MusicTech",
            "url": "https://musictech.com/news/industry/ai-music-earnings/",
            "accent": "#7928ca",
            "motif": "sphere",
            "image": "pipeline/media/aiacts61m.jpg",
            "hasFull": true
          }
        ]
      }
    ]
  },
  "movies": {
    "label": "Movies",
    "news": [
      {
        "id": "smartroto",
        "eyebrow": "AI NEWS",
        "headline": "파운드리가 AI 로토 플러그인\n스마트로토를 정식 공개했다",
        "body": "아티스트가 주요 프레임만 지정하면 스플라인이 샷 전체에 자동으로 스냅돼 수작업보다 최대 4배 빠르다.",
        "tool": "Movies",
        "source": "fxguide",
        "url": "https://www.fxguide.com/fxfeatured/foundrys-smartroto-ai-assisted-roto-that-aims-to-work-the-way-you-do/",
        "accent": "#0070f3",
        "motif": "frame",
        "image": "pipeline/media/smartroto.jpg",
        "hasFull": true
      },
      {
        "id": "sparkstory",
        "eyebrow": "AI NEWS",
        "headline": "스파크 스토리 베타 공개\n브라우저로 짜는 프리비스",
        "body": "파이널 드래프트 대본을 불러와 장소와 인물을 분석하고 25종 넘는 마블 환경으로 가상 촬영장을 짠다.",
        "tool": "Movies",
        "source": "Animation World Network",
        "url": "https://www.awn.com/news/lightcraft-technology-opens-spark-story-beta-siggraph-2026",
        "accent": "#f5a623",
        "motif": "frame",
        "image": "pipeline/media/sparkstory.jpg",
        "hasFull": true
      },
      {
        "id": "griptape",
        "eyebrow": "AI NEWS",
        "headline": "스튜디오가 AI 모델을 고른다\n파운드리 그립테이프 엔터프라이즈",
        "body": "파이프라인 감독이 아티스트가 쓸 AI 모델을 직접 고르고 온프레미스로 돌려 VFX 워크플로를 통제한다.",
        "tool": "Movies",
        "source": "postPerspective",
        "url": "https://postperspective.com/foundry-adds-griptape-enterprise-for-pro-grade-ai-in-vfx/",
        "accent": "#7928ca",
        "motif": "frame",
        "image": "pipeline/media/griptape.jpg",
        "hasFull": true
      }
    ],
    "days": [
      {
        "date": "2026-07-19",
        "cards": [
          {
            "id": "martini",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "AI 영상 제작진이 함께 쓰는 공유 촬영장 '마티니'가 열렸다",
            "body": "마티니는 세트와 참고 이미지를 2D·3D 공간에서 숏으로 구성하는 웹 협업 도구로, 무료 인디 요금제와 함께 출시됐다.",
            "source": "No Film School",
            "url": "https://nofilmschool.com/martini-ai-film-set",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/martini.jpg",
            "hasFull": true
          },
          {
            "id": "curious-refuge-ai-tools",
            "eyebrow": "AI NEWS",
            "tool": "Social",
            "headline": "이번 주 새 AI 영화 도구, 아티스트를 위한 핵심 업데이트",
            "body": "큐리어스 리퓨지가 아티스트를 위해 이번 주 최신 AI 영화 제작 도구를 정리하며, 새 모션 컨트롤 워크플로에 초점을 맞춘다.",
            "source": "Curious Refuge",
            "url": "https://www.youtube.com/watch?v=GsZmUTLW4wA",
            "accent": "#ff2d55",
            "motif": "frame",
            "image": "pipeline/media/curious-refuge-ai-tools.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-21",
        "cards": [
          {
            "id": "switchlight3",
            "eyebrow": "AI NEWS",
            "tool": "SwitchLight 3",
            "headline": "실사 4K 영상을 언리얼에서 AI로 다시 밝히는 스위치라이트 3",
            "body": "비블 AI가 코리도어 크루의 실사 4K 영상에 스위치라이트 3을 적용해 언리얼 엔진 안에서 바로 쓸 재조명 패스를 만들어냈다.",
            "source": "ProVideo Coalition",
            "url": "https://www.provideocoalition.com/puget-systems-at-siggraph-2026-an-immersive-robo-dojo/",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/switchlight3.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-22",
        "cards": [
          {
            "id": "switchhdr",
            "eyebrow": "AI NEWS",
            "tool": "SwitchHDR",
            "headline": "SDR 영상에서 HDR을 복원하는 AI 모델 등장",
            "body": "비블이 공개한 SwitchHDR는 일반 SDR 영상을 장면 선형 16비트 EXR로 복원해 VFX·후반 작업에 바로 넘긴다.",
            "source": "fxguide",
            "url": "https://www.fxguide.com/fxfeatured/switchhdr-an-ai-model-for-hdr-reconstruction-from-sdr-video/",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/switchhdr.jpg",
            "hasFull": true
          },
          {
            "id": "nvidia-keynote",
            "eyebrow": "AI NEWS",
            "tool": "NVIDIA Research",
            "headline": "뉴럴 렌더링과 월드 모델 엔비디아가 방향을 짚는다",
            "body": "엔비디아 리서치가 SIGGRAPH 2026 기조연설에서 뉴럴 렌더링과 월드 모델, AI 시뮬레이션의 다음 방향을 짚는다.",
            "source": "Animation World Network",
            "url": "https://www.awn.com/news/nvidia-neural-rendering-world-models-and-simulation-keynote-set-siggraph-2026",
            "accent": "#f5a623",
            "motif": "frame",
            "image": "pipeline/media/nvidia-keynote.jpg",
            "hasFull": true
          },
          {
            "id": "spark-story",
            "eyebrow": "AI NEWS",
            "tool": "Spark Story",
            "headline": "실시간 프리비즈 도구 스파크 스토리 베타 열렸다",
            "body": "라이트크래프트의 스파크 스토리는 장면을 블로킹하고 풀 화질 슈퍼데일리를 실시간으로 뽑아 프리비즈 단계를 압축한다.",
            "source": "postPerspective",
            "url": "https://postperspective.com/lightcraft-launches-beta-for-spark-story-interactive-previz-tool/",
            "accent": "#7928ca",
            "motif": "frame",
            "image": "pipeline/media/spark-story.jpg",
            "hasFull": true
          },
          {
            "id": "project-indigo",
            "eyebrow": "AI NEWS",
            "tool": "Project Indigo",
            "headline": "어도비 프로젝트 인디고에 생성형 AI 놀이터가 열린다",
            "body": "어도비가 카메라 앱 프로젝트 인디고에 실험적 AI 플레이그라운드를 더해, 촬영 직후 생성형 편집을 곧바로 적용하게 했다.",
            "source": "RedShark News",
            "url": "https://www.redsharknews.com/adobe-project-indigo-ai-playground",
            "accent": "#2ec5c5",
            "motif": "frame",
            "image": "pipeline/media/project-indigo.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-23",
        "cards": [
          {
            "id": "autodesk",
            "eyebrow": "AI NEWS",
            "tool": "Autodesk",
            "headline": "오토데스크, 마야·3ds Max·아널드에 AI와 가우시안 스플랫 도입",
            "body": "시그래프 2026에서 편집 가능한 가우시안 스플랫과 맞춤 모션 모델로 애니메이션·VFX 작업 흐름을 다듬는다.",
            "source": "postPerspective",
            "url": "https://postperspective.com/autodesk-updates-bring-your-own-data-editable-3d-gaussian-splats-more/",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/autodesk.jpg",
            "hasFull": true
          },
          {
            "id": "animaj",
            "eyebrow": "AI NEWS",
            "tool": "Animaj",
            "headline": "디즈니 주니어와 애니마주가 AI 애니 '오지 폭스' 공개",
            "body": "AI 스튜디오 애니마주가 만든 미취학용 시리즈로, 공개 이틀 만에 조회수 약 80만을 기록했다.",
            "source": "Cartoon Brew",
            "url": "https://www.cartoonbrew.com/series/disney-jr-animaj-ozzy-youtube-264646.html",
            "accent": "#f5a623",
            "motif": "frame",
            "image": "pipeline/media/animaj.jpg",
            "hasFull": true
          },
          {
            "id": "nightborne",
            "eyebrow": "AI NEWS",
            "tool": "Barley Studios",
            "headline": "블롬캄프의 좀비 AI 단편, 결국 데운 슬롭에 그친다",
            "body": "바이트댄스 시드댄스로 만든 '나이트본'은 텍스트-투-비디오가 아직 좋은 영화를 못 만든다는 증거로 남았다.",
            "source": "The Verge",
            "url": "https://www.theverge.com/entertainment/968703/neill-blomkamps-nightborne-barley-studios-seedance",
            "accent": "#7928ca",
            "motif": "frame",
            "image": "pipeline/media/nightborne.jpg",
            "hasFull": true
          },
          {
            "id": "hpzcaptis",
            "eyebrow": "AI NEWS",
            "tool": "HP Z Captis",
            "headline": "HP Z 캡티스와 어도비 서브스턴스, 대규모 디지털 트윈 캡처",
            "body": "더 빠른 캡처와 정밀한 이미징으로 실사 디지털 트윈을 대량 생성해 VFX 파이프라인에 공급한다.",
            "source": "postPerspective",
            "url": "https://postperspective.com/hp-and-adobe-offer-digital-twin-capture-built-for-scale/",
            "accent": "#2ec5c5",
            "motif": "frame",
            "image": "pipeline/media/hpzcaptis.jpg",
            "hasFull": true
          },
          {
            "id": "substance3d",
            "eyebrow": "AI NEWS",
            "tool": "Substance 3D",
            "headline": "어도비 서브스턴스 3D, 생태계 전반에 OpenPBR 지원",
            "body": "OpenPBR 머티리얼 지원을 넓히고 페인터를 개선해 실사 에셋의 텍스처링 도구를 한층 조인다.",
            "source": "No Film School",
            "url": "https://nofilmschool.com/adobe-substance-3d-updates-openpbr",
            "accent": "#eb367f",
            "motif": "frame",
            "image": "pipeline/media/substance3d.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-24",
        "cards": [
          {
            "id": "premiere-genmedia",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "어도비 프리미어 베타, 타임라인에서 바로 생성 영상·효과음을 만든다",
            "body": "빈 트랙을 끌어 프롬프트를 넣으면 프리미어가 고른 모델로 영상이나 효과음을 만들어 타임라인에 붙인다.",
            "source": "ProVideo Coalition",
            "url": "https://www.provideocoalition.com/adobe-premiere-is-adding-a-generative-media-tool/",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/premiere-genmedia.jpg",
            "hasFull": true
          },
          {
            "id": "kokboru",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "12명이 2주 만에 만든 15분 애니 'Kök Börü'",
            "body": "손그림 캐릭터와 채색 텍스처로 생성 결과를 붙잡아, 열두 명이 2주 만에 15분짜리 애니메이션을 끝냈다.",
            "source": "Animation World Network",
            "url": "https://www.awn.com/news/higgsfield-debuts-k-k-b-r-showcasing-hybrid-human-ai-animation-pipeline",
            "accent": "#f5a623",
            "motif": "frame",
            "image": "pipeline/media/kokboru.jpg",
            "hasFull": true
          },
          {
            "id": "sam2matte",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "무료 SAM2 매팅 툴, 머리카락 로토를 몇 시간 줄인다",
            "body": "머리카락 같은 잔털까지 자동으로 따내 손 마스킹에 쓰던 몇 시간을 덜어주는 무료 SAM2 매팅 도구다.",
            "source": "Curious Refuge",
            "url": "https://www.youtube.com/shorts/Tr0AzAljYUE",
            "accent": "#7928ca",
            "motif": "frame",
            "image": "pipeline/media/sam2matte.jpg",
            "hasFull": true
          },
          {
            "id": "promiseai",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "'샤크네이도'와 '닥터후' 작가가 이제 AI 영화를 만든다",
            "body": "Promise AI가 각본가·쇼러너를 생성형 창작자와 짝지어 AI 영화 'Tuning In'을 냈다.",
            "source": "The Hollywood Reporter",
            "url": "https://www.hollywoodreporter.com/business/digital/ai-films-promise-sharknado-doctor-who-1236648616/",
            "accent": "#2ec5c5",
            "motif": "frame",
            "image": "pipeline/media/promiseai.png",
            "hasFull": true
          },
          {
            "id": "raindanceimgn",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "레인댄스와 IMGN, 인디 감독에게 1만 파운드 펀드와 개발 허브",
            "body": "제34회 레인댄스가 IMGN과 £10,000 펀드를 열고 2027년 각본 공모에 개발 허브를 붙였다.",
            "source": "Variety",
            "url": "https://variety.com/2026/film/global/raindance-israel-ai-platform-imgn-development-fund-1236809594/",
            "accent": "#eb367f",
            "motif": "frame",
            "image": "pipeline/media/raindanceimgn.jpg",
            "hasFull": true
          }
        ]
      }
    ]
  },
  "games": {
    "label": "Games",
    "news": [
      {
        "id": "nvidia-dgx-agents",
        "eyebrow": "AI NEWS",
        "headline": "DGX 스테이션에서 개인 AI 에이전트를\n30분 만에 로컬 실행",
        "body": "엔비디아 에이전트 툴킷을 깔면 DGX 스테이션에서 인터넷 없이 개인 에이전트를 로컬로 돌린다.",
        "tool": "Games",
        "source": "Wccftech",
        "url": "https://wccftech.com/nvidia-brings-local-ai-agents-to-dgx-station-pc-with-agent-toolkit/",
        "accent": "#7928ca",
        "motif": "cube",
        "image": "pipeline/media/nvidia-dgx-agents.jpg",
        "hasFull": true
      },
      {
        "id": "steam-aidisclosure-devs",
        "eyebrow": "AI NEWS",
        "headline": "스팀의 생성 AI 표기 의무는 옳다\n개발자들이 밸브 편에 섰다",
        "body": "팀 스위니의 반대와 달리 개발자들은 생성 AI 사용을 소비자에게 알려야 한다며 밸브의 표기 의무를 지지했다.",
        "tool": "Games",
        "source": "GamesRadar+",
        "url": "https://www.gamesradar.com/games/steams-required-ai-disclosure-is-the-right-move-devs-say-gen-ai-should-be-called-out-in-games-and-support-valves-store-mandate/",
        "accent": "#f5a623",
        "motif": "cube",
        "video": "pipeline/media/steam-aidisclosure-devs.mp4",
        "poster": "pipeline/media/steam-aidisclosure-devs.jpg",
        "image": "pipeline/media/steam-aidisclosure-devs.jpg",
        "hasFull": true
      }
    ],
    "days": [
      {
        "date": "2026-07-20",
        "cards": [
          {
            "id": "damagecontrol",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "게임 배경 작업을 빠르게, 블렌더 툴킷 데미지 컨트롤",
            "body": "제시 미에티넨이 스캐터·스머지 같은 생성형 도구를 묶어 블렌더 툴킷 데미지 컨트롤을 내놨다.",
            "source": "80 Level",
            "url": "https://80.lv/articles/jesse-miettinen-s-the-last-of-us-like-generator-finally-launches",
            "accent": "#7928ca",
            "motif": "cube",
            "image": "pipeline/media/damagecontrol.jpg",
            "hasFull": true
          },
          {
            "id": "indiedevs25",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "인디 개발자 25명이 생성형 AI를 피하는 이유",
            "body": "인디 스튜디오 25곳은 생성형 AI가 되레 더 못한 게임을 만든다며 도입을 꺼린다고 말한다.",
            "source": "GamesRadar+",
            "url": "https://www.gamesradar.com/games/it-creates-lesser-games-indie-game-studios-are-supposed-to-love-generative-ai-so-why-do-the-25-devs-i-spoke-to-avoid-it/",
            "accent": "#0070f3",
            "motif": "cube",
            "image": "pipeline/media/indiedevs25.jpg",
            "hasFull": true
          },
          {
            "id": "metahumancrowds",
            "eyebrow": "AI NEWS",
            "tool": "Social",
            "headline": "언리얼에서 대규모 메타휴먼 군중 만들기",
            "body": "언리얼 페스트 세션에서 Mass와 Nanite로 메타휴먼 군중을 대규모로 채우는 파이프라인을 소개한다.",
            "source": "Unreal Engine",
            "url": "https://www.youtube.com/watch?v=wQoa1j4Rgss",
            "accent": "#ff2d55",
            "motif": "frame",
            "image": "pipeline/media/metahumancrowds.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-21",
        "cards": [
          {
            "id": "houdini22",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "후디니 22, 가우시안 스플랫을 게임 아트 파이프라인에 넣다",
            "body": "후디니 22가 신경 방사장 캡처인 가우시안 스플랫을 네이티브로 품고 UI까지 새로 짜 게임 제작 흐름에 들어왔다.",
            "source": "80 Level",
            "url": "https://80.lv/articles/houdini-22-is-out-now-bringing-native-gaussian-splats-new-ui-and-more",
            "accent": "#7928ca",
            "motif": "cube",
            "image": "pipeline/media/houdini22.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-22",
        "cards": [
          {
            "id": "unity7",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "유니티 7, 빌드를 다시 짜지 않는 AI 최적화 업그레이드 로드맵",
            "body": "유니티 7은 기존 6 구조를 그대로 둔 채 빌드 재작성 없이 올라가고, AI 그래픽 최적화를 새로 얹는다.",
            "source": "Game Developer",
            "url": "https://www.gamedeveloper.com/programming/unity-unveils-unity-7-roadmap-with-update-path-that-won-t-break-your-build",
            "accent": "#7928ca",
            "motif": "cube",
            "image": "pipeline/media/unity7.png",
            "hasFull": true
          },
          {
            "id": "dlss5",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "엔비디아, DLSS 5 AI 필터를 조절하는 슬라이더 둘을 공개",
            "body": "엔비디아가 DLSS 5 신경 렌더를 손볼 슬라이더 둘을 개발자에게 열어 주고, 제어 장치를 더 늘리고 있다.",
            "source": "PC Gamer",
            "url": "https://www.pcgamer.com/hardware/nvidia-finally-reveals-what-controls-devs-actually-have-for-dlss-5-and-dont-worry-folks-there-are-two-main-sliders-to-control-the-ai-filter/",
            "accent": "#0070f3",
            "motif": "cube",
            "image": "pipeline/media/dlss5.jpg",
            "hasFull": true
          },
          {
            "id": "meshy3dagent",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "메시 3D 에이전트, 단발 프롬프트를 대화형 창작 파트너로 바꾸다",
            "body": "메시 3D 에이전트 베타가 대화로 맥락을 이어 스타일이 일관된 에셋을 만들고, 블렌더와 언리얼, 유니티로 내보낸다.",
            "source": "80 Level",
            "url": "https://80.lv/articles/meshy-wants-ai-to-feel-less-like-a-prompt-and-more-like-a-creative-partner/",
            "accent": "#f5a623",
            "motif": "cube",
            "image": "pipeline/media/meshy3dagent.png",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-23",
        "cards": [
          {
            "id": "nvidia-siggraph",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "시그래프서 공개된 뉴럴 렌더링과 툴 속으로 들어온 AI 에이전트",
            "body": "엔비디아가 시그래프에서 뉴럴 렌더링과 코스모스 3 월드 모델을 공개해 실시간 4K 창작을 앞당겼다.",
            "source": "NVIDIA Blog",
            "url": "https://blogs.nvidia.com/blog/siggraph-news-2026/",
            "accent": "#7928ca",
            "motif": "cube",
            "image": "pipeline/media/nvidia-siggraph.jpg",
            "hasFull": true
          },
          {
            "id": "ai-2d-to-3d",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "2D 도면을 게임용 3D로 바꾸는 새 AI 기법 공개",
            "body": "평면 2D 그림을 게임에 바로 쓸 수 있는 3D 형상으로 바꿔, 수작업 모델링 부담을 크게 던다.",
            "source": "PC Gamer",
            "url": "https://www.pcgamer.com/software/ai/new-method-teaches-ai-to-make-2d-designs-3d-and-now-im-afraid-this-will-be-how-the-robots-learn-to-build-themselves-without-us/",
            "accent": "#0070f3",
            "motif": "cube",
            "image": "pipeline/media/ai-2d-to-3d.jpg",
            "hasFull": true
          },
          {
            "id": "atelico",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "저전력 온디바이스 AI를 내건 스튜디오 아텔리코",
            "body": "스튜디오 아텔리코가 저전력 온디바이스 생성형 AI와 정당한 보수를 앞세워 데뷔작을 준비한다.",
            "source": "GamesIndustry.biz",
            "url": "https://www.gamesindustry.biz/ethical-low-power-and-on-device-studio-atelicos-vision-for-the-future-of-generative-ai",
            "accent": "#f5a623",
            "motif": "cube",
            "image": "pipeline/media/atelico.png",
            "hasFull": true
          },
          {
            "id": "kaneko",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "페르소나 아티스트, 다음 작품엔 생성형 AI를 쓰지 않는다",
            "body": "카네코 카즈마가 두 차례 반발을 겪은 뒤, 직접 그리는 편이 빠르다며 차기작에 생성형 AI를 뺀다.",
            "source": "GamesRadar+",
            "url": "https://www.gamesradar.com/games/rpg/persona-and-shin-megami-tensei-artist-isnt-using-generative-ai-in-his-next-game-following-backlash-to-his-last-2-deckbuilders/",
            "accent": "#2ec5c5",
            "motif": "cube",
            "image": "pipeline/media/kaneko.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-24",
        "cards": [
          {
            "id": "fnaivoice",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "7월 30일부터 Fortnite 섬에 말을 받아치는 AI NPC가 선다",
            "body": "Epic이 Gemini로 움직이는 캐릭터 음성 36종을 열고, 7월 30일 UEFN 대화 시스템이 실험 딱지를 뗀다.",
            "source": "Polygon",
            "url": "https://www.polygon.com/epic-games-ai-fortnite/",
            "accent": "#7928ca",
            "motif": "cube",
            "image": "pipeline/media/fnaivoice.jpg",
            "hasFull": true
          },
          {
            "id": "openriglogic",
            "eyebrow": "AI NEWS",
            "tool": "Social",
            "headline": "MetaHuman 릭을 Blender로 그대로 옮기는 OpenRigLogic",
            "body": "Poly Hammer가 OpenRigLogic을 Blender에 붙여, MetaHuman DNA의 거동을 Unreal 밖에서 손본다.",
            "source": "Unreal Engine (YouTube)",
            "url": "https://www.youtube.com/watch?v=WZhDr5Ktf9c",
            "accent": "#ff2d55",
            "motif": "frame",
            "image": "pipeline/media/openriglogic.jpg",
            "hasFull": true
          },
          {
            "id": "steamcensus",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "Steam 신작 셋 중 하나가 이미 AI 사용을 밝히고 있다",
            "body": "2026년 Steam 신작의 30.8%가 AI 사용을 표기했고, 이 기울기면 2027~2028년에 절반을 넘긴다.",
            "source": "PC Gamer",
            "url": "https://www.pcgamer.com/gaming-industry/steam-week-in-review-take-cover-because-it-looks-like-more-than-half-of-steam-games-will-have-an-ai-disclosure-by-2027-2028/",
            "accent": "#0070f3",
            "motif": "cube",
            "image": "pipeline/media/steamcensus.png",
            "hasFull": true
          },
          {
            "id": "mkwiicomp",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "Mario Kart Wii를 PC로 옮긴 첫 정적 리컴파일, 문제는 AI",
            "body": "patchzy가 AI 코딩으로 Mario Kart Wii를 PC용 정적 리컴파일로 옮겼고, 팬들은 곧장 등을 돌렸다.",
            "source": "GamesRadar+",
            "url": "https://www.gamesradar.com/games/racing/mario-kart-wii-is-being-rebuilt-for-pc-but-the-projects-ai-vibe-coding-instantly-soured-many-nintendo-fans-on-the-project/",
            "accent": "#f5a623",
            "motif": "cube",
            "image": "pipeline/media/mkwiicomp.jpg",
            "hasFull": true
          },
          {
            "id": "inworldtts",
            "eyebrow": "AI NEWS",
            "tool": "Social",
            "headline": "잘 뽑힌 AI 음성 테이크를 다시 불러오는 Inworld 기록",
            "body": "Inworld TTS Playground가 뽑아낸 음성마다 보이스와 모델, 설정을 남겨 언제든 되살린다.",
            "source": "Inworld AI (YouTube)",
            "url": "https://www.youtube.com/watch?v=0uPl_pmFwAQ",
            "accent": "#2ec5c5",
            "motif": "frame",
            "image": "pipeline/media/inworldtts.jpg",
            "hasFull": true
          }
        ]
      }
    ]
  },
  "books": {
    "label": "Books",
    "news": [
      {
        "id": "booklens-hallucinate",
        "tool": "Books",
        "eyebrow": "AI NEWS",
        "headline": "금서 지정 돕는 AI 도구\n없는 책까지 지어낸다",
        "body": "시민단체가 만든 북렌즈는 실재하지 않는 책에도 부적절 판정을 붙여 리뷰를 통째로 지어낸다.",
        "source": "Book Riot",
        "url": "https://bookriot.com/tools-used-by-book-banners-2026/",
        "accent": "#f5a623",
        "motif": "swatch",
        "image": "pipeline/media/booklens-hallucinate.jpg",
        "hasFull": true
      },
      {
        "id": "ai-nonfiction-hill",
        "tool": "Books",
        "eyebrow": "AI NEWS",
        "headline": "아마존에 팔리는 AI 전기\n기자가 저자를 추적했다",
        "body": "뉴욕타임스 기자 캐시미어 힐은 아마존에 올라온 자신의 AI 전기를 직접 사서 읽고 정체를 파헤쳤다.",
        "source": "Jane Friedman",
        "url": "https://janefriedman.com/new-york-times-journalist-investigates-origins-of-ai-generated-nonfiction/",
        "accent": "#0070f3",
        "motif": "swatch",
        "image": "pipeline/media/ai-nonfiction-hill.png",
        "hasFull": true
      },
      {
        "id": "open-science-2",
        "tool": "Books",
        "eyebrow": "AI NEWS",
        "headline": "AI가 논문을 대신 읽는 시대\n개방보다 신뢰가 문제다",
        "body": "AI가 연구를 요약해 전하는 환경에서 오픈 사이언스의 무게중심이 접근에서 신뢰로 옮겨간다.",
        "source": "The Scholarly Kitchen",
        "url": "https://scholarlykitchen.sspnet.org/2026/07/14/open-science-2-0-building-understanding-in-an-ai-mediated-world/",
        "accent": "#7928ca",
        "motif": "swatch",
        "image": "pipeline/media/open-science-2.jpg",
        "hasFull": true
      }
    ],
    "days": [
      {
        "date": "2026-07-20",
        "cards": [
          {
            "id": "fiction-feast",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "픽션 피스트, 자체 소설에 AI 도구를 쓴다고 통보",
            "body": "영국의 대표 단편 잡지 픽션 피스트가 자체 제작 소설에 AI 도구를 활용하겠다고 기고 작가들에게 알렸다.",
            "source": "The Bookseller",
            "url": "https://www.thebookseller.com/news/take-a-breaks-fiction-feast-to-use-ai-tools-on-stories-created-in-house",
            "accent": "#f5a623",
            "motif": "swatch",
            "image": "pipeline/media/fiction-feast.jpg",
            "hasFull": true
          },
          {
            "id": "cartland-voice",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "볼린다, 인터뷰와 자료로 카틀랜드 목소리를 복원",
            "body": "오디오북 출판사 볼린다가 인터뷰와 자료 조사에 사람의 손을 더해 고 바버라 카틀랜드의 목소리를 AI로 되살렸다.",
            "source": "The Bookseller",
            "url": "https://www.thebookseller.com/news/interviews-research-and-human-input-used-by-bolinda-to-create-ai-clone-of-barbara-cartlands-voice",
            "accent": "#0070f3",
            "motif": "swatch",
            "image": "pipeline/media/cartland-voice.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-21",
        "cards": [
          {
            "id": "fanfic-ai-markers",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "복사해 붙인 글에 남은 흔적이 AI 사용을 드러내다",
            "body": "클로드에서 붙여넣은 글에 숨은 표식이 남아, AI를 꺼리던 팬픽 커뮤니티의 광범위한 AI 사용이 드러났다.",
            "source": "Jane Friedman",
            "url": "https://janefriedman.com/fanfiction-sites-reveal-plenty-of-ai-assisted-writing-to-community-dismay/",
            "accent": "#f5a623",
            "motif": "swatch",
            "image": "pipeline/media/fanfic-ai-markers.jpg",
            "hasFull": true
          },
          {
            "id": "vancouver-ai-disclosure",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "학술계 AI 공개를 위한 밴쿠버 표준이 나온다",
            "body": "AI를 쓴 연구자 약 3분의 1이 이를 밝히지 않는다는 조사 뒤, 학술 AI 공개 기준인 '밴쿠버 표준'이 국제 협의로 마련된다.",
            "source": "The Scholarly Kitchen",
            "url": "https://scholarlykitchen.sspnet.org/2026/07/13/guest-post-research-needs-a-shared-standard-for-ai-disclosure/",
            "accent": "#0070f3",
            "motif": "swatch",
            "image": "pipeline/media/vancouver-ai-disclosure.jpg",
            "hasFull": true
          },
          {
            "id": "bloomsbury-ai-licensing",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "블룸즈버리, AI 라이선스로 실적을 끌어올리다",
            "body": "블룸즈버리가 구글 AI 라이선스 수익으로 실적을 올린 가운데, 여러 출판사는 무단 학습을 이유로 구글을 제소했다.",
            "source": "Publishing Perspectives",
            "url": "https://publishingperspectives.com/2026/07/around-the-book-world-monday-july-20th-2026/",
            "accent": "#7928ca",
            "motif": "swatch",
            "image": "pipeline/media/bloomsbury-ai-licensing.png",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-22",
        "cards": [
          {
            "id": "ai-narration",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "청취자 61%가 AI 낭독을 사람 목소리로 착각했다",
            "body": "스포큰 조사에서 청취자 61%가 AI 낭독을 사람 목소리로 착각했고, 다역 장면에선 AI 낭독을 선호했다.",
            "source": "Publishers Weekly",
            "url": "https://www.publishersweekly.com/pw/by-topic/digital/content-and-e-books/article/100825-some-favor-ai-narration-for-multi-cast-audiobooks-even-as-interest-in-ai-voices-wanes.html",
            "accent": "#f5a623",
            "motif": "swatch",
            "image": "pipeline/media/ai-narration.jpg",
            "hasFull": true
          },
          {
            "id": "ai-uptake",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "출판이 전 창작 산업에서 AI 도입률 가장 낮은 6%",
            "body": "크리에이티브 액세스 조사에서 출판의 AI 도입률은 전 창작 산업을 통틀어 가장 낮은 6%로 집계됐다.",
            "source": "The Bookseller",
            "url": "https://www.thebookseller.com/news/publishing-has-lowest-uptake-of-ai-across-creative-industries-according-to-new-report",
            "accent": "#0070f3",
            "motif": "swatch",
            "image": "pipeline/media/ai-uptake.jpg",
            "hasFull": true
          },
          {
            "id": "hologram",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "책 대신 AI 요약본을 읽는 출판의 '홀로그램 문제'",
            "body": "로버트 무어는 AI 요약과 챗봇이 책의 알맹이를 대신 전하면서 독자가 원작 대신 복제물을 소비하게 된다고 본다.",
            "source": "Literary Hub",
            "url": "https://lithub.com/publishing-has-a-hologram-problem-and-its-growing/",
            "accent": "#7928ca",
            "motif": "swatch",
            "image": "pipeline/media/hologram.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-23",
        "cards": [
          {
            "id": "zedoc",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "노르웨이 Beat에서 갈라져 나온 에이전틱 메타데이터 플랫폼",
            "body": "주제 분류와 접근성 보강, ONIX 생성과 오디오북 챕터 분할을 한 흐름으로 묶어 자동으로 처리한다.",
            "source": "Publishers Weekly",
            "url": "https://www.publishersweekly.com/pw/by-topic/international/international-book-news/article/100855-norway-s-beat-spins-out-zedoc-a-new-agentic-ai-platform.html",
            "accent": "#f5a623",
            "motif": "swatch",
            "image": "pipeline/media/zedoc.png",
            "hasFull": true
          },
          {
            "id": "ai-course",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "AI 시대를 책임 있게 건너가려는 출판인을 위한 4주 과정",
            "body": "4주짜리 온라인 프로그램으로 AI 기술을 익히고 실무 워크플로와 사내 사용 지침까지 함께 세운다.",
            "source": "Publishing Perspectives",
            "url": "https://publishingperspectives.com/2026/07/announcing-a-course-to-help-publishers-navigate-the-ai-age-responsibly/",
            "accent": "#0070f3",
            "motif": "swatch",
            "image": "pipeline/media/ai-course.png",
            "hasFull": true
          },
          {
            "id": "editor-ai-survey",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "멜버른대와 RMIT가 나선 편집자 AI 사용 실태 조사",
            "body": "두 대학 연구진이 호주의 출판사와 편집자가 생성형 AI를 실제로 어떻게 쓰는지 설문으로 살핀다.",
            "source": "Books+Publishing",
            "url": "https://www.booksandpublishing.com.au/articles/2026/07/21/334844/researchers-to-investigate-local-editor-and-publisher-ai-use/",
            "accent": "#7928ca",
            "motif": "swatch",
            "image": "pipeline/media/editor-ai-survey.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-24",
        "cards": [
          {
            "id": "anthropic-final",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "Anthropic 해적판 학습 소송 15억 달러 합의가 최종 확정",
            "body": "판사는 작품당 약 3,000달러가 고의 침해 법정 최저 배상액의 네 배라며 합의안을 승인했다.",
            "source": "Publishers Weekly",
            "url": "https://www.publishersweekly.com/pw/by-topic/digital/copyright/article/100888-judge-gives-final-approval-in-1-5-billion-settlement-in-anthropic-copyright-case.html",
            "accent": "#f5a623",
            "motif": "swatch",
            "image": "pipeline/media/anthropic-final.jpg",
            "hasFull": true
          },
          {
            "id": "bloomsbury-payout",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "Bloomsbury가 AI 합의금으로 1400만 파운드를 받는다",
            "body": "합의 명단에 오른 자사 도서 14,087종 덕에 수수료를 뗀 1870만 달러를 저자와 나눈다.",
            "source": "The Bookseller",
            "url": "https://www.thebookseller.com/news/bloomsbury-lands-14m-in-anthropic-ai-settlement",
            "accent": "#0070f3",
            "motif": "swatch",
            "image": "pipeline/media/bloomsbury-payout.jpg",
            "hasFull": true
          },
          {
            "id": "substack-pangram",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "Substack이 붙인 AI 탐지 라벨 작성자가 끄면 사라진다",
            "body": "Pangram이 돌린 판독 결과를 독자가 열어볼 수 있지만, 작성자가 끄면 표시가 사라진다.",
            "source": "Jane Friedman",
            "url": "https://janefriedman.com/substack-adds-ai-detection-tools-but-creators-can-disable-them/",
            "accent": "#7928ca",
            "motif": "swatch",
            "hasFull": true
          },
          {
            "id": "wiley-genesis",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "Genesis Mission에 들어간 유일한 과학 출판사 Wiley",
            "body": "Nvidia와 AWS, Microsoft, IBM 사이에서 동료심사 콘텐츠를 대는 유일한 출판사로 합류했다.",
            "source": "Publishing Perspectives",
            "url": "https://publishingperspectives.com/2026/07/wiley-joins-genesis-mission-consortium-in-support-of-u-s-ai-goals/",
            "accent": "#2ec5c5",
            "motif": "swatch",
            "image": "pipeline/media/wiley-genesis.jpg",
            "hasFull": true
          },
          {
            "id": "ipa-congress-ai",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "쿠알라룸푸르 IPA 총회 패널을 생성형 AI가 뒤덮었다",
            "body": "학습 데이터 라이선싱부터 편집·제작 조직 개편까지, 패널 토론마다 생성형 AI가 중심에 놓였다.",
            "source": "Books+Publishing",
            "url": "https://www.booksandpublishing.com.au/articles/2026/07/22/334849/ai-dominates-global-publishing-conversation-at-ipa-congress/",
            "accent": "#eb367f",
            "motif": "swatch",
            "hasFull": true
          }
        ]
      }
    ]
  },
  "gadgets": {
    "label": "Gadgets",
    "news": [
      {
        "id": "gemma-4-pixel-tpu",
        "eyebrow": "AI NEWS",
        "headline": "구글 젬마 4, 픽셀 10의\nTPU에 맞춘 온디바이스 모델",
        "body": "텐서 G5 TPU에 최적화된 젬마 4가 픽셀 10에서 인터넷 없이 이미지와 음성을 바로 처리한다.",
        "tool": "Google",
        "source": "9to5Google",
        "url": "https://9to5google.com/2026/07/14/pixel-10-gemma-4/",
        "accent": "#ff5a4d",
        "motif": "headset",
        "image": "pipeline/media/gemma-4-pixel-tpu.jpg",
        "hasFull": true
      },
      {
        "id": "gemini-nano-4-fold8",
        "eyebrow": "AI NEWS",
        "headline": "제미나이 나노 4, 삼성 새\n폴더블에 처음 탑재됐다",
        "body": "140여 개 언어를 지원하는 제미나이 나노 4가 갤럭시 Z 폴드 8과 플립 8에 처음 실려 기기에서 돈다.",
        "tool": "Gemini",
        "source": "Android Authority",
        "url": "https://www.androidauthority.com/galaxy-z-fold-8-flip-8-gemini-nano-4-3690495/",
        "accent": "#0070f3",
        "motif": "headset",
        "image": "pipeline/media/gemini-nano-4-fold8.jpg",
        "hasFull": true
      },
      {
        "id": "samsung-intelligent-eyewear",
        "eyebrow": "AI NEWS",
        "headline": "삼성 인텔리전트 아이웨어\n제미나이 안경을 만져봤다",
        "body": "워비파커·젠틀몬스터와 만든 제미나이 안경은 얇고 가벼웠고 통역과 길안내를 손 없이 처리한다.",
        "tool": "Samsung",
        "source": "Android Central",
        "url": "https://www.androidcentral.com/wearables/samsung-google-intelligent-eyewear-galaxy-unpacked-2026-hands-on",
        "accent": "#eb367f",
        "motif": "headset",
        "image": "pipeline/media/samsung-intelligent-eyewear.jpg",
        "hasFull": true
      },
      {
        "id": "garmin-cirqa-band",
        "eyebrow": "AI NEWS",
        "headline": "핏빗 에어 비켜, 가민\nCIRQA 스마트밴드 등장",
        "body": "가민 첫 화면 없는 밴드 CIRQA는 배터리가 열흘 가고 80가지 운동을 추적한다.",
        "tool": "Garmin",
        "source": "Android Authority",
        "url": "https://www.androidauthority.com/garmin-cirqa-smart-band-launch-3689862/",
        "accent": "#f5a623",
        "motif": "headset",
        "image": "pipeline/media/garmin-cirqa-band.jpg",
        "hasFull": true
      }
    ],
    "days": [
      {
        "date": "2026-07-20",
        "cards": [
          {
            "id": "codex-micro",
            "eyebrow": "AI NEWS",
            "tool": "OpenAI",
            "headline": "OpenAI 첫 하드웨어는 코딩 에이전트 조작용 매크로패드",
            "body": "OpenAI가 첫 하드웨어로 AI 코딩 에이전트를 손끝으로 다루는 230달러짜리 매크로패드 코덱스 마이크로를 내놨다.",
            "source": "Gizmodo",
            "url": "https://gizmodo.com/openai-just-launched-its-first-hardware-product-and-its-a-tiny-keyboard-for-bossing-around-ai-agents-2000786080",
            "accent": "#ff5a4d",
            "motif": "headset",
            "image": "pipeline/media/codex-micro.jpg",
            "hasFull": true
          },
          {
            "id": "gemini-home",
            "eyebrow": "AI NEWS",
            "tool": "Google",
            "headline": "제미나이, 연이은 명령도 끊김 없이 받아낸다",
            "body": "구글 홈의 제미나이가 음성 확인 없이 연이은 명령을 더 안정적으로 처리한다. 날씨·스포츠 화면도 함께 나아진다.",
            "source": "Android Authority",
            "url": "https://www.androidauthority.com/gemini-for-home-visual-improvements-3685543/",
            "accent": "#0070f3",
            "motif": "headset",
            "image": "pipeline/media/gemini-home.jpg",
            "hasFull": true
          },
          {
            "id": "ear-3a",
            "eyebrow": "AI NEWS",
            "tool": "Nothing",
            "headline": "99달러 이어버드에 들어온 온디바이스 녹음",
            "body": "노싱 이어(3a)는 99달러에 꼬집어 담는 오디오 스냅샷 녹음부터 AI 전사·요약, 챗GPT 연동까지 챙겼다.",
            "source": "Engadget",
            "url": "https://www.engadget.com/2202348/nothing-announces-ear-3a-sub-dollar100-anc-earbuds/",
            "accent": "#7928ca",
            "motif": "headset",
            "image": "pipeline/media/ear-3a.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-21",
        "cards": [
          {
            "id": "meta-privacy-led",
            "eyebrow": "AI NEWS",
            "tool": "Meta",
            "headline": "프라이버시 LED를 가리면 카메라가 스스로 꺼진다",
            "body": "메타가 v26 업데이트를 배포해 프라이버시 LED가 훼손되면 스마트글래스 카메라가 꺼지도록 강제한다.",
            "source": "9to5Google",
            "url": "https://9to5google.com/2026/07/07/meta-ray-ban-smart-glasses-privacy-light-camera-update/",
            "accent": "#ff5a4d",
            "motif": "headset",
            "image": "pipeline/media/meta-privacy-led.jpg",
            "hasFull": true
          },
          {
            "id": "samsung-unpacked-july",
            "eyebrow": "AI NEWS",
            "tool": "Samsung",
            "headline": "갤럭시 언팩, 폴드8과 에이전트 AI를 함께 연다",
            "body": "22일 언팩을 앞두고 삼성이 갤럭시 Z 폴드8·플립8과 함께 예측·에이전트형 갤럭시 AI를 선보일 전망이다.",
            "source": "Gizmodo",
            "url": "https://gizmodo.com/what-were-expecting-at-samsungs-july-galaxy-unpacked-2026-2000787025",
            "accent": "#0070f3",
            "motif": "headset",
            "image": "pipeline/media/samsung-unpacked-july.jpg",
            "hasFull": true
          },
          {
            "id": "irobot-roomba-relaunch",
            "eyebrow": "AI NEWS",
            "tool": "iRobot",
            "headline": "아이로봇, AI 청소기 다섯 종을 다시 내놓는다",
            "body": "새 주인을 맞은 아이로봇이 AI 주행과 165도 온수 세척 도크를 갖춘 룸바 다섯 종을 공개했다.",
            "source": "Gizmodo",
            "url": "https://gizmodo.com/irobot-debuts-five-self-emptying-roombas-most-under-1000-2000782317",
            "accent": "#f5a623",
            "motif": "headset",
            "image": "pipeline/media/irobot-roomba-relaunch.jpg",
            "hasFull": true
          },
          {
            "id": "brainco-mind-robot",
            "eyebrow": "AI NEWS",
            "tool": "BrainCo",
            "headline": "생각만으로 로봇을 0.2초 만에 움직인다",
            "body": "브레인코가 뇌파를 200밀리초 안에 로봇 명령으로 바꾸는, 손이 필요 없는 제어 플랫폼을 시연했다.",
            "source": "Notebookcheck",
            "url": "https://www.notebookcheck.net/BrainCo-unveils-brain-controlled-robot-AI-platform-The-future-of-eating-Cheetos-while-building-PCs-hands-free-with-just-a-thought.1346280.0.html",
            "accent": "#2ec5c5",
            "motif": "headset",
            "image": "pipeline/media/brainco-mind-robot.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-22",
        "cards": [
          {
            "id": "oneui9",
            "eyebrow": "AI NEWS",
            "tool": "One UI",
            "headline": "원 UI 9, 갤럭시에 에이전트형 제미나이 탑재",
            "body": "원 UI 9가 제미나이로 앱을 넘나들며 작업을 대신하고, 문장만으로 위젯을 만들어 준다.",
            "source": "9to5Google",
            "url": "https://9to5google.com/2026/07/14/one-ui-9-all-the-features-you-need-to-know-video/",
            "accent": "#0070f3",
            "motif": "headset",
            "image": "pipeline/media/oneui9.jpg",
            "hasFull": true
          },
          {
            "id": "galaxyglasses",
            "eyebrow": "AI NEWS",
            "tool": "Samsung",
            "headline": "삼성 갤럭시 글래스 유출 스냅드래곤 AR1에 제미나이",
            "body": "유출된 갤럭시 글래스는 스냅드래곤 AR1과 듀얼 카메라를 얹고, 제미나이로 촬영과 번역을 손 안 대고 해낸다.",
            "source": "Android Authority",
            "url": "https://www.androidauthority.com/samsung-galaxy-glasses-specs-leak-3689677/",
            "accent": "#eb367f",
            "motif": "headset",
            "image": "pipeline/media/galaxyglasses.jpg",
            "hasFull": true
          },
          {
            "id": "snapdragonx2e",
            "eyebrow": "AI NEWS",
            "tool": "Qualcomm",
            "headline": "스냅드래곤 X2 엘리트 AI PC 인텔·AMD와 정면 비교",
            "body": "노트북체크가 80-TOPS 헥사곤 NPU를 얹은 스냅드래곤 X2 엘리트를 최신 인텔·AMD 노트북과 맞대어 봤다.",
            "source": "Notebookcheck",
            "url": "https://www.notebookcheck.net/After-testing-several-Snapdragon-X2E-systems-this-is-how-they-compare-to-the-latest-Intel-and-AMD-laptops.1343280.0.html",
            "accent": "#f5a623",
            "motif": "headset",
            "image": "pipeline/media/snapdragonx2e.jpg",
            "hasFull": true
          },
          {
            "id": "surfacelaptop138",
            "eyebrow": "AI NEWS",
            "tool": "Microsoft",
            "headline": "서피스 랩톱 13.8, X2 플러스로 코파일럿+ 기준을 넘다",
            "body": "서피스 랩톱 13.8은 스냅드래곤 X2 플러스로 CPU가 크게 빨라졌고, NPU가 코파일럿+ 온디바이스 AI 기준을 넘어선다.",
            "source": "Notebookcheck",
            "url": "https://www.notebookcheck.net/Snapdragon-X2-Plus-is-much-faster-Microsoft-Surface-Laptop-13-8-2026-Review.1334131.0.html",
            "accent": "#7928ca",
            "motif": "headset",
            "image": "pipeline/media/surfacelaptop138.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-23",
        "cards": [
          {
            "id": "adobe-indigo",
            "eyebrow": "AI NEWS",
            "tool": "Adobe",
            "headline": "어도비가 실험 카메라 앱에 생성형 AI를 대거 담았다",
            "body": "어도비가 프로젝트 인디고에 AI 플레이그라운드를 더해, 촬영하는 순간 방해물을 지우고 원하는 스타일을 입힌다.",
            "source": "Engadget",
            "url": "https://www.engadget.com/2218980/adobe-crams-multiple-ai-tools-into-its-experimental-camera-app/",
            "accent": "#ff5a4d",
            "motif": "headset",
            "image": "pipeline/media/adobe-indigo.jpg",
            "hasFull": true
          },
          {
            "id": "openai-speaker",
            "eyebrow": "AI NEWS",
            "tool": "OpenAI",
            "headline": "오픈AI의 첫 기기는 카메라 달린 휴대용 스피커라는 보도",
            "body": "오픈AI의 첫 기기는 카메라와 센서를 단 화면 없는 휴대용 스피커로, 먼저 나서 돕는 AI 동반자를 지향한다고 전해진다.",
            "source": "9to5Mac",
            "url": "https://9to5mac.com/2026/07/14/report-openais-first-device-will-be-a-portable-speaker-with-a-camera-and-other-sensors/",
            "accent": "#0070f3",
            "motif": "headset",
            "image": "pipeline/media/openai-speaker.jpg",
            "hasFull": true
          },
          {
            "id": "samsung-health-assistant",
            "eyebrow": "AI NEWS",
            "tool": "Samsung",
            "headline": "삼성, 흩어진 건강 데이터를 풀어 주는 AI 건강 비서",
            "body": "삼성이 삼성 헬스에 AI 건강 비서 베타를 더해, 갤럭시 폰·워치·링 데이터를 읽고 의사가 검증한 조언을 건넨다.",
            "source": "Engadget",
            "url": "https://www.engadget.com/2219698/samsung-aims-to-help-you-make-more-sense-of-health-data-with-a-new-ai-powered-assistant/",
            "accent": "#f5a623",
            "motif": "headset",
            "image": "pipeline/media/samsung-health-assistant.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-24",
        "cards": [
          {
            "id": "frameworkdesk",
            "eyebrow": "AI NEWS",
            "tool": "Framework",
            "headline": "프레임워크가 192GB 미니 PC로 로컬 AI를 책상에 올린다",
            "body": "프레임워크가 192GB 메모리를 얹은 미니 PC를 내놔, DeepSeek V4 Flash 같은 모델을 로컬에서 돌린다.",
            "source": "Digital Trends",
            "url": "https://www.digitaltrends.com/computing/framework-desktop-brings-ryzen-ai-max-192gb-ram-and-local-ai-to-a-mini-pc/",
            "accent": "#ff5a4d",
            "motif": "headset",
            "image": "pipeline/media/frameworkdesk.jpg",
            "hasFull": true
          },
          {
            "id": "mouthpad",
            "eyebrow": "AI NEWS",
            "tool": "Augmental",
            "headline": "혀로 굴리는 트랙패드에 바이브 코더가 눈독을 들인다",
            "body": "접근성 기기로 나온 Augmental의 MouthPad와 Vox를 AI 코더들이 손 안 쓰는 입력 장치로 데려간다.",
            "source": "Gizmodo",
            "url": "https://gizmodo.com/vibe-coders-ai-augmental-mouthpad-keyboard-mouse-2000789866",
            "accent": "#0070f3",
            "motif": "headset",
            "image": "pipeline/media/mouthpad.jpg",
            "hasFull": true
          },
          {
            "id": "voicepad",
            "eyebrow": "AI NEWS",
            "tool": "Apple",
            "headline": "macOS 27 베타에 숨어 있던 시리 '보이스 패드'",
            "body": "macOS 27 베타에 숨은 화면에서 커서를 움직이면 미국식 영어 목소리 13종이 공간 음향으로 가까워지고 멀어진다.",
            "source": "MacRumors",
            "url": "https://www.macrumors.com/2026/07/23/macos-27-beta-hidden-siri-voice-ui/",
            "accent": "#f5a623",
            "motif": "headset",
            "image": "pipeline/media/voicepad.jpg",
            "hasFull": true
          },
          {
            "id": "ultrahumanemerald",
            "eyebrow": "AI NEWS",
            "tool": "Ultrahuman",
            "headline": "울트라휴먼이 분석을 전부 반지 안으로 옮겼다",
            "body": "울트라휴먼이 앱을 에메랄드로 갈아엎고 분석을 전부 기기에서 처리해, 인터넷이 끊겨도 인사이트가 나온다.",
            "source": "Engadget",
            "url": "https://www.engadget.com/2220780/ultrahuman-overhauls-app-brings-all-of-its-analysis-on-device/",
            "accent": "#7928ca",
            "motif": "headset",
            "image": "pipeline/media/ultrahumanemerald.jpg",
            "hasFull": true
          },
          {
            "id": "geminilivemini",
            "eyebrow": "AI NEWS",
            "tool": "Google",
            "headline": "1세대 구글 홈 미니까지 제미나이 라이브가 내려온다",
            "body": "구글이 1세대 홈 미니와 네스트 허브에 제미나이 라이브를 풀어, 오래된 스피커와 주고받는 대화가 열린다.",
            "source": "Android Authority",
            "url": "https://www.androidauthority.com/gemini-live-expands-to-first-gen-google-speakers-3690874/",
            "accent": "#2ec5c5",
            "motif": "headset",
            "image": "pipeline/media/geminilivemini.jpg",
            "hasFull": true
          }
        ]
      }
    ]
  },
  "science": {
    "label": "Science",
    "news": [
      {
        "id": "hiddenvars",
        "eyebrow": "AI NEWS",
        "headline": "숨은 변수 몇 개로\n거대 물질계를 미리 읽는 AI",
        "body": "싱가포르국립대 연구진은 원자 일부의 힘만 보고 50만 개가 넘는 원자 물질계의 거동을 예측했다.",
        "tool": "Science",
        "source": "Tech Xplore",
        "url": "https://techxplore.com/news/2026-07-ai-hidden-material-microscopic-large.html",
        "accent": "#2ec5c5",
        "motif": "sphere",
        "image": "pipeline/media/hiddenvars.jpg",
        "hasFull": true
      },
      {
        "id": "xrayagent",
        "eyebrow": "AI NEWS",
        "headline": "싱크로트론 실험을 스스로\n정렬하는 에이전트 AI",
        "body": "스탠퍼드·SLAC 연구진의 에이전트 AI가 빔라인에서 단결정 시료를 스스로 정렬했다.",
        "tool": "Science",
        "source": "Phys.org",
        "url": "https://phys.org/news/2026-07-ai-agent-synchrotron-ray-experimental.html",
        "accent": "#0070f3",
        "motif": "sphere",
        "image": "pipeline/media/xrayagent.jpg",
        "hasFull": true
      },
      {
        "id": "cellforge",
        "eyebrow": "AI NEWS",
        "headline": "바이오 생산 현장에 맞춘\nAI 세포 공학 모델",
        "body": "Triplebar Bio 연구진은 생산 조건에 맞춰 숙주 세포의 유전체 설계를 돕는 AI를 만들고 있다.",
        "tool": "Science",
        "source": "GEN (Genetic Engineering & Biotechnology News)",
        "url": "https://www.genengnews.com/topics/bioprocessing/ai-protein-engineering-model-designed-for-biomanufacturing/",
        "accent": "#7928ca",
        "motif": "sphere",
        "image": "pipeline/media/cellforge.png",
        "hasFull": true
      },
      {
        "id": "creepnorm",
        "eyebrow": "AI NEWS",
        "headline": "생명과학에 소리 없이\n스며드는 LLM, 경계는 없다",
        "body": "생성형 AI가 경계도 정해지기 전에 생명과학 연구의 일상으로 스며든다고 국제 연구진이 경고했다.",
        "tool": "Science",
        "source": "Phys.org",
        "url": "https://phys.org/news/2026-07-large-language-quietly-reshaping-life.html",
        "accent": "#f5a623",
        "motif": "sphere",
        "image": "pipeline/media/creepnorm.jpg",
        "hasFull": true
      }
    ],
    "days": [
      {
        "date": "2026-07-20",
        "cards": [
          {
            "id": "chathea",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "언어 모델이 소재 탐색 과정을 스스로 이끌며 촉매를 찾다",
            "body": "도호쿠대가 만든 ChatHEA가 문헌 조사부터 실험 설계까지 도맡아 사람의 직관 너머에 있던 연료전지 촉매를 찾아냈다.",
            "source": "Phys.org",
            "url": "https://phys.org/news/2026-07-large-language-discovery-catalysts-energy.html",
            "accent": "#2ec5c5",
            "motif": "sphere",
            "image": "pipeline/media/chathea.jpg",
            "hasFull": true
          },
          {
            "id": "k2-18b-seti",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "머신러닝이 수백만 전파 신호를 솎아 외계 탐색을 앞당기다",
            "body": "자동 머신러닝이 수백만 개의 전파 후보를 솎아 내며 외계 신호 탐색 속도를 크게 끌어올렸다.",
            "source": "ScienceDaily",
            "url": "https://www.sciencedaily.com/releases/2026/07/260712011748.htm",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/k2-18b-seti.jpg",
            "hasFull": true
          },
          {
            "id": "scent-ai",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "AI가 식물 향기에서 수면을 돕는 성분을 골라내다",
            "body": "싱가포르국립대가 향기 분자 2,391종으로 학습시킨 모델이 96.1% 정확도로 수면을 돕는 화합물을 가려냈다.",
            "source": "Phys.org",
            "url": "https://phys.org/news/2026-07-ai-aromatic-scent-compounds.html",
            "accent": "#7928ca",
            "motif": "sphere",
            "image": "pipeline/media/scent-ai.jpg",
            "hasFull": true
          },
          {
            "id": "denning-critique",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "기계는 인간의 암묵적 지식을 담아낼 수 없다",
            "body": "피터 데닝은 튜링이 1950년 논문에 심은 가정이 틀렸고 기계는 상식 같은 암묵지를 담아내지 못한다고 본다.",
            "source": "ScienceDaily",
            "url": "https://www.sciencedaily.com/releases/2026/07/260713084850.htm",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/denning-critique.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-21",
        "cards": [
          {
            "id": "willow-rl",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "구글 양자컴퓨터가 계산하며 자기 오류로부터 배운다",
            "body": "강화학습으로 양자컴퓨터가 자기 오류 데이터를 학습해, 계산 중 스스로 재보정하며 논리 오류율을 20% 낮췄다.",
            "source": "The Quantum Insider",
            "url": "https://thequantuminsider.com/2026/07/10/google-study-shows-quantum-computer-can-learn-from-its-own-errors-while-it-computes/",
            "accent": "#2ec5c5",
            "motif": "sphere",
            "image": "pipeline/media/willow-rl.png",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-22",
        "cards": [
          {
            "id": "flatband",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "물리 지식을 담은 AI가 2D 양자물질 탐색을 앞당긴다",
            "body": "물리 법칙을 학습한 모델이 후보 1만여 개를 98.2% 정확도로 가려내, 느린 양자 계산을 대신한다.",
            "source": "Phys.org",
            "url": "https://phys.org/news/2026-07-physics-based-machine-method-2d.html",
            "accent": "#2ec5c5",
            "motif": "sphere",
            "image": "pipeline/media/flatband.jpg",
            "hasFull": true
          },
          {
            "id": "baker",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "단백질을 처음부터 설계하는 베이커 연구소의 열린 뇌",
            "body": "100여 명이 모인 베이커 연구소가 딥러닝 도구를 함께 쓰며, 항체와 효소를 원자 단위로 새로 설계한다.",
            "source": "GEN (Genetic Engineering & Biotechnology News)",
            "url": "https://www.genengnews.com/topics/artificial-intelligence/protein-designs-ai-revolution-inside-david-bakers-communal-brain/",
            "accent": "#7928ca",
            "motif": "sphere",
            "image": "pipeline/media/baker.jpeg",
            "hasFull": true
          },
          {
            "id": "openadmet",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "약물 대사 예측 대회에서 크기보다 데이터가 이겼다",
            "body": "약물 대사 예측 공개 대회가 28개 팀 공동 1위로 끝나, 성능은 모델 크기가 아니라 데이터 질이 가른다.",
            "source": "STAT News",
            "url": "https://www.statnews.com/2026/07/14/openadmet-ai-drug-metabolism-prediction-inductive-bio/",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/openadmet.jpg",
            "hasFull": true
          },
          {
            "id": "goflow",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "위성 열영상으로 미세한 바다 표층 해류를 복원한다",
            "body": "GOFLOW가 위성 열영상에서 기존 모델이 놓친 미세 해류를 복원해, 기후·날씨 예측을 더 정밀하게 한다.",
            "source": "Tech Xplore",
            "url": "https://techxplore.com/news/2026-07-ai-powered-unprecedented-insight-earth.html",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/goflow.jpg",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-23",
        "cards": [
          {
            "id": "oled-ai",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "AI와 양자화학을 결합해 효율적 청색 OLED 소재를 찾다",
            "body": "나고야대가 양자화학 데이터로 학습한 AI로 분자 1만 7000여 개를 훑어 유망한 청색 발광체를 찾아냈다.",
            "source": "Phys.org",
            "url": "https://phys.org/news/2026-07-ai-quantum-chemistry-combine-efficient.html",
            "accent": "#2ec5c5",
            "motif": "sphere",
            "image": "pipeline/media/oled-ai.jpg",
            "hasFull": true
          },
          {
            "id": "deeptimegate",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "물리 법칙을 실시간 검증하는 AI가 산란 매질 너머를 본다",
            "body": "UCLA의 딥타임게이트는 물리 법칙을 실시간 잣대로 삼아 산란 매질 너머를 저가 카메라로 찍어낸다.",
            "source": "Phys.org",
            "url": "https://phys.org/news/2026-07-physics-based-ai-boost-biomedical.html",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/deeptimegate.jpg",
            "hasFull": true
          },
          {
            "id": "qewc",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "양자 기하학으로 양자 AI의 '치명적 망각'을 막다",
            "body": "QEWC는 양자 상태의 기하 구조에 학습을 묶어, 새 과제를 익혀도 앞서 배운 능력을 잃지 않게 한다.",
            "source": "The Quantum Insider",
            "url": "https://thequantuminsider.com/2026/07/22/new-framework-uses-quantum-geometry-to-help-quantum-ai-systems-remember-what-they-learn/",
            "accent": "#7928ca",
            "motif": "sphere",
            "image": "pipeline/media/qewc.png",
            "hasFull": true
          }
        ]
      },
      {
        "date": "2026-07-24",
        "cards": [
          {
            "id": "cyclecover",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "GPT-5.6이 50년 묵은 그래프 이론 난제를 증명했다",
            "body": "GPT-5.6 Sol이 50년 넘게 풀리지 않던 순환 이중 덮개 추측을 증명했다.",
            "source": "Scientific American",
            "url": "https://www.scientificamerican.com/article/chatgpt-just-proved-another-50-year-old-math-conjecture/",
            "accent": "#2ec5c5",
            "motif": "sphere",
            "image": "pipeline/media/cyclecover.jpg",
            "hasFull": true
          },
          {
            "id": "scoresmooth",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "확산 모델은 왜 베끼지 않고 새 이미지를 그려내는가",
            "body": "신경망 규제로 점수 함수가 뭉툭해지면서 확산 모델이 훈련 데이터 사이를 메운다.",
            "source": "Google Research",
            "url": "https://research.google/blog/towards-demystifying-the-creativity-of-diffusion-models/",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/scoresmooth.png",
            "hasFull": true
          },
          {
            "id": "peptiverse",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "합성하기 전에 펩타이드 성질을 먼저 알려주는 오픈소스 AI",
            "body": "PeptiVerse는 합성 전에 펩타이드의 용해도·독성·체내 지속 시간을 계산한다.",
            "source": "Phys.org",
            "url": "https://phys.org/news/2026-07-source-ai-key-peptide-traits.html",
            "accent": "#7928ca",
            "motif": "sphere",
            "image": "pipeline/media/peptiverse.jpg",
            "hasFull": true
          },
          {
            "id": "medmia",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "의료 AI는 생각보다 환자 정보를 훨씬 많이 흘린다",
            "body": "의료 AI에서 환자 정보가 알려진 것보다 쉽게 샜고, 위험은 소수 집단에 쏠렸다.",
            "source": "Physics World",
            "url": "https://physicsworld.com/a/privacy-risks-from-medical-ai-are-greater-than-previously-thought/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/medmia.jpg",
            "hasFull": true
          },
          {
            "id": "curiobot",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "호기심을 심은 로봇이 언어를 두 배 빨리 배웠다",
            "body": "호기심을 보상받은 로봇은 언어를 두 배 빨리 익혔고, 유아처럼 문법 오류를 거쳤다.",
            "source": "Tech Xplore",
            "url": "https://techxplore.com/news/2026-07-playful-ai-robots-mirror-toddlers.html",
            "accent": "#eb367f",
            "motif": "sphere",
            "image": "pipeline/media/curiobot.jpg",
            "hasFull": true
          }
        ]
      }
    ]
  }
};
  window.AX_SECTION_ORDER = [
  "design",
  "music",
  "movies",
  "games",
  "books",
  "gadgets",
  "science"
];
  // back-compat (large-card app reads these until it becomes section-aware):
  window.AX_NEWS = [
  {
    "id": "flux3",
    "eyebrow": "AI NEWS",
    "headline": "FLUX 3, 소리까지 담은\n20초 영상 생성으로 확장",
    "body": "블랙포레스트랩스가 이미지에 더해 소리까지 담은 20초 영상을 만드는 FLUX 3를 한정 공개했다.",
    "tool": "KeyShot",
    "source": "VentureBeat",
    "url": "https://venturebeat.com/technology/black-forest-labs-launches-flux-3-capable-of-generating-images-and-20-second-video-with-audio-but-in-limited-release-to-start",
    "accent": "#f5a623",
    "motif": "sphere",
    "image": "pipeline/media/flux3.png",
    "hasFull": true
  },
  {
    "id": "chaossplat",
    "eyebrow": "AI NEWS",
    "headline": "가우시안 스플랫에 조명을\n다시 입히는 카오스 V-Ray",
    "body": "카오스가 V-Ray 7.4에서 스캔한 가우시안 스플랫을 CG 조명으로 다시 밝히는 리라이팅 기능을 열었다.",
    "tool": "KeyShot",
    "source": "Creative Bloq",
    "url": "https://www.creativebloq.com/3d/chaos-just-fixed-one-of-the-biggest-problems-with-gaussian-splats-you-can-finally-relight-them",
    "accent": "#3b6bff",
    "motif": "sphere",
    "image": "pipeline/media/chaossplat.jpg",
    "hasFull": true
  },
  {
    "id": "mediocre",
    "eyebrow": "AI NEWS",
    "headline": "생성 도구가 끌어내리는\n'적당히 평범한' 결과물",
    "body": "크리스 R 베커는 생성 도구에 기댈수록 작업이 '적당한 평범함'에 갇힌다며 그 기본값을 넘어서는 법을 짚는다.",
    "tool": "AI Workflow",
    "source": "UX Collective",
    "url": "https://uxdesign.cc/the-aggressively-mediocre-fight-ed47b3f9f8f4",
    "accent": "#ff5a4d",
    "motif": "frame",
    "image": "pipeline/media/mediocre.png",
    "hasFull": true
  },
  {
    "id": "landing7",
    "eyebrow": "AI NEWS",
    "headline": "AI 티 안 나는 랜딩페이지\n만드는 구체적인 7가지",
    "body": "AI로 만든 랜딩페이지가 뻔해 보이는 색·서체·여백 같은 일곱 대목을 짚어 고치는 법을 알려준다.",
    "tool": "Figma",
    "source": "DEV Community",
    "url": "https://dev.to/parweb/how-to-make-a-landing-page-that-doesnt-look-ai-generated-7-concrete-fixes-i83",
    "accent": "#0070f3",
    "motif": "frame",
    "image": "pipeline/media/landing7.png",
    "hasFull": true
  }
];
  window.AX_DAYS = [
  {
    "date": "2026-07-20",
    "cards": [
      {
        "id": "meta-regret",
        "eyebrow": "AI NEWS",
        "tool": "AI Workflow",
        "headline": "메타의 AI 툴 철회 사과, 창작자를 향한 진심일까",
        "body": "접었던 AI 창작 툴에 메타가 뒤늦게 건넨 사과, 창작자를 위한 진심인지 그저 뒷수습인지 되묻는다.",
        "source": "Creative Bloq",
        "url": "https://www.creativebloq.com/design/metas-regret-over-its-scrapped-ai-tool-is-like-a-burglar-apologising-for-the-mess",
        "accent": "#ff5a4d",
        "motif": "frame",
        "image": "pipeline/media/meta-regret.jpg",
        "hasFull": true
      }
    ]
  },
  {
    "date": "2026-07-21",
    "cards": [
      {
        "id": "nvidia",
        "eyebrow": "AI NEWS",
        "tool": "AI Workflow",
        "headline": "어도비·블렌더·언리얼 안으로 AI 에이전트가 들어오다",
        "body": "MCP 연동으로 AI 에이전트가 어도비·블렌더·언리얼 안에서 장면을 살피고 색 오류를 짚어낸다.",
        "source": "NVIDIA Blog",
        "url": "https://blogs.nvidia.com/blog/siggraph-news-2026/",
        "accent": "#ff5a4d",
        "motif": "frame",
        "image": "pipeline/media/nvidia.jpg",
        "hasFull": true
      },
      {
        "id": "lightcraft",
        "eyebrow": "AI NEWS",
        "tool": "KeyShot",
        "headline": "대본을 가상 촬영장으로 아이폰 한 대로 완성한다",
        "body": "대본만으로 가상 세트를 짓고, 실제 장소 없이 아이폰 한 대로 장면을 찍게 해주는 도구다.",
        "source": "Creative Bloq",
        "url": "https://www.creativebloq.com/3d/i-watched-lightcraft-turn-a-screenplay-into-a-virtual-film-set-using-an-iphone",
        "accent": "#f5a623",
        "motif": "sphere",
        "image": "pipeline/media/lightcraft.jpg",
        "hasFull": true
      },
      {
        "id": "inversphere",
        "eyebrow": "AI NEWS",
        "tool": "KeyShot",
        "headline": "360도 세계를 통째로 하나의 구에 접어 담다",
        "body": "개발자 VoxelKei가 360도 환경 전체를 하나의 구에 접어 3D 가우시안 스플래팅으로 보여준다.",
        "source": "80 Level",
        "url": "https://80.lv/articles/folding-entire-360-degree-worlds-into-one-sphere-with-3dgs",
        "accent": "#3b6bff",
        "motif": "sphere",
        "image": "pipeline/media/inversphere.jpg",
        "hasFull": true
      },
      {
        "id": "style-refs",
        "eyebrow": "AI NEWS",
        "tool": "AI Workflow",
        "headline": "프롬프트를 늘리기보다 스타일 레퍼런스를 건네라",
        "body": "프롬프트에 단어를 더 쌓을수록 효과는 줄고, 시각 레퍼런스를 주는 편이 결과를 안정적으로 되풀이한다.",
        "source": "DEV Community",
        "url": "https://dev.to/chen_mensen_ac0fc78dae2a4/i-stopped-making-my-ai-image-prompts-longer-style-references-helped-more-4h2m",
        "accent": "#eb367f",
        "motif": "frame",
        "image": "pipeline/media/style-refs.png",
        "hasFull": true
      }
    ]
  },
  {
    "date": "2026-07-22",
    "cards": [
      {
        "id": "vray74",
        "eyebrow": "AI NEWS",
        "tool": "KeyShot",
        "headline": "Chaos, 블렌더용 V-Ray 7.4 공개",
        "body": "Chaos가 블렌더용 V-Ray 7.4를 내놓으며 태양광 코스틱과 UDIM, 사이클스 조명 변환 기능을 새로 담았다.",
        "source": "CG Channel",
        "url": "https://www.cgchannel.com/2026/07/chaos-releases-v-ray-7-4-for-blender/",
        "accent": "#f5a623",
        "motif": "sphere",
        "image": "pipeline/media/vray74.jpg",
        "hasFull": true
      },
      {
        "id": "smartroto",
        "eyebrow": "AI NEWS",
        "tool": "KeyShot",
        "headline": "Foundry, Nuke에 AI 로토 스마트로토를 붙이다",
        "body": "Foundry가 Nuke용 SmartRoto를 선보여, 로토 스플라인을 샷 전체에 자동 전파·변형해 수작업보다 최대 4배 빠르다.",
        "source": "CG Channel",
        "url": "https://www.cgchannel.com/2026/07/foundry-releases-new-ai-powered-smartroto-add-on-for-nuke/",
        "accent": "#3b6bff",
        "motif": "sphere",
        "hasFull": true
      },
      {
        "id": "meshy",
        "eyebrow": "AI NEWS",
        "tool": "AI Workflow",
        "headline": "Meshy, 프롬프트 대신 대화하는 3D 파트너로",
        "body": "Meshy의 새 대화형 3D 에이전트는 세션 내내 맥락을 기억해, 스타일이 일관된 3D 에셋을 뽑아낸다.",
        "source": "80 Level",
        "url": "https://80.lv/articles/meshy-wants-ai-to-feel-less-like-a-prompt-and-more-like-a-creative-partner",
        "accent": "#ff5a4d",
        "motif": "frame",
        "image": "pipeline/media/meshy.png",
        "hasFull": true
      }
    ]
  },
  {
    "date": "2026-07-23",
    "cards": [
      {
        "id": "maya20262",
        "eyebrow": "AI NEWS",
        "tool": "KeyShot",
        "headline": "마야 2026.2, 스튜디오가 직접 AI 애니메이션을 학습시킨다",
        "body": "새 '브링 유어 오운 데이터'로 자체 키프레임과 모캡을 넣어 모션메이커 AI 모델을 직접 길들일 수 있다.",
        "source": "CG Channel",
        "url": "https://www.cgchannel.com/2026/07/maya-2026-2-lets-you-train-your-own-ai-animation-models/",
        "accent": "#f5a623",
        "motif": "sphere",
        "image": "pipeline/media/maya20262.jpg",
        "hasFull": true
      },
      {
        "id": "3dsmax20262",
        "eyebrow": "AI NEWS",
        "tool": "KeyShot",
        "headline": "3ds Max 2026.2, 가우시안 스플랫을 직접 편집한다",
        "body": "3D 가우시안 스플랫을 불러와 편집하고 조명을 다시 넣어 렌더까지, 방사휘도 캡처가 주류 파이프라인에 들어온다.",
        "source": "CG Channel",
        "url": "https://www.cgchannel.com/2026/07/autodesk-releases-3ds-max-2026-2-with-editable-gaussian-splats/",
        "accent": "#3b6bff",
        "motif": "sphere",
        "image": "pipeline/media/3dsmax20262.jpg",
        "hasFull": true
      },
      {
        "id": "ux-review-ai",
        "eyebrow": "AI NEWS",
        "tool": "AI Workflow",
        "headline": "UX 리뷰를 AI에게 통째로 맡겨 봤다",
        "body": "AI는 UX 리뷰의 든든한 파트너지만 전문가를 대신하진 못하고, 정확도는 모델이 아니라 넣어 준 전문성에서 나온다.",
        "source": "UX Collective",
        "url": "https://uxdesign.cc/i-handed-a-ux-review-over-to-ai-heres-what-happened-0511e73e4ffe",
        "accent": "#ff5a4d",
        "motif": "frame",
        "image": "pipeline/media/ux-review-ai.jpg",
        "hasFull": true
      },
      {
        "id": "screens-demoted",
        "eyebrow": "AI NEWS",
        "tool": "AI Workflow",
        "headline": "화면은 이제 주인공 자리에서 밀려난다",
        "body": "AI가 유능해질수록 화면 UI는 중심에서 물러나고, 디자이너의 일은 어떤 화면이 정말 필요한지 가리는 쪽으로 바뀐다.",
        "source": "UX Collective",
        "url": "https://uxdesign.cc/the-screens-are-getting-demoted-6b40120fcf04",
        "accent": "#eb367f",
        "motif": "frame",
        "image": "pipeline/media/screens-demoted.png",
        "hasFull": true
      },
      {
        "id": "art-director-edge",
        "eyebrow": "AI NEWS",
        "tool": "AI Workflow",
        "headline": "AI 시대, 아트 디렉터의 진짜 무기는 안목이다",
        "body": "생성형 워크플로의 승부처는 더 나은 프롬프트나 도구가 아니라 방향과 취향, 비평으로 다듬은 훈련된 눈이다.",
        "source": "DEV Community",
        "url": "https://dev.to/designbytk/art-directors-advantage-in-the-ai-gen-era-4a3k",
        "accent": "#7928ca",
        "motif": "frame",
        "image": "pipeline/media/art-director-edge.png",
        "hasFull": true
      }
    ]
  },
  {
    "date": "2026-07-24",
    "cards": [
      {
        "id": "agentface",
        "eyebrow": "AI NEWS",
        "tool": "Figma",
        "headline": "AI를 기능이 아니라 다음 사용자로 에이전트에게도 얼굴을 준다",
        "body": "AI를 기능이 아닌 다음 사용자로 보고 에이전트에게도 상태가 보이는 화면을 준다.",
        "source": "Builder.io",
        "url": "https://www.builder.io/blog/why-every-agent-needs-a-face",
        "accent": "#0070f3",
        "motif": "frame",
        "image": "pipeline/media/agentface.png",
        "hasFull": true
      },
      {
        "id": "ailegible",
        "eyebrow": "AI NEWS",
        "tool": "Design Tokens",
        "headline": "핸드오프 문서의 첫 독자가 개발자에서 에이전트로 바뀌었다",
        "body": "에이전트가 먼저 읽는 스펙엔 토큰과 컴포넌트 이름, 다섯 가지 상태가 들어간다.",
        "source": "DEV Community",
        "url": "https://dev.to/chris_fa_8fca9f4ba09d963/the-design-handoff-changed-heres-what-ai-legible-specs-look-like-38ki",
        "accent": "#2ec5c5",
        "motif": "swatch",
        "image": "pipeline/media/ailegible.png",
        "hasFull": true
      },
      {
        "id": "figmotion",
        "eyebrow": "AI NEWS",
        "tool": "Social",
        "headline": "모션 툴이 무서운 사람을 위한 Figma Motion 수업",
        "body": "Figma 에이전트가 애니메이션 초안을 만들고 디자이너가 캔버스에서 다듬는다.",
        "source": "Figma (YouTube)",
        "url": "https://www.youtube.com/watch?v=OxoV79nv4v0",
        "accent": "#ff2d55",
        "motif": "frame",
        "image": "pipeline/media/figmotion.jpg",
        "hasFull": true
      },
      {
        "id": "trusttest",
        "eyebrow": "AI NEWS",
        "tool": "AI Workflow",
        "headline": "Figma에도 물어야 할 AI 학습 신뢰 질문 네 가지",
        "body": "동의·대칭·고지·탈출 네 질문으로 디자인 도구의 AI 학습 기본값을 따져 묻는다.",
        "source": "UX Collective",
        "url": "https://uxdesign.cc/the-trust-test-four-questions-every-tool-should-answer-even-figma-about-ai-training-model-usage-4f1150f91a30",
        "accent": "#ff5a4d",
        "motif": "frame",
        "image": "pipeline/media/trusttest.png",
        "hasFull": true
      },
      {
        "id": "zcaptis",
        "eyebrow": "AI NEWS",
        "tool": "Text-to-CAD",
        "headline": "HP Z Captis, 스캔한 물성이 Adobe Substance 소재가 된다",
        "body": "HP Z Captis의 소재 캡처가 Adobe Substance 3D 파이프라인과 이어졌다.",
        "source": "DEVELOP3D",
        "url": "https://develop3d.com/3d-scanning/hp-z-captis-adobe-substance/",
        "accent": "#7928ca",
        "motif": "cube",
        "image": "pipeline/media/zcaptis.jpg",
        "hasFull": true
      }
    ]
  }
];
})();
