/* AUTO-GENERATED by pipeline/build_data.py — do not hand-edit.
   Source of truth: pipeline/news_data.json */
(function () {
  window.AX_SECTIONS = {
  "design": {
    "label": "Design",
    "news": [
      {
        "id": "figma-make",
        "eyebrow": "AI NEWS",
        "headline": "피그마 메이크에 속성 패널과\n주석 기능이 더해졌다",
        "body": "AI가 만든 화면을 속성 패널로 직접 손보고, 다시 프롬프트를 쓰지 않고도 의도를 코드로 넘긴다.",
        "tool": "Figma",
        "source": "Figma",
        "url": "https://www.figma.com/blog/properties-panel-and-annotations-now-in-figma-make/",
        "accent": "#0070f3",
        "motif": "frame",
        "full": {
          "mode": "summary",
          "blocks": [
            {
              "t": "img",
              "src": "https://cdn.sanity.io/images/599r6htc/regionalized/d1366af0a7f2c9945aa6a7a693f319518f22fc63-3840x2160.png"
            },
            {
              "t": "p",
              "x": "피그마 메이크에 시각적 속성 패널과 주석 기능이 들어왔다."
            },
            {
              "t": "p",
              "x": "디자이너는 AI가 만들어 낸 결과물을 곧바로 손볼 수 있고, 프롬프트를 다시 쓰지 않고도 그 의도를 코드 쪽으로 넘긴다."
            },
            {
              "t": "p",
              "x": "디자인에서 코드로 이어지는 고리를 한층 조인, 피그마 AI 빌더의 실제 기능 업데이트다."
            }
          ]
        },
        "image": "pipeline/media/figma-make.png",
        "free": true,
        "hasFull": true
      },
      {
        "id": "perplexity-color",
        "eyebrow": "AI NEWS",
        "headline": "생성형 AI로 발산형\n데이터 색상 체계를 만든다",
        "body": "퍼플렉시티로 발산형 데이터 시각화 팔레트를 짜며, 접근성까지 챙긴 색상 토큰을 만든다.",
        "tool": "Design Tokens",
        "source": "UX Collective",
        "url": "https://uxdesign.cc/perplexity-diverges-with-color-cad28cbe7bad",
        "accent": "#2ec5c5",
        "motif": "swatch",
        "image": "pipeline/media/perplexity-color.png",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "unwanted-ai-images",
        "eyebrow": "AI NEWS",
        "headline": "원치 않는 AI 이미지가\n사람들을 불안하게 한다",
        "body": "아마존과 틴더, 레딧이 사용자 사진을 기본값으로 AI 편집하고, 거부는 사용자 몫으로 남긴다.",
        "tool": "AI Workflow",
        "source": "Creative Bloq",
        "url": "https://www.creativebloq.com/ai/from-amazon-to-tinder-and-reddit-tech-platforms-are-giving-users-ai-images-they-didnt-ask-for",
        "accent": "#ff5a4d",
        "motif": "frame",
        "image": "pipeline/media/unwanted-ai-images.jpg",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "ai-fluency",
        "eyebrow": "AI NEWS",
        "headline": "AI 능숙함은\n결승선이 아니다",
        "body": "제품 제작자 90%가 AI 역량을 필수로 꼽지만, 피그마는 팀이 엉뚱한 능력에 매달린다고 짚는다.",
        "tool": "AI Workflow",
        "source": "Figma",
        "url": "https://www.figma.com/blog/ai-fluency-isnt-the-finish-line/",
        "accent": "#3b6bff",
        "motif": "frame",
        "image": "pipeline/media/ai-fluency.png",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "creative-technologists",
        "eyebrow": "AI NEWS",
        "headline": "크리에이티브 테크놀로지스트가\n중심으로 옮겨간다",
        "body": "AI가 디자인과 코드의 간극을 좁히며, 직접 만드는 디자이너가 변방에서 팀의 기본값으로 옮겨간다.",
        "tool": "AI Workflow",
        "source": "UX Collective",
        "url": "https://uxdesign.cc/creative-technologists-are-moving-from-the-margins-to-the-center-4fcfaa3cf2f6",
        "accent": "#eb367f",
        "motif": "frame",
        "image": "pipeline/media/creative-technologists.png",
        "hasFull": true,
        "locked": true
      }
    ],
    "days": [
      {
        "date": "2026-07-28",
        "cards": [
          {
            "id": "pincushion-ui-feedback",
            "eyebrow": "AI NEWS",
            "tool": "AI Workflow",
            "headline": "라이브 앱에 남긴 지적이 사람 손질 없이 PR이 된다",
            "body": "라이브 앱에 꽂은 핀이 선택자와 뷰포트까지 담아 코딩 에이전트가 MCP로 받아 PR로 만든다.",
            "source": "DEV Community",
            "url": "https://dev.to/matttdamon/from-feedback-to-merged-pr-making-ui-feedback-agent-actionable-12a8",
            "accent": "#ff5a4d",
            "motif": "frame",
            "image": "pipeline/media/pincushion-ui-feedback.png",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "ai-websites-samey",
            "eyebrow": "AI NEWS",
            "tool": "AI Workflow",
            "headline": "AI로 뽑아낸 웹사이트가 하나같이 똑같아 보이는 까닭",
            "body": "똑같은 히어로와 카드 그리드가 반복되는 건 모델이 디자인 대신 흔한 패턴을 되풀이해서다.",
            "source": "DEV Community",
            "url": "https://dev.to/lyd_lyd_d4869af25d33ce0eb/why-do-ai-generated-websites-all-look-the-same-k2j",
            "accent": "#3b6bff",
            "motif": "cube",
            "image": "pipeline/media/ai-websites-samey.png",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "netflix-genai-boycott",
            "eyebrow": "AI NEWS",
            "tool": "AI Workflow",
            "headline": "생성형 AI가 싫다면 넷플릭스를 떠날 이유는 충분하다",
            "body": "넷플릭스가 올해에만 약 300편에 생성형 AI를 끌어들였다고 주주 서한에서 밝혔다.",
            "source": "Creative Bloq",
            "url": "https://www.creativebloq.com/ai/hate-generative-ai-maybe-its-time-to-boycott-netflix",
            "accent": "#2ec5c5",
            "motif": "swatch",
            "image": "pipeline/media/netflix-genai-boycott.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-29",
        "cards": [
          {
            "id": "macpaw-eney",
            "eyebrow": "AI NEWS",
            "tool": "Design Tokens",
            "headline": "채팅창을 벗어난 AI 조수 MacPaw의 캐릭터 실험",
            "body": "MacPaw는 텍스트 창 대신 표정을 지닌 원형 캐릭터 Eney를 만들어 AI 조수를 다시 설계했다.",
            "source": "Smashing Magazine",
            "url": "https://www.smashingmagazine.com/2026/07/digital-design-ai-era/",
            "accent": "#2ec5c5",
            "motif": "swatch",
            "image": "pipeline/media/macpaw-eney.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "no-handoff",
            "eyebrow": "AI NEWS",
            "tool": "Figma",
            "headline": "디자이너가 AI를 지휘해 핸드오프 없이 직접 만든다",
            "body": "디자이너 Merav Shaked는 AI를 팀처럼 지휘해 하룻밤 만에 포트폴리오를 직접 다시 만들었다.",
            "source": "DEV Community",
            "url": "https://dev.to/meravish/i-design-products-then-i-make-them-there-is-no-handoff-2bof",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/no-handoff.png",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "octane-neural",
            "eyebrow": "AI NEWS",
            "tool": "KeyShot",
            "headline": "OctaneRender 2027.1 신경망 렌더링을 알파 공개",
            "body": "Otoy는 낮은 샘플에서도 노이즈가 거의 없는 신경망 렌더링을 OctaneRender 알파에 담았다.",
            "source": "CG Channel",
            "url": "https://www.cgchannel.com/2026/07/otoy-releases-octanerender-2027-1-in-alpha/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/octane-neural.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-30",
        "cards": [
          {
            "id": "agent-native-actions",
            "eyebrow": "AI NEWS",
            "tool": "Figma",
            "headline": "UI가 하는 일은 모두 에이전트도 할 수 있다",
            "body": "모든 기능을 액션 하나로 묶어, 화면에서 되는 일이면 에이전트도 똑같이 처리한다.",
            "source": "Builder.io",
            "url": "https://www.builder.io/blog/agent-first-apps",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/agent-native-actions.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "where-ai-belongs-games",
            "eyebrow": "AI NEWS",
            "tool": "KeyShot",
            "headline": "AI가 게임 개발에서 진짜 있어야 할 자리",
            "body": "디켄은 생성형 AI의 쓸모가 콘텐츠 자동화보다 저마다 다른 경험에 있다고 본다.",
            "source": "80 Level",
            "url": "https://80.lv/articles/game-ai-expert-explains-where-ai-actually-belongs-in-game-development-and-the-risks",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/where-ai-belongs-games.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "nexthena-121-i18n",
            "eyebrow": "AI NEWS",
            "tool": "Design Tokens",
            "headline": "AI 화이트보드 넥스테나 다국어와 테마를 다듬다",
            "body": "넥스테나 1.2.1이 영어·중국어 전환을 더해, 화이트보드가 OS 명암을 따른다.",
            "source": "DEV Community",
            "url": "https://dev.to/blackstar/nexthena-121-released-2alp",
            "accent": "#2ec5c5",
            "motif": "swatch",
            "image": "pipeline/media/nexthena-121-i18n.png",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-31",
        "cards": [
          {
            "id": "nanobanana-earth",
            "eyebrow": "AI NEWS",
            "tool": "KeyShot",
            "headline": "나노 바나나가 구글 어스에서 과거와 미래를 그려낸다",
            "body": "나노 바나나가 구글 어스에 들어가 지도 위에서 옛 유적과 지어질 건물을 실사처럼 그려낸다.",
            "source": "Engadget",
            "url": "https://www.engadget.com/2226451/nano-banana-image-generation-comes-to-google-earth/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/nanobanana-earth.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "shieldfont-poison-ai",
            "eyebrow": "AI NEWS",
            "tool": "Figma",
            "headline": "AI 학습을 오염시키는 무료 폰트 실드폰트",
            "body": "타이포 디자이너들이 긁어간 글과 이미지로 AI가 학습하지 못하게 오염시키는 무료 폰트를 공개했다.",
            "source": "Creative Bloq",
            "url": "https://www.creativebloq.com/design/fonts-typography/type-designers-have-created-a-free-font-that-poisons-ai",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/shieldfont-poison-ai.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "bull-bear-design-ai",
            "eyebrow": "AI NEWS",
            "tool": "Design Tokens",
            "headline": "AI가 디자이너에게 줄 자율과 드러날 빈틈",
            "body": "앤디 버드는 AI가 디자이너에게 더 큰 자율을 주는 동시에, 감춰 온 실력 격차를 드러낸다고 본다.",
            "source": "Smashing Magazine",
            "url": "https://smashingmagazine.com/2026/07/bull-and-bear-case-digital-design-age-ai/",
            "accent": "#2ec5c5",
            "motif": "swatch",
            "image": "pipeline/media/bull-bear-design-ai.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "get-out-of-their-way",
            "eyebrow": "AI NEWS",
            "tool": "Figma",
            "headline": "AI를 이미 아는 팀에게 자리를 내주어라",
            "body": "모두 같은 AI 도구를 쥔 지금, 승부는 그 도구를 이미 이해한 실무자를 믿고 맡기는 팀에서 갈린다.",
            "source": "UX Collective",
            "url": "https://uxdesign.cc/your-people-get-ai-get-out-of-their-way-131370c157f8",
            "accent": "#3b6bff",
            "motif": "frame",
            "image": "pipeline/media/get-out-of-their-way.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-08-01",
        "cards": [
          {
            "id": "google-earth-rollback",
            "eyebrow": "AI NEWS",
            "tool": "KeyShot",
            "headline": "구글, 지도에 붙인 생성 AI 도구를 되돌리다",
            "body": "구글이 지도의 신뢰를 해친다는 반발에 구글 어스의 생성형 이미지 도구를 며칠 만에 거둬들였다.",
            "source": "Engadget",
            "url": "https://www.engadget.com/2228142/google-rolls-back-the-needless-ai-generation-tools-it-added-to-google-earth/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/google-earth-rollback.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "rebelle-brush",
            "eyebrow": "AI NEWS",
            "tool": "KeyShot",
            "headline": "생성 AI 대신 붓의 감각을 택한 리벨",
            "body": "리벨 8.3은 생성 AI를 좇는 대신 물리적으로 사실적인 붓과 수채 시뮬레이션에 더 깊이 파고든다.",
            "source": "Creative Bloq",
            "url": "https://www.creativebloq.com/art/digital-art-software/rebelle-8-3-proves-the-future-of-digital-painting-isnt-ai-its-making-brushes-feel-real",
            "accent": "#7928ca",
            "motif": "sphere",
            "image": "pipeline/media/rebelle-brush.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "jakobs-law-chatbox",
            "eyebrow": "AI NEWS",
            "tool": "Figma",
            "headline": "화면이 채팅창 하나로 합쳐질 때의 야코프 법칙",
            "body": "AI가 여러 화면을 채팅창 하나로 합치는 지금, 사용자가 길을 잃지 않게 지킬 익숙함의 규칙을 다시 짚는다.",
            "source": "UX Collective",
            "url": "https://uxdesign.cc/jakobs-law-how-to-apply-it-as-ai-collapses-surfaces-into-one-chat-box-d8ebc9a727db",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/jakobs-law-chatbox.png",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "rethinking-friction",
            "eyebrow": "AI NEWS",
            "tool": "AI Workflow",
            "headline": "AI 시대에 다시 묻는 마찰의 쓸모",
            "body": "AI가 무엇이든 즉시 해내는 지금, 사용자에게 통제권을 남기려면 마찰을 의도적으로 되돌려야 한다고 짚는다.",
            "source": "UX Collective",
            "url": "https://uxdesign.cc/rethinking-friction-in-an-ai-world-8f361d62ab5e",
            "accent": "#ff5a4d",
            "motif": "frame",
            "image": "pipeline/media/rethinking-friction.png",
            "hasFull": true,
            "locked": true
          }
        ]
      }
    ],
    "lockedCount": 4
  },
  "music": {
    "label": "Music",
    "news": [
      {
        "id": "soundboost",
        "eyebrow": "AI NEWS",
        "headline": "사운드부스트, 원하는 소리를 말하면\nAI가 믹싱과 마스터링을 끝낸다",
        "body": "원하는 소리를 말로 설명하면 믹싱과 마스터링이 끝나고, 무료 스템 분리기까지 함께 제공된다.",
        "tool": "Music",
        "source": "Digital Music News",
        "url": "https://www.digitalmusicnews.com/2026/07/30/soundboost-natural-language-music-mastering-mixing/",
        "accent": "#ff2d55",
        "motif": "sphere",
        "full": {
          "mode": "summary",
          "blocks": [
            {
              "t": "p",
              "x": "사운드부스트가 자연어 텍스트 프롬프트로 돌아가는 AI 믹싱·마스터링을 선보였다. 원하는 소리를 말로 풀어 주면, 프로듀서가 그대로 마스터를 잡아낼 수 있다."
            },
            {
              "t": "img",
              "src": "https://www.digitalmusicnews.com/wp-content/uploads/2026/07/soundboost-scaled.jpg"
            },
            {
              "t": "p",
              "x": "여기에 무료 스템 분리기가 더해지고, 회사는 자사 모델을 '윤리적으로 학습시킨' 것으로 내세운다."
            },
            {
              "t": "p",
              "x": "이미 13만 명이 넘는 뮤지션이 쓰고 있다고 밝히며, 트랙을 마무리하는 방식을 바꿔 놓겠다는 그림이다."
            }
          ]
        },
        "image": "pipeline/media/soundboost.jpg",
        "free": true,
        "hasFull": true
      }
    ],
    "days": [
      {
        "date": "2026-07-27",
        "cards": [
          {
            "id": "devocean",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "곁에서 함께 패치하는 AI, 모듈러 신스 안으로 들어오다",
            "body": "145개 모듈을 갖춘 모듈러 신스에 함께 패치를 짜주는 AI 에이전트 MaYa가 들어갔다.",
            "source": "Synthtopia",
            "url": "https://www.synthtopia.com/content/2026/07/17/ocean-swift-intros-dev-ocean-modular-synthesis-sound-design-environment/",
            "accent": "#ff2d55",
            "motif": "sphere",
            "image": "pipeline/media/devocean.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "deezer-ai-flood",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "AI 음원, 처음으로 디저 신규 업로드의 절반을 넘겼다",
            "body": "2026년 6월 디저에는 하루 9만 곡꼴로 AI 음원이 올라와 신규 업로드의 절반을 처음 넘겼다.",
            "source": "Music Business Worldwide",
            "url": "https://www.musicbusinessworldwide.com/90000-ai-tracks-flood-deezer-daily-passing-half-of-new-music-uploads-for-the-first-time/",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/deezer.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "fender-studio-pro",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "무료 DAW 펜더 스튜디오에 AI 편집 도구가 들어왔다",
            "body": "펜더의 무료 DAW 스튜디오 프로 8.1이 Moises 기반 스템 분리·생성과 AI 보컬 보정을 품었다.",
            "source": "MusicTech",
            "url": "https://musictech.com/reviews/digital-audio-workstations/fender-studio-pro-8-1-review/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/fender.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "izotope-vea",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "노브 세 개로 끝내는 AI 보컬 보정, 지금은 공짜",
            "body": "iZotope가 RX·Nectar의 AI 처리를 노브 세 개로 줄인 보컬 플러그인 VEA를 7월 31일까지 무료로 푼다.",
            "source": "Bedroom Producers Blog",
            "url": "https://bedroomproducersblog.com/2026/07/26/izotope-japan-vea-free/",
            "accent": "#7928ca",
            "motif": "sphere",
            "image": "pipeline/media/izotope.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-29",
        "cards": [
          {
            "id": "elevenmusic-vocals-refs",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "일레븐랩스, AI 음악에 레퍼런스·보컬 기능 추가",
            "body": "일레븐랩스가 일레븐뮤직에 참조 음원으로 스타일을 잡는 레퍼런스와 목소리로 곡을 짓는 보컬 기능을 넣었다.",
            "source": "DigitalToday",
            "url": "https://www.digitaltoday.co.kr/en/view/84703/elevenlabs-upgrades-ai-music-generation-service-adds-vocals-references",
            "accent": "#ff2d55",
            "motif": "sphere",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-30",
        "cards": [
          {
            "id": "labels-ban-ai-slop-charts",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "AI 슬롭 곡을 세계 차트에서 빼자는 메이저 3사",
            "body": "소니와 유니버설, 워너가 완전 AI로 만든 곡을 차트 집계에서 빼자고 요구했다.",
            "source": "Engadget",
            "url": "https://www.engadget.com/2226234/major-labels-call-for-ai-slop-songs-to-be-banned-from-entering-charts-around-the-world/",
            "accent": "#ff2d55",
            "motif": "sphere",
            "image": "pipeline/media/labels-ban-ai-slop-charts.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "audioauditor-ai-detect-toolkit",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "AI 곡까지 잡아내는 무료 오픈소스 오디오 툴킷",
            "body": "오픈소스 앱 오디오오디터가 워터마크·바이트 패턴으로 AI 곡까지 가려낸다.",
            "source": "Bedroom Producers Blog",
            "url": "https://bedroomproducersblog.com/2026/07/28/audioauditor/",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/audioauditor-ai-detect-toolkit.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "canada-only-humans-authors-copyright",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "저작자는 사람뿐이라는 캐나다 음악 출판사들",
            "body": "캐나다 음악 출판사 단체가 저작권 소송에 개입해 저작자는 사람뿐이라 주장했다.",
            "source": "CMU",
            "url": "https://completemusicupdate.com/only-humans-can-be-authors-say-canadian-music-publishers-in-test-case-on-copyright-status-of-ai-generated-works/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/canada-only-humans-authors-copyright.png",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "human-first-label-needs-teeth",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "아무도 검증 못 하는 '휴먼 퍼스트'라는 약속",
            "body": "'휴먼 퍼스트' 라벨은 유통사가 작곡·연주·보컬을 항목별로 검증해야 의미가 있다.",
            "source": "Hypebot",
            "url": "https://www.hypebot.com/human-first-is-a-promise-nobody-can-check-yet/",
            "accent": "#7928ca",
            "motif": "sphere",
            "image": "pipeline/media/human-first-label-needs-teeth.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-31",
        "cards": [
          {
            "id": "flow-music-spaces",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "구글 플로우 뮤직이 노래 생성과 편집, 스템 분리를 한 화면에 담는다",
            "body": "라이리아 3 프로 기반으로 노래 생성과 편집, 보컬 분리, 트랙 확장까지 한 작업 공간에서 이뤄진다.",
            "source": "Music Business Worldwide",
            "url": "https://www.musicbusinessworldwide.com/googles-flow-music-adds-song-generation-editing-and-stem-splitting-to-spaces-its-vibe-coding-tool/",
            "accent": "#ff2d55",
            "motif": "sphere",
            "image": "pipeline/media/flow-music-spaces.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "vochlea-dubbox",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "보클리아 덥박스, 비트박스를 실시간 드럼 루프로 바꾼다",
            "body": "비트박스를 머신러닝으로 익혀, 벨로시티가 살아 있는 드럼 루프로 실시간 바꿔 준다.",
            "source": "MusicRadar",
            "url": "https://www.musicradar.com/music-tech/beatbox-your-ideas-into-reality-with-vochleas-dubbox-an-app-that-converts-your-voice-into-drum-loops",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/vochlea-dubbox.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "roland-neutone-lydia",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "뉴톤과 롤랜드의 프로젝트 리디아, AI 모델을 직접 만드는 페달",
            "body": "실시간 연주를 위한 AI 이펙트 페달로, 뉴럴 샘플링 모델을 직접 훈련하고 뜯어고쳐 자기만의 악기로 만든다.",
            "source": "MusicTech",
            "url": "https://musictech.com/features/interviews/roland-neutone-project-lydia/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/roland-neutone-lydia.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "stem-separation-2026",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "스템 분리 도구 아홉 종, 트랙마다 최선은 달랐다",
            "body": "아홉 개 AI 스템 분리 도구를 시험한 결과, 로직 프로는 빠른 일상 작업에, MVSEP은 까다로운 보컬에 앞섰다.",
            "source": "MusicTech",
            "url": "https://musictech.com/guides/buyers-guide/best-stem-separation-tools/",
            "accent": "#7928ca",
            "motif": "sphere",
            "image": "pipeline/media/stem-separation-2026.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-08-01",
        "cards": [
          {
            "id": "lyria-35",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "구글 라이리아 3.5, 더 자연스럽고 감정이 살아 있는 보컬로 올라선다",
            "body": "음악성과 가사, 보컬 품질을 손봐 발음이 또렷해지고 멜로디 구조가 한결 자연스러워졌다.",
            "source": "Music Business Worldwide",
            "url": "https://www.musicbusinessworldwide.com/watch-out-suno-google-has-upgraded-lyria/",
            "accent": "#ff2d55",
            "motif": "sphere",
            "image": "pipeline/media/lyria-35.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "karst",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "팀 엑자일의 카스트, 시스템으로 음악을 짜는 소프트웨어 모듈러",
            "body": "노드 에디터와 케이블 없는 패칭으로, 생성 알고리즘을 직접 손으로 짜 음악을 만든다.",
            "source": "Synthtopia",
            "url": "https://www.synthtopia.com/content/2026/07/30/tim-exile-previews-karst-software-modular-system/",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/karst.png",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "silt",
            "eyebrow": "AI NEWS",
            "tool": "Music",
            "headline": "튜너리 실트, 테이프 루프로 스스로 자라나는 앰비언트 악기",
            "body": "길이가 다른 네 개의 짧은 루프가 테이프 위에서 천천히 어긋나며 앰비언트를 자아낸다.",
            "source": "Synthtopia",
            "url": "https://www.synthtopia.com/content/2026/07/24/tunary-intros-silt-generative-tape-loop-instrument/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/silt.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      }
    ],
    "lockedCount": 0
  },
  "movies": {
    "label": "Movies",
    "news": [
      {
        "id": "luma-layers",
        "eyebrow": "AI NEWS",
        "headline": "프롬프트 대신\n요소 단위로 고친다",
        "body": "Luma의 Layers는 프롬프트를 통째로 다시 돌리는 대신 AI 이미지를 요소 하나하나 정밀하게 고치게 한다.",
        "tool": "Movies",
        "source": "Luma AI",
        "url": "https://lumalabs.ai/news/introducing-layers",
        "accent": "#0070f3",
        "motif": "frame",
        "full": {
          "mode": "full",
          "blocks": [
            {
              "t": "img",
              "src": "https://cdn.sanity.io/images/2ylxvaa2/production/80d1b0c6b46f2a066a23085c49320a532f9959e7-1920x1080.png?rect=0,36,1920,1008&w=1200&h=630&fm=jpg"
            },
            {
              "t": "p",
              "x": "Luma AI가 자사 영화 제작 도구 안에 Layers를 새로 얹었다. AI로 만든 이미지를 요소 단위로 만지며 정밀하게 편집할 수 있게 하는 기능이다."
            },
            {
              "t": "p",
              "x": "그동안은 결과가 마음에 들지 않으면 프롬프트를 통째로 다시 돌려야 했다. Layers는 그 방식을 벗어나, 화면 속 개별 요소를 골라 하나씩 손볼 수 있게 한다."
            },
            {
              "t": "p",
              "x": "생성형 작업을 프롬프트 운에 맡기는 단계에서 끌어내려, 감독하고 다시 고치는 통제된 작업으로 옮기는 셈이다. 필름메이커와 프리비주얼 아티스트가 기대하던 결의 제어다."
            }
          ]
        },
        "video": "pipeline/media/luma-layers.mp4",
        "poster": "pipeline/media/luma-layers.jpg",
        "image": "pipeline/media/luma-layers.jpg",
        "free": true,
        "hasFull": true
      },
      {
        "id": "frame-io-search",
        "eyebrow": "AI NEWS",
        "headline": "전체 화면 검색과\n비교 뷰어 개선",
        "body": "Adobe Frame.io가 전체 화면 검색과 AI 검색 토글, 비교 뷰어 개선으로 촬영본을 더 빠르게 찾고 검토하게 한다.",
        "tool": "Movies",
        "source": "RedShark News",
        "url": "https://www.redsharknews.com/frame-io-full-screen-search-comparison-viewer-update",
        "accent": "#f5a623",
        "motif": "frame",
        "image": "pipeline/media/frame-io-search.jpg",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "wonder-dynamics",
        "eyebrow": "AI NEWS",
        "headline": "연기를 CG로 옮기되\n손은 아티스트가",
        "body": "Wonder Dynamics의 Flow Studio는 실사 연기를 CG 캐릭터로 옮기면서도 아티스트가 통제권을 쥐게 한다.",
        "tool": "Movies",
        "source": "No Film School",
        "url": "https://nofilmschool.com/filmmakers-at-wonder-dynamics-building-ai-for-filmmakers",
        "accent": "#7928ca",
        "motif": "frame",
        "image": "pipeline/media/wonder-dynamics.webp",
        "hasFull": true,
        "locked": true
      }
    ],
    "days": [
      {
        "date": "2026-07-28",
        "cards": [
          {
            "id": "martini",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "마티니, 프롬프트 대신 카메라로 숏을 짜는 AI 촬영장",
            "body": "마티니는 피그마처럼 웹에서 여럿이 함께 카메라를 움직여 AI 영상의 숏을 짜는 가상 촬영장이다.",
            "source": "No Film School",
            "url": "https://nofilmschool.com/martini-ai-film-set",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/martini.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "aitoolvetting",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "검증 안 된 AI 도구는 결국 쌓이는 리스크다",
            "body": "제프 그린버그는 포스트 현장에 쏟아지는 소규모 AI 도구를 믿기 전 다섯 가지를 따져 리스크를 재라고 짚는다.",
            "source": "ProVideo Coalition",
            "url": "https://www.provideocoalition.com/the-rise-of-the-independent-ai-assisted-developer-tools-warnings-and-considerations/",
            "accent": "#f5a623",
            "motif": "frame",
            "image": "pipeline/media/aitoolvetting.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-29",
        "cards": [
          {
            "id": "reluctant-ai",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "15년 전통 영화 제작자 이제 마지못해 AI로 간다",
            "body": "무너지는 중예산 영화를 살리려, 15년 경력의 제작자가 마지못해 생성형 AI 제작 도구로 돌아섰다.",
            "source": "The Hollywood Reporter",
            "url": "https://www.hollywoodreporter.com/business/business-news/ai-moviemaking-production-1236647473/",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/reluctant-ai.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "gods-gifts",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "유튜브에서 태어난 AI 장편 극장 개봉을 눈앞에 두다",
            "body": "가십 고블린 채널이 통째로 AI로 만든 장편이 유튜브 구독층을 발판 삼아 극장 개봉으로 넘어갈 채비를 한다.",
            "source": "Deadline",
            "url": "https://deadline.com/2026/07/gossip-goblin-ai-feature-gods-dont-give-gifts-youtube-theaters-1236998952/",
            "accent": "#f5a623",
            "motif": "frame",
            "image": "pipeline/media/gods-gifts.png",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "reply-jury",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "리플 AI 영화제 심사위원에 롭 민코프·캐서린 하드윅",
            "body": "AI 단편을 겨루는 리플 AI 영화제가 롭 민코프와 캐서린 하드윅을 심사위원으로 세웠다.",
            "source": "Variety",
            "url": "https://variety.com/2026/film/festivals/reply-ai-film-festival-jury-rob-minkoff-catherine-hardwicke-1236822490/",
            "accent": "#7928ca",
            "motif": "frame",
            "image": "pipeline/media/reply-jury.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-30",
        "cards": [
          {
            "id": "saga-ai-video-source-attribution",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "AI 영상을 만든 모델까지 역추적하는 도구 SAGA",
            "body": "UC 리버사이드 연구팀이 생성 영상에 남은 시각적 지문을 읽어 원본 모델을 추적한다.",
            "source": "No Film School",
            "url": "https://nofilmschool.com/ai-tracing-tool",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/saga-ai-video-source-attribution.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "nvidia-synthetic-video-detector-mcp-siggraph",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "NVIDIA가 딥페이크 탐지와 AI 에이전트를 함께 열다",
            "body": "엔비디아가 시그래프 2026에서 합성 영상 탐지 NIM과 MCP를 공개했다.",
            "source": "RedShark News",
            "url": "https://www.redsharknews.com/nvidia-synthetic-video-detector-mcp-siggraph-2026",
            "accent": "#f5a623",
            "motif": "frame",
            "image": "pipeline/media/nvidia-synthetic-video-detector-mcp-siggraph.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-31",
        "cards": [
          {
            "id": "autodesk-maya-3dgs-ai",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "Autodesk가 마야·3ds Max에 AI와 3DGS 도구를 더하다",
            "body": "시그래프 2026에서 마야의 모션메이커가 스튜디오 자체 리그와 목캡으로 생성형 모션 모델을 학습한다.",
            "source": "postPerspective",
            "url": "https://postperspective.com/autodesk-updates-bring-your-own-data-editable-3d-gaussian-splats-more/",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/autodesk-maya-3dgs-ai.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "beeble-switchlight-hybrid-set",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "AI가 배경과 조명을 바꾸는 하이브리드 촬영 현장",
            "body": "비블의 스위치라이트로 배경과 조명은 AI가 바꾸고 배우의 연기와 카메라 워크는 그대로 남긴다.",
            "source": "ProVideo Coalition",
            "url": "https://www.provideocoalition.com/is-this-the-future-of-filmmaking/",
            "accent": "#f5a623",
            "motif": "frame",
            "image": "pipeline/media/beeble-switchlight-hybrid-set.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "puget-robo-dojo-siggraph",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "관객을 메타휴먼으로 바꾸는 퓨젯의 로보 도조",
            "body": "라이다 스캔과 LED 볼륨으로 관객을 실시간 메타휴먼 아바타로 바꿔 AI 로봇과 맞붙게 한다.",
            "source": "RedShark News",
            "url": "https://www.redsharknews.com/puget-systems-robo-dojo-siggraph-2026",
            "accent": "#7928ca",
            "motif": "frame",
            "image": "pipeline/media/puget-robo-dojo-siggraph.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-08-01",
        "cards": [
          {
            "id": "vida-scene-search",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "장면 단위로 찾는 오프라인 AI 검색",
            "body": "수작업 메타데이터 없이 자연어만으로 영상 라이브러리를 장면 단위로 뒤져 편집자가 필요한 장면을 곧바로 찾는다.",
            "source": "postPerspective",
            "url": "https://postperspective.com/vida-scene-search-ai-scene-level-search-with-no-manual-logging-required/",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/vida-scene-search.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "hp-z-captis-adobe",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "AI로 빨라진 디지털 트윈 캡처",
            "body": "HP Z Captis가 Substance 3D와 더 깊게 붙고 Jetson에서 AI 추론을 돌려 제작용 디지털 트윈을 빠르게 만든다.",
            "source": "postPerspective",
            "url": "https://postperspective.com/hp-and-adobe-offer-digital-twin-capture-built-for-scale/",
            "accent": "#f5a623",
            "motif": "frame",
            "image": "pipeline/media/hp-z-captis-adobe.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "frostfx",
            "eyebrow": "AI NEWS",
            "tool": "Movies",
            "headline": "AI는 대체가 아니라 또 하나의 도구",
            "body": "에스토니아 FrostFX는 AI로 반복적 기술 작업을 걷어내 아티스트가 창작 판단에 더 오래 머물게 한다고 말한다.",
            "source": "RedShark News",
            "url": "https://www.redsharknews.com/vfx-frostfx-estonia",
            "accent": "#7928ca",
            "motif": "frame",
            "image": "pipeline/media/frostfx.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      }
    ],
    "lockedCount": 2
  },
  "games": {
    "label": "Games",
    "news": [
      {
        "id": "steamdisclosure",
        "eyebrow": "AI NEWS",
        "headline": "게임에 쓴 생성형 AI는\n숨기지 말고 밝혀라",
        "body": "개발자들은 게임에 쓴 생성형 AI를 스토어 페이지에 표기하도록 한 밸브의 방침을 지지한다고 밝혔다.",
        "tool": "Games",
        "source": "GamesRadar+",
        "url": "https://www.gamesradar.com/games/steams-required-ai-disclosure-is-the-right-move-devs-say-gen-ai-should-be-called-out-in-games-and-support-valves-store-mandate/",
        "accent": "#7928ca",
        "motif": "cube",
        "full": {
          "mode": "summary",
          "blocks": [
            {
              "t": "img",
              "src": "https://cdn.mos.cms.futurecdn.net/VALmj9Zgh9vEKQFCVSAQjW-1920-80.jpg"
            },
            {
              "t": "p",
              "x": "생성형 AI가 들어간 게임은 스팀 스토어 페이지에 그 사실을 밝혀야 한다. 밸브가 내건 이 표기 의무를 두고, 정작 게임을 만드는 사람들이 옳은 방향이라며 손을 들어줬다."
            },
            {
              "t": "p",
              "x": "개발자들은 게임에 실제로 담긴 생성형 AI라면 플레이어에게 알려야 한다고 말한다. 무엇으로 만든 게임인지, 살 사람에게는 알 권리가 있다는 것이다."
            },
            {
              "t": "p",
              "x": "나아가 스팀만이 아니라 모든 스토어가 같은 규칙을 두었으면 한다는 바람도 이어졌다. 한 곳의 방침에 그치지 않고 업계의 기본선으로 자리 잡기를 바라는 셈이다."
            }
          ]
        },
        "image": "pipeline/media/steamdisclosure.jpg",
        "free": true,
        "hasFull": true
      }
    ],
    "days": [
      {
        "date": "2026-07-28",
        "cards": [
          {
            "id": "blendcap-mocap",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "영상 하나로 전신·손·표정을 캡처하는 블렌더 애드온",
            "body": "블렌드캡은 녹화한 영상 하나에서 전신과 손, 표정 동작을 따내 게임 캐릭터 릭에 바로 옮긴다.",
            "source": "80 Level",
            "url": "https://80.lv/articles/full-body-hand-facial-motion-capture-from-any-video-in-blender/",
            "accent": "#7928ca",
            "motif": "cube",
            "image": "pipeline/media/blendcap-mocap.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "duskbloods-ai-lore",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "출시도 안 한 게임의 가짜 보스를 구글 AI가 사실처럼 퍼뜨린다",
            "body": "레딧 팬들이 지어낸 더스크블러드의 가짜 보스와 설정을 구글 AI 개요가 사실인 양 검색 결과에 띄운다.",
            "source": "Eurogamer",
            "url": "https://www.eurogamer.net/the-duskbloods-google-ai-hallucinations",
            "accent": "#eb367f",
            "motif": "sphere",
            "image": "pipeline/media/duskbloods-ai-lore.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "vibe-coding-clone-threat",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "AI 바이브 코딩이 좋은 게임을 베끼고 묻어버린다는 경고",
            "body": "업계 분석가는 AI 바이브 코딩이 스팀 같은 상점에서 잘 만든 게임을 복제해 묻어버릴 수 있다고 경고한다.",
            "source": "GamesRadar+",
            "url": "https://www.gamesradar.com/games/good-games-will-get-cloned-and-buried-ai-vibe-coding-is-one-of-the-biggest-threats-on-storefronts-like-steam-analyst-warns/",
            "accent": "#f5a623",
            "motif": "frame",
            "image": "pipeline/media/vibe-coding-clone-threat.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-29",
        "cards": [
          {
            "id": "ocarina-ipad",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "AI 디컴파일로 되살린 오카리나 iPad에서 네이티브로 실행된다",
            "body": "AI 디컴파일 기법으로 만든 이식판이 아이패드에서 N64의 프레임 제약 없이 네이티브로 돌아간다.",
            "source": "Wccftech",
            "url": "https://wccftech.com/ipados-gets-native-zelda-ocarina-of-time-port-via-ai/",
            "accent": "#7928ca",
            "motif": "cube",
            "image": "pipeline/media/ocarina-ipad.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-30",
        "cards": [
          {
            "id": "unity7-mcp-server",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "Unity 7, AI 에이전트에 엔진을 여는 로드맵",
            "body": "MCP 서버로 코딩 에이전트가 엔진을 다루고, Unity 6 빌드도 안 깨진다.",
            "source": "Game Developer",
            "url": "https://www.gamedeveloper.com/programming/unity-unveils-unity-7-roadmap-with-update-path-that-won-t-break-your-build",
            "accent": "#7928ca",
            "motif": "cube",
            "image": "pipeline/media/unity7-mcp-server.png",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "dlss5-direct-final-frame",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "DLSS 5, 아티스트가 최종 프레임을 지휘한다",
            "body": "신경 렌더링이 단일 GPU에서 한 단계 확산만으로 4K 화면을 만들어낸다.",
            "source": "Wccftech",
            "url": "https://wccftech.com/nvidia-dlss-5-hands-over-full-control-to-artists-to-direct-the-final-frame/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/dlss5-direct-final-frame.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "indie-devs-avoid-genai",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "인디 개발자 25인이 생성형 AI를 피하는 이유",
            "body": "인디 스튜디오들이 생성형 AI가 게임의 질을 떨어뜨린다며 작업에서 밀어낸다.",
            "source": "GamesRadar+",
            "url": "https://www.gamesradar.com/games/it-creates-lesser-games-indie-game-studios-are-supposed-to-love-generative-ai-so-why-do-the-25-devs-i-spoke-to-avoid-it/",
            "accent": "#0070f3",
            "motif": "frame",
            "image": "pipeline/media/indie-devs-avoid-genai.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "studios-refusing-genai",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "생성형 AI를 거부하는 게임 스튜디오 명단",
            "body": "50곳 넘는 스튜디오가 생성형 AI를 개발에서 빼겠다고 공개 선언했다.",
            "source": "Aftermath",
            "url": "https://aftermath.site/video-games-no-ai/",
            "accent": "#2ec5c5",
            "motif": "cube",
            "image": "pipeline/media/studios-refusing-genai.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-31",
        "cards": [
          {
            "id": "2d-to-3d",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "평면 콘셉트 아트를 게임용 3D 애셋으로 바꾸는 AI",
            "body": "평면 콘셉트 아트를 게임에 바로 쓸 수 있는 3D 지오메트리로 바꾸는 새로운 AI 기법이 등장했다.",
            "source": "PC Gamer",
            "url": "https://www.pcgamer.com/software/ai/new-method-teaches-ai-to-make-2d-designs-3d-and-now-im-afraid-this-will-be-how-the-robots-learn-to-build-themselves-without-us/",
            "accent": "#7928ca",
            "motif": "cube",
            "image": "pipeline/media/2d-to-3d.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "games-ai-culture-war",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "AI는 분명 쓸모 있지만 논쟁이 실제 기술을 가렸다",
            "body": "게임 AI 베테랑 디켄은 진짜 기회가 인재 대체가 아니라 더 풍부한 플레이 경험에 있다고 본다.",
            "source": "GamesRadar+",
            "url": "https://www.gamesradar.com/games/a-couple-of-companies-have-managed-to-ignite-a-culture-war-and-bring-the-economy-to-the-brink-of-collapse-games-ai-veteran-says-it-can-be-useful-but-weve-made-mountains-out-of-chatgpts-molehills/",
            "accent": "#0070f3",
            "motif": "cube",
            "image": "pipeline/media/games-ai-culture-war.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-08-01",
        "cards": [
          {
            "id": "therelic",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "프리뷰 빌드 AI 의혹에 디렉터가 선을 긋다",
            "body": "디렉터는 초기 콘셉트 단계의 로딩 화면과 소비 아이템 아이콘 일부에만 AI를 썼고 최종 게임엔 쓰지 않았다고 밝혔다.",
            "source": "Kotaku",
            "url": "https://kotaku.com/director-of-new-soulslike-says-no-ai-used-in-the-final-game-after-big-youtubers-sounded-the-alarm-over-a-recent-preview-build-2000720260",
            "accent": "#7928ca",
            "motif": "cube",
            "image": "pipeline/media/therelic.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "nexusmods",
            "eyebrow": "AI NEWS",
            "tool": "Games",
            "headline": "넥서스 모드, AI 자산 공개를 의무화하다",
            "body": "최대 PC 모딩 플랫폼 넥서스 모드가 AI로 만든 자산을 업로드할 때 반드시 표기하도록 정책을 조인다.",
            "source": "PC Gamer",
            "url": "https://www.pcgamer.com/gaming-industry/nexus-mods-finally-tightens-the-screws-on-ai-though-its-still-playing-softball-with-the-tide-of-slop/",
            "accent": "#eb367f",
            "motif": "cube",
            "image": "pipeline/media/nexusmods.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      }
    ],
    "lockedCount": 0
  },
  "books": {
    "label": "Books",
    "news": [
      {
        "id": "ai-scholarship-ownership",
        "eyebrow": "AI NEWS",
        "headline": "빅테크가 AI 참여 계층을\n장악하기 전에 표준을 세워라",
        "body": "학술 출판사들이 빅테크에 AI 참여 계층을 빼앗기기 전에 표준 인프라를 함께 세워야 한다는 제언이다.",
        "tool": "Books",
        "source": "The Scholarly Kitchen",
        "url": "https://scholarlykitchen.sspnet.org/2026/07/30/guest-post-the-third-time-is-not-the-charm-who-will-own-how-ai-participates-in-scholarship/",
        "accent": "#f5a623",
        "motif": "swatch",
        "full": {
          "mode": "summary",
          "blocks": [
            {
              "t": "img",
              "src": "https://scholarlykitchen.sspnet.org/wp-content/uploads/2026/04/iStock-2192544306-1024x576.jpg"
            },
            {
              "t": "p",
              "x": "학술 연구에 AI가 어떻게 끼어들지, 그 규칙을 누가 쥐게 될까. 저자들은 이 물음을 미루지 말고 지금 던져야 한다고 말한다."
            },
            {
              "t": "p",
              "x": "디지털 집적과 검색·발견의 계층을 결국 기술 기업이 손에 넣었던 전례가 있다. 같은 일이 AI 계층에서 되풀이되기 전에, 학술 출판사들이 먼저 인프라 표준을 함께 세워야 한다는 것이다."
            },
            {
              "t": "p",
              "x": "AI 시대가 학술·전문 출판의 작업 흐름을 누가 통제하느냐 하는 문제를 다시 짜고 있다. 그 판을 구체적으로 들여다본 진단이다."
            }
          ]
        },
        "image": "pipeline/media/ai-scholarship-ownership.jpg",
        "free": true,
        "hasFull": true
      },
      {
        "id": "nyt-ai-nonfiction",
        "eyebrow": "AI NEWS",
        "headline": "AI 논픽션은 어디서 오는가\n450권 펴낸 은퇴자를 좇다",
        "body": "한 은퇴자가 AI로 450권 넘게 자가출판해 소소한 인쇄 수익까지 올린 과정을 NYT가 추적했다.",
        "tool": "Books",
        "source": "Jane Friedman",
        "url": "https://janefriedman.com/new-york-times-journalist-investigates-origins-of-ai-generated-nonfiction/",
        "accent": "#0070f3",
        "motif": "swatch",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "pope-ai-encyclical",
        "eyebrow": "AI NEWS",
        "headline": "AI를 도덕의 문제로 되돌린\n교황의 회칙이 던진 물음",
        "body": "레오 14세의 AI 회칙은 기술을 도덕적 중립으로 보지 말고 인간 중심 감독을 요구하라 말한다.",
        "tool": "Books",
        "source": "Publishing Perspectives",
        "url": "https://publishingperspectives.com/2026/07/clarity-of-thought-and-responsibility-can-the-pope-move-the-needle-on-ai-regulation/",
        "accent": "#7928ca",
        "motif": "swatch",
        "image": "pipeline/media/pope-ai-encyclical.png",
        "hasFull": true,
        "locked": true
      }
    ],
    "days": [
      {
        "date": "2026-07-28",
        "cards": [
          {
            "id": "udgooglebooks",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "델라웨어대, 구글 북스에 장서 제공해 AI 학습용 학술 자료를 큐레이션",
            "body": "델라웨어대가 장서 10만여 권을 구글 북스에 디지털화해 AI가 신뢰할 학술 자료로 학습하도록 돕는다.",
            "source": "Publishing Perspectives",
            "url": "https://publishingperspectives.com/2026/07/around-the-book-world-monday-july-20th-2026/",
            "accent": "#f5a623",
            "motif": "swatch",
            "image": "pipeline/media/udgooglebooks.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "hkbookfair",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "홍콩 도서전이 'AI 시대에 모두의 읽기'를 올해 주제로 삼고 공진화를 논하다",
            "body": "36회 홍콩 도서전이 'AI 시대의 읽기'를 주제로 삼아 AI가 읽기 효율과 깊은 사고를 어떻게 키울지 논했다.",
            "source": "Publishing Perspectives",
            "url": "https://publishingperspectives.com/2026/07/around-the-book-world-july-27-2026/",
            "accent": "#7928ca",
            "motif": "frame",
            "image": "pipeline/media/hkbookfair.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-29",
        "cards": [
          {
            "id": "audiobook-ai-multicast",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "AI 멀티캐스트 내레이션 블라인드 실험서 사람 앞섰다",
            "body": "에디슨 리서치 블라인드 실험에서 청취자들이 AI 멀티캐스트를 단독 사람 낭독보다 조금 높게 평가했다.",
            "source": "Jane Friedman",
            "url": "https://janefriedman.com/new-study-audiobook-listeners-willing-to-try-ai-multi-cast-narration-rate-it-favorably/",
            "accent": "#f5a623",
            "motif": "swatch",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-30",
        "cards": [
          {
            "id": "daggermouth-60-percent-ai-study",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "AI가 쓴 소설이 베스트셀러에 올랐다",
            "body": "스토니브룩대 연구진이 화제작 다거마우스를 60% AI로 쓰인 소설로 판정했다.",
            "source": "Book Riot",
            "url": "https://bookriot.com/study-claims-viral-bestseller-daggermouth-is-ai-generated/",
            "accent": "#f5a623",
            "motif": "swatch",
            "image": "pipeline/media/daggermouth-60-percent-ai-study.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "publishing-perspectives-ai-course-2027",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "AI 시대를 준비하는 출판인 4주 워크숍",
            "body": "퍼블리싱 퍼스펙티브스가 2027년 1월 출판 실무진 대상 4주 AI 과정을 연다.",
            "source": "Publishing Perspectives",
            "url": "https://publishingperspectives.com/2026/07/announcing-a-course-to-help-publishers-navigate-the-ai-age-responsibly/",
            "accent": "#0070f3",
            "motif": "swatch",
            "image": "pipeline/media/publishing-perspectives-ai-course-2027.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-31",
        "cards": [
          {
            "id": "translators-craft-vs-ai",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "세계를 건너 우리를 실어 나르는 번역가들을 기리며",
            "body": "생성형 AI 번역이 확산되는 흐름 속에서, 문학 번역을 숙련된 인간의 기예로 다시 세우자는 주장이 나온다.",
            "source": "Publishing Perspectives",
            "url": "https://publishingperspectives.com/2026/07/in-praise-of-the-translators-who-transport-us-across-the-globe/",
            "accent": "#f5a623",
            "motif": "swatch",
            "image": "pipeline/media/translators-craft-vs-ai.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "editor-publisher-ai-survey",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "편집자와 발행인의 실제 AI 사용을 연구진이 들여다본다",
            "body": "멜버른대와 RMIT 연구진이 독립 출판 현장의 편집자와 발행인이 생성형 AI를 실제로 어떻게 쓰는지 조사한다.",
            "source": "Books+Publishing",
            "url": "https://www.booksandpublishing.com.au/articles/2026/07/21/334844/researchers-to-investigate-local-editor-and-publisher-ai-use/",
            "accent": "#0070f3",
            "motif": "swatch",
            "image": "pipeline/media/editor-publisher-ai-survey.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "poetry-foundation-scrape",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "시 재단 서고를 긁어 AI 교육 콘텐츠를 찍어내다",
            "body": "CZ 자오가 세운 기글 아카데미가 시 재단의 저작권 시를 긁어 AI 교육 콘텐츠를 자동으로 찍어냈다.",
            "source": "Publishers Weekly",
            "url": "https://www.publishersweekly.com/pw/by-topic/industry-news/publisher-news/article/100955-poetry-foundation-library-scraped-used-to-make-ai-generated-educational-content.html",
            "accent": "#7928ca",
            "motif": "swatch",
            "image": "pipeline/media/poetry-foundation-scrape.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-08-01",
        "cards": [
          {
            "id": "ai-publishing-easier",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "AI가 출판을 덜어냈지만 여전히 쉬운 일은 아니다",
            "body": "한 창업자는 제작팀 대신 AI로 322권을 펴냈고, 기계가 읽기 좋은 구조가 편집 방식을 바꾸고 있다.",
            "source": "Publishers Weekly",
            "url": "https://www.publishersweekly.com/pw/by-topic/international/international-book-news/article/100926-ai-may-be-making-publishing-easier-but-it-s-still-not-easy.html",
            "accent": "#f5a623",
            "motif": "swatch",
            "image": "pipeline/media/ai-publishing-easier.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "substack-ai-detection",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "서브스택, AI 탐지 기능 도입 다만 끄는 것도 가능하다",
            "body": "독자는 팬그램으로 글의 AI 작성 비율을 확인하고, 창작자는 그 배지를 직접 꺼둘 수 있다.",
            "source": "Jane Friedman",
            "url": "https://janefriedman.com/substack-adds-ai-detection-tools-but-creators-can-disable-them/",
            "accent": "#0070f3",
            "motif": "swatch",
            "image": "pipeline/media/substack-ai-detection.png",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "genius-novel-pulled",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "억대 계약 맺은 화제작이 AI 의혹으로 회수되다",
            "body": "미국과 영국에서 6~7자릿수 계약을 따낸 범죄 소설이 AI 사용 의혹 끝에 판매에서 내려졌다.",
            "source": "The Bookseller",
            "url": "https://www.thebookseller.com/news/genius-novel-sold-in-major-six-and-seven-figure-deals-at-auction-pulled-over-ai-allegations",
            "accent": "#7928ca",
            "motif": "swatch",
            "image": "pipeline/media/genius-novel-pulled.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "ai-dilutes-book-market",
            "eyebrow": "AI NEWS",
            "tool": "Books",
            "headline": "생성형 AI가 책 시장을 묽게 만든다는 증명 시도",
            "body": "작가들이 오래 우려해온 시장 잠식을 새 연구가 처음으로 실측 수치로 입증하려 나섰다.",
            "source": "Jane Friedman",
            "url": "https://janefriedman.com/researchers-attempt-to-prove-that-generative-ai-dilutes-the-market-for-books/",
            "accent": "#2ec5c5",
            "motif": "swatch",
            "hasFull": true,
            "locked": true
          }
        ]
      }
    ],
    "lockedCount": 2
  },
  "gadgets": {
    "label": "Gadgets",
    "news": [
      {
        "id": "samsung-galaxy-glasses-gemini",
        "eyebrow": "AI NEWS",
        "headline": "메타 레이밴에 맞설 삼성 글래스가\n구글과 함께 온다",
        "body": "삼성이 구글, 젠틀몬스터와 함께 만든 제미나이 스마트 글래스로 실시간 번역과 길 안내를 예고했다.",
        "tool": "Gadgets",
        "source": "Android Authority",
        "url": "https://www.androidauthority.com/samsung-galaxy-gemini-smart-glasses-3689544/",
        "accent": "#ff5a4d",
        "motif": "headset",
        "full": {
          "mode": "full",
          "blocks": [
            {
              "t": "img",
              "src": "https://www.androidauthority.com/wp-content/uploads/2026/07/Samsung-Intelligent-Eyewear-4.jpg"
            },
            {
              "t": "p",
              "x": "삼성이 언팩에서 제미나이를 얹은 스마트 글래스 두 종을 미리 보였다. 구글, 그리고 안경 브랜드 워비파커와 젠틀몬스터가 함께 만든 제품이다."
            },
            {
              "t": "p",
              "x": "화면 없는 안경테에 카메라가 달렸다. 제미나이가 이 눈으로 주변을 보고 읽어, 실시간 번역과 길 안내, 알림 요약을 곧바로 건넨다."
            },
            {
              "t": "p",
              "x": "무거운 연산은 짝을 이룬 갤럭시 폰이 떠맡는다. 안경은 폰 곁에서 늘 켜져 있는 AI 창구가 되는 셈인데, 창작자와 일상 사용자 모두를 겨냥한 방향이 분명하다."
            }
          ]
        },
        "image": "pipeline/media/samsung-galaxy-glasses-gemini.jpg",
        "free": true,
        "hasFull": true
      }
    ],
    "days": [
      {
        "date": "2026-07-28",
        "cards": [
          {
            "id": "amd-x100-robots",
            "eyebrow": "AI NEWS",
            "tool": "AMD",
            "headline": "AMD, 로봇에 넣을 임베디드 라이젠 AI 칩을 내놓는다",
            "body": "AMD가 라이젠 AI 실리콘을 담은 X100 칩을 휴머노이드와 엣지 로봇의 두뇌로 내놨다.",
            "source": "Tom's Hardware",
            "url": "https://www.tomshardware.com/pc-components/cpus/amds-new-x100-chip-lineup-puts-strix-halo-into-robots-apus-for-physical-ai-bring-zen-5-cpu-rdna-3-5-gpu-cores-to-compete-with-intels-panther-lake",
            "accent": "#0070f3",
            "motif": "headset",
            "image": "pipeline/media/amd-x100-robots.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "byd-xiaodi-robot",
            "eyebrow": "AI NEWS",
            "tool": "BYD",
            "headline": "BYD, 테슬라 옵티머스에 맞설 휴머노이드 샤오디를 예고한다",
            "body": "BYD가 테슬라 옵티머스에 맞설 이족보행 휴머노이드 로봇 샤오디를 8월 공개로 예고했다.",
            "source": "Notebookcheck",
            "url": "https://www.notebookcheck.net/New-Tesla-Optimus-rival-Leak-reveals-first-details-about-BYD-s-AI-robot.1352248.0.html",
            "accent": "#f5a623",
            "motif": "headset",
            "image": "pipeline/media/byd-xiaodi-robot.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "brainco-bci-robot",
            "eyebrow": "AI NEWS",
            "tool": "BrainCo",
            "headline": "브레인코, 생각만으로 로봇을 조종하는 기술을 선보인다",
            "body": "브레인코가 WAIC 2026에서 뇌 신호만으로 로봇 손과 휴머노이드를 조종하는 기술을 시연했다.",
            "source": "Notebookcheck",
            "url": "https://www.notebookcheck.net/BrainCo-unveils-brain-controlled-robot-AI-platform-The-future-of-eating-Cheetos-while-building-PCs-hands-free-with-just-a-thought.1346280.0.html",
            "accent": "#7928ca",
            "motif": "headset",
            "image": "pipeline/media/brainco-bci-robot.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "looki-ai-pendant",
            "eyebrow": "AI NEWS",
            "tool": "Looki",
            "headline": "루키, 하루 종일 녹화하는 AI 목걸이의 앞날을 비춘다",
            "body": "늘 켜진 AI 카메라 목걸이 루키를 석 달간 걸친 CNET 기자가 그 어색함과 사생활 부담을 전한다.",
            "source": "CNET",
            "url": "https://www.cnet.com/tech/mobile/my-life-with-looki-is-a-harbinger-of-always-on-recording-glasses-to-come/",
            "accent": "#2ec5c5",
            "motif": "headset",
            "image": "pipeline/media/looki-ai-pendant.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "meta-glasses-subscription",
            "eyebrow": "AI NEWS",
            "tool": "Meta",
            "headline": "메타, 스마트 글래스 AI 기능에 구독제를 다시 저울질한다",
            "body": "메타가 대화 초점 기능에 요금제를 붙이려던 계획을 반발에 접었지만 다른 기능의 유료화 여지는 남겼다.",
            "source": "Gizmodo",
            "url": "https://gizmodo.com/meta-is-rethinking-subscriptions-on-its-smart-glasses-2000791288",
            "accent": "#eb367f",
            "motif": "headset",
            "image": "pipeline/media/meta-glasses-subscription.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-29",
        "cards": [
          {
            "id": "gemini-automation",
            "eyebrow": "AI NEWS",
            "tool": "Gemini",
            "headline": "제미나이 작업 자동화가 40개 넘는 앱으로 확장됐다",
            "body": "갤럭시 Z 폴드8에 처음 실린 제미나이가 쇼핑과 예약, 여행까지 40개 넘는 앱에서 여러 단계 작업을 대신 처리한다.",
            "source": "9to5Google",
            "url": "https://9to5google.com/2026/07/22/gemini-task-automation-samsung/",
            "accent": "#ff5a4d",
            "motif": "headset",
            "image": "pipeline/media/gemini-automation.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "ai-activity-dashboard",
            "eyebrow": "AI NEWS",
            "tool": "Samsung",
            "headline": "백그라운드 AI를 지켜보는 삼성의 새 대시보드",
            "body": "원 UI 9은 제미나이가 백그라운드에서 처리한 작업을 한곳에서 확인하는 AI 활동 대시보드를 새로 담았다.",
            "source": "Android Authority",
            "url": "https://www.androidauthority.com/samsung-one-ui-9-ai-assistant-activity-dashboard-3690155/",
            "accent": "#0070f3",
            "motif": "headset",
            "image": "pipeline/media/ai-activity-dashboard.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "galaxy-watch-9-health",
            "eyebrow": "AI NEWS",
            "tool": "Samsung",
            "headline": "갤럭시 워치9·울트라2에 AI 건강 기능이 붙었다",
            "body": "삼성이 갤럭시 워치9와 울트라2를 내놓으며 개인 건강 코치와 피트니스 지수, 혈관 부하 등 AI 건강 기능을 담았다.",
            "source": "Android Central",
            "url": "https://www.androidcentral.com/wearables/samsung-galaxy-watch/galaxy-watch-9-watch-ultra-2-are-here-samsung-health-partners-launch",
            "accent": "#f5a623",
            "motif": "headset",
            "image": "pipeline/media/galaxy-watch-9-health.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-30",
        "cards": [
          {
            "id": "meta-ray-ban-display-muse-spark",
            "eyebrow": "AI NEWS",
            "tool": "Meta",
            "headline": "레이밴 디스플레이가 뮤즈 스파크로 똑똑해졌다",
            "body": "메타가 레이밴 디스플레이에 더 빠른 뮤즈 스파크 AI를 배포하기 시작했다.",
            "source": "Gizmodo",
            "url": "https://gizmodo.com/the-meta-ray-ban-displays-dumb-smart-glasses-ai-is-dumb-no-more-2000791752",
            "accent": "#ff5a4d",
            "motif": "headset",
            "image": "pipeline/media/meta-ray-ban-display-muse-spark.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "oura-ring-5-advisor",
            "eyebrow": "AI NEWS",
            "tool": "Oura",
            "headline": "오우라 링5가 더 작아지고 어드바이저 AI로 코치한다",
            "body": "5세대 오우라 링이 40% 작아지고, 오우라 어드바이저 AI가 건강 조언을 건넨다.",
            "source": "Gizmodo",
            "url": "https://gizmodo.com/oura-ring-5-review-the-best-smart-ring-right-now-and-its-not-close-2000785576",
            "accent": "#eb367f",
            "motif": "headset",
            "image": "pipeline/media/oura-ring-5-advisor.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "ios-27-siri-apple-intelligence",
            "eyebrow": "AI NEWS",
            "tool": "Apple",
            "headline": "iOS 27의 새 시리가 기대를 그대로 채웠다",
            "body": "iOS 27의 새 시리가 폭넓은 지식과 대화형 UI, 애플 기기 통합까지 채웠다.",
            "source": "9to5Mac",
            "url": "https://9to5mac.com/2026/07/23/ios-27s-new-siri-delivers-in-every-single-way-id-hoped-for/",
            "accent": "#f5a623",
            "motif": "headset",
            "image": "pipeline/media/ios-27-siri-apple-intelligence.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "alexa-plus-smart-home-app-store",
            "eyebrow": "AI NEWS",
            "tool": "Alexa+",
            "headline": "알렉사+가 스마트홈 앱 스토어로 열렸다",
            "body": "아마존이 스마트홈 제조사가 기기 기능을 알렉사+에 연결하도록 개발자 툴킷을 열었다.",
            "source": "Digital Trends",
            "url": "https://www.digitaltrends.com/computing/amazon-just-turned-alexa-into-a-full-blown-app-store/",
            "accent": "#0070f3",
            "motif": "headset",
            "image": "pipeline/media/alexa-plus-smart-home-app-store.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-31",
        "cards": [
          {
            "id": "gemini-robotics2",
            "eyebrow": "AI NEWS",
            "tool": "Google DeepMind",
            "headline": "제미나이 로보틱스 2, 휴머노이드의 전신을 제어하다",
            "body": "팔과 몸통, 이동 베이스를 함께 조율하는 전신 제어로 휴머노이드가 쓰레기봉투를 묶고 전구를 갈아 끼운다.",
            "source": "The Verge",
            "url": "https://www.theverge.com/tech/973276/google-deepmind-gemini-robotics-2-whole-body",
            "accent": "#ff5a4d",
            "motif": "headset",
            "image": "pipeline/media/gemini-robotics2.png",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "openai-companion-speaker",
            "eyebrow": "AI NEWS",
            "tool": "OpenAI",
            "headline": "OpenAI의 첫 기기는 화면 없는 이동형 AI 동반자 스피커",
            "body": "오픈AI의 첫 제품은 조니 아이브와 만든 화면 없는 휴대형 AI 동반자 스피커로, 카메라로 주변을 인식한다.",
            "source": "MacRumors",
            "url": "https://www.macrumors.com/2026/07/28/openai-first-devices/",
            "accent": "#0070f3",
            "motif": "headset",
            "image": "pipeline/media/openai-companion-speaker.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "m4-max-local-ai",
            "eyebrow": "AI NEWS",
            "tool": "Apple",
            "headline": "M4 Max로 살펴본 애플 실리콘의 로컬 AI 성능",
            "body": "맥 스튜디오의 M4 Max가 엔비디아 GB10, AMD 스트릭스 헤일로와의 로컬 LLM 벤치마크에서 디코드 처리량 선두를 차지했다.",
            "source": "Tom's Hardware",
            "url": "https://www.tomshardware.com/desktops/exploring-apple-silicons-local-ai-performance-with-the-mac-studio-and-m4-max-m4-max-beats-gb10-and-strix-halo-in-decode-throughput-but-memory-bandwidth-isnt-everything",
            "accent": "#7928ca",
            "motif": "headset",
            "image": "pipeline/media/m4-max-local-ai.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "dji-osmo-pocket4p",
            "eyebrow": "AI NEWS",
            "tool": "DJI",
            "headline": "DJI 오스모 포켓 4P, 듀얼 렌즈로 프로에 다가서다",
            "body": "두 개의 렌즈와 광학 줌, 넓은 다이내믹 레인지, AI 피사체 추적을 더해 1인 창작자의 촬영 방식을 새로 짠다.",
            "source": "Engadget",
            "url": "https://www.engadget.com/2226364/dji-osmo-pocket-4p-review/",
            "accent": "#2ec5c5",
            "motif": "headset",
            "image": "pipeline/media/dji-osmo-pocket4p.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "halliday-g2",
            "eyebrow": "AI NEWS",
            "tool": "Halliday",
            "headline": "할리데이 G2, 카메라 없이 회의를 돕는 스마트 글래스",
            "body": "카메라를 빼고 양안 마이크로 LED 디스플레이로 실시간 번역과 자막, 회의록을 50g 미만 프레임에 담았다.",
            "source": "Android Authority",
            "url": "https://www.androidauthority.com/halliday-g2-smart-glasses-launch-3689649/",
            "accent": "#eb367f",
            "motif": "headset",
            "image": "pipeline/media/halliday-g2.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-08-01",
        "cards": [
          {
            "id": "adobe-project-indigo",
            "eyebrow": "AI NEWS",
            "tool": "Gadgets",
            "headline": "어도비 실험 카메라 앱에 생성형 AI가 들어왔다",
            "body": "어도비가 실험용 카메라 앱 프로젝트 인디고에 생성 편집과 스타일 변환을 얹은 AI 플레이그라운드를 더했다.",
            "source": "Engadget",
            "url": "https://www.engadget.com/2218980/adobe-crams-multiple-ai-tools-into-its-experimental-camera-app/",
            "accent": "#ff5a4d",
            "motif": "headset",
            "image": "pipeline/media/adobe-project-indigo.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "samsung-health-assistant",
            "eyebrow": "AI NEWS",
            "tool": "Gadgets",
            "headline": "삼성 건강 데이터를 AI가 대신 읽어준다",
            "body": "삼성 헬스에 들어온 AI 챗봇 헬스 어시스턴트가 웰니스 데이터를 풀어 맞춤형 생활 조언을 건넨다.",
            "source": "Engadget",
            "url": "https://www.engadget.com/2219698/samsung-aims-to-help-you-make-more-sense-of-health-data-with-a-new-ai-powered-assistant/",
            "accent": "#0070f3",
            "motif": "headset",
            "image": "pipeline/media/samsung-health-assistant.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "friend-2-pendant",
            "eyebrow": "AI NEWS",
            "tool": "Gadgets",
            "headline": "AI 목걸이 프렌드가 스피커를 달고 돌아왔다",
            "body": "늘 듣고 있던 AI 동반자 프렌드가 249달러 2.0으로 돌아와 음성 응답과 월 구독 기억을 얹었다.",
            "source": "Gizmodo",
            "url": "https://gizmodo.com/friend-is-back-with-a-new-ai-pendant-and-its-marketing-is-more-depressing-than-ever-2000793089",
            "accent": "#f5a623",
            "motif": "headset",
            "image": "pipeline/media/friend-2-pendant.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      }
    ],
    "lockedCount": 0
  },
  "science": {
    "label": "Science",
    "news": [
      {
        "id": "ai-telescope-stargazing",
        "eyebrow": "AI NEWS",
        "headline": "실시간으로 하늘을 살피며\n스스로 관측하는 AI 망원경",
        "body": "노스웨스턴대 연구진의 강화학습 AI가 날씨와 하늘 상태에 맞춰 다크에너지카메라의 관측 일정을 스스로 짠다.",
        "tool": "Science",
        "source": "Phys.org (Northwestern University)",
        "url": "https://phys.org/news/2026-07-ai-driven-telescope-stargazing.html",
        "accent": "#2ec5c5",
        "motif": "sphere",
        "full": {
          "mode": "full",
          "blocks": [
            {
              "t": "p",
              "x": "밤하늘을 관측할 때 무엇을, 언제, 어느 방향으로 볼지 정하는 일은 그동안 사람의 몫이었다. 노스웨스턴대와 시카고대, 페르미연구소가 함께한 이번 연구는 그 판단을 강화학습 AI에게 맡겼다."
            },
            {
              "t": "img",
              "src": "https://scx1.b-cdn.net/csz/news/800a/2026/first-ai-driven-telesc.jpg"
            },
            {
              "t": "p",
              "x": "AI는 다크에너지카메라의 관측 일정을 스스로 세운다. 하늘 상태와 날씨가 시시각각 달라지면 계획도 실시간으로 고쳐 잡는다. 사람이 일일이 조정하지 않아도 상황에 맞춰 다음 관측을 이어가는 방식이다."
            },
            {
              "t": "p",
              "x": "연구진은 이 AI의 성능이 숙련된 사람 일정 담당자와 견줄 만하다고 평가했다. 스스로 돌아가는 천문대로 가는 길에 놓인 하나의 이정표이자, AI가 관측천문학을 직접 밀어 올린 사례인 셈이다."
            }
          ]
        },
        "image": "pipeline/media/ai-telescope-stargazing.jpg",
        "free": true,
        "hasFull": true
      },
      {
        "id": "ai-agent-synchrotron",
        "eyebrow": "AI NEWS",
        "headline": "싱크로트론 실험을 스스로\n준비하는 AI 에이전트",
        "body": "스탠퍼드·SLAC의 AI 에이전트가 검출기 영상과 실험 기록을 읽고 장비를 제어해 결정 시료를 스스로 정렬한다.",
        "tool": "Science",
        "source": "Phys.org (Stanford / SLAC)",
        "url": "https://phys.org/news/2026-07-ai-agent-synchrotron-ray-experimental.html",
        "accent": "#0070f3",
        "motif": "sphere",
        "image": "pipeline/media/ai-agent-synchrotron.jpg",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "brain-age-sleep-eeg",
        "eyebrow": "AI NEWS",
        "headline": "수면 뇌파로 잰 뇌 나이가\n치매 위험을 앞서 짚는다",
        "body": "UCSF 연구진이 성인 약 7천 명의 수면 뇌파로 뇌 나이를 추정하니, 실제보다 늙은 뇌는 치매 위험이 크게 높았다.",
        "tool": "Science",
        "source": "ScienceDaily (UC San Francisco)",
        "url": "https://www.sciencedaily.com/releases/2026/07/260729051540.htm",
        "accent": "#7928ca",
        "motif": "sphere",
        "image": "pipeline/media/brain-age-sleep-eeg.jpg",
        "hasFull": true,
        "locked": true
      }
    ],
    "days": [
      {
        "date": "2026-07-28",
        "cards": [
          {
            "id": "syntnpb",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "AI가 설계한 유전자 편집 효소가 자연 효소를 앞서다",
            "body": "ESM-IF1이 설계한 합성 TnpB 효소가 사람 세포에서 자연형 28%를 웃도는 46~50% 효율을 냈다.",
            "source": "Phys.org",
            "url": "https://phys.org/news/2026-07-aidesigned-geneediting-enzymes-crispr-toolbox.html",
            "accent": "#2ec5c5",
            "motif": "sphere",
            "image": "pipeline/media/syntnpb.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "corgigenome",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "DNA가 세포마다 유전자를 어떻게 켜는지 읽는 AI",
            "body": "막스플랑크 연구진이 만든 Corgi는 세포 유형마다 유전자가 켜지고 꺼지는 양상을 예측한다.",
            "source": "Phys.org",
            "url": "https://phys.org/news/2026-07-ai-tool-dna-sequences-genes.html",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/corgigenome.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "cognitivebci",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "인지 장애를 겨냥한 뇌-컴퓨터 인터페이스",
            "body": "마운트시나이 연구진은 우울증과 불안, PTSD, 강박을 겨냥한 인지형 BCI 로드맵을 내놨다.",
            "source": "EurekAlert! (Mount Sinai)",
            "url": "https://www.eurekalert.org/news-releases/1136848",
            "accent": "#7928ca",
            "motif": "sphere",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "platondetector",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "보이지 않는 입자를 3D로 쫓는 카메라",
            "body": "ETH취리히 연구진이 빛의 장 카메라와 AI 신경망으로 섬광체 한 덩어리에서 입자 경로를 3D로 복원했다.",
            "source": "ScienceDaily (ETH Zurich)",
            "url": "https://www.sciencedaily.com/releases/2026/07/260716023610.htm",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/platondetector.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-29",
        "cards": [
          {
            "id": "l2t",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "관찰만으로 세상의 규칙을 스스로 세우는 AI",
            "body": "KAIST 연구진의 L2T는 관찰만으로 변화의 규칙을 스스로 찾아 실행 가능한 프로그램으로 엮어낸다.",
            "source": "Tech Xplore",
            "url": "https://techxplore.com/news/2026-07-children-ai-framework-theorize-world.html",
            "accent": "#2ec5c5",
            "motif": "sphere",
            "image": "pipeline/media/l2t.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "quasar",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "AI가 DESI 자료를 훑어 렌즈 퀘이사를 두 배로",
            "body": "오하이오주립대 팀이 모의 렌즈로 훈련한 AI로 80만 개 DESI 천체에서 렌즈 퀘이사 후보 7개를 찾아냈다.",
            "source": "Phys.org",
            "url": "https://phys.org/news/2026-07-quasar-lenses-emerge-ai-scan.html",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/quasar.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "binn",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "신경망이 토양 탄소를 50배 빠르게 측정하다",
            "body": "코넬 연구진의 생지화학 기반 신경망 BINN은 정확도를 지키면서 토양 탄소를 이전보다 50배 빠르게 계산한다.",
            "source": "Phys.org",
            "url": "https://phys.org/news/2026-07-soil-carbon-effectively-efficient-ai.html",
            "accent": "#7928ca",
            "motif": "sphere",
            "image": "pipeline/media/binn.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "symptomai",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "대화형 진단 AI의 소견을 의사들이 더 선호했다",
            "body": "구글 리서치의 대화형 진단 에이전트 SymptomAI가 낸 감별 진단을 임상의들이 절반 넘는 사례에서 동료보다 선호했다.",
            "source": "Google Research",
            "url": "https://research.google/blog/symptomai-towards-a-conversational-ai-agent-for-everyday-symptom-assessment/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/symptomai.png",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-30",
        "cards": [
          {
            "id": "raygun-protein-redesign",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "단백질을 수식으로 바꿔 다시 설계하는 Raygun",
            "body": "듀크대 연구진이 단백질을 표준 수식으로 바꿔 크기와 형태를 자유롭게 다시 설계했다.",
            "source": "Phys.org",
            "url": "https://phys.org/news/2026-07-molecular-ray-ai-tool-redesigns.html",
            "accent": "#2ec5c5",
            "motif": "sphere",
            "image": "pipeline/media/raygun-protein-redesign.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "quantum-rl-self-calibration",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "오류에서 배워 스스로 조율하는 양자컴퓨터",
            "body": "구글의 강화학습 에이전트가 오류 신호로 수천 개 제어 변수를 실시간 보정했다.",
            "source": "Google Research",
            "url": "https://research.google/blog/towards-a-quantum-computer-that-learns-from-its-errors/",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/quantum-rl-self-calibration.png",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "single-sensor-ultrasound-ai",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "센서 하나로 즉석 초음파 영상을 되살리는 AI",
            "body": "IMDEA 연구진이 센서 하나가 잡은 신호만으로 완전한 초음파 영상을 복원했다.",
            "source": "Tech Xplore",
            "url": "https://techxplore.com/news/2026-07-ai-powered-method-enables-instant.html",
            "accent": "#7928ca",
            "motif": "sphere",
            "image": "pipeline/media/single-sensor-ultrasound-ai.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "solid-state-battery-database",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "고체 배터리 설계를 여는 표준 데이터베이스",
            "body": "메릴랜드대가 245개 기록과 167개 변수를 표준화한 고체 배터리 DB를 내놓았다.",
            "source": "Tech Xplore",
            "url": "https://techxplore.com/news/2026-07-standardized-battery-database-ai-solid.html",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/solid-state-battery-database.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-07-31",
        "cards": [
          {
            "id": "quantum-ml-neoantigen",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "양자 머신러닝으로 종양 신항원의 면역 반응을 예측하다",
            "body": "적은 표본으로도 어떤 신항원이 면역 반응을 일으킬지 예측해 고전 기법을 앞선다.",
            "source": "The Quantum Insider",
            "url": "https://thequantuminsider.com/2026/07/30/cleveland-clinic-and-ibm-researchers-create-quantum-machine-learning-framework-to-predict-neoantigen-immune-response/",
            "accent": "#2ec5c5",
            "motif": "sphere",
            "image": "pipeline/media/quantum-ml-neoantigen.png",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "quantum-neural-net-barren",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "'불모의 고원'을 피해 커지는 양자 신경망",
            "body": "새 이론 틀은 확장 가능한 두 회로 구조와 병렬 학습법으로 배런 플래토를 수학적으로 피한다.",
            "source": "The Quantum Insider",
            "url": "https://thequantuminsider.com/2026/07/28/quantum-machine-learning-design-targets-training-and-scaling-barriers/",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/quantum-neural-net-barren.png",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "alphafold-impossible-structures",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "AI 단백질 예측이 물리·화학적으로 불가능한 구조를 내놓는다",
            "body": "주요 예측 도구가 물리·화학적으로 불가능한 구조를 자주 내놓아 분자동역학 검증과 사람 검토가 여전히 필요하다.",
            "source": "Phys.org",
            "url": "https://phys.org/news/2026-07-ai-tools-protein-chemically-impossible.html",
            "accent": "#7928ca",
            "motif": "sphere",
            "image": "pipeline/media/alphafold-impossible-structures.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "ai-drug-discovery-data-loop",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "AI 신약 발견의 병목은 이제 실험실 데이터다",
            "body": "AI가 치료 표적을 빠르게 찾아낼수록 실험실의 물리적 한계와 양질의 실험 데이터 부족이 드러난다.",
            "source": "MIT Technology Review",
            "url": "https://www.technologyreview.com/2026/07/27/1139667/closing-the-data-loop-in-ai-driven-drug-discovery/",
            "accent": "#f5a623",
            "motif": "sphere",
            "image": "pipeline/media/ai-drug-discovery-data-loop.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      },
      {
        "date": "2026-08-01",
        "cards": [
          {
            "id": "blue-oled",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "양자화학과 AI로 찾은 고순도 파란빛 OLED 소재",
            "body": "나고야대 연구진이 양자화학 시뮬레이션과 기계학습을 결합해 붕소 없이 선명한 청색광을 내는 분자를 설계했다.",
            "source": "Phys.org (Nagoya University)",
            "url": "https://phys.org/news/2026-07-ai-quantum-chemistry-combine-efficient.html",
            "accent": "#2ec5c5",
            "motif": "sphere",
            "image": "pipeline/media/blue-oled.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "goflow",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "위성 영상에서 숨은 바다 표층 해류를 읽는 AI",
            "body": "텔아비브대의 GOFLOW는 위성 영상만으로 그동안 볼 수 없던 바다 표층 해류를 복원해 기후 예측의 입력값을 넓힌다.",
            "source": "Tech Xplore (Tel Aviv University)",
            "url": "https://techxplore.com/news/2026-07-ai-powered-unprecedented-insight-earth.html",
            "accent": "#0070f3",
            "motif": "sphere",
            "image": "pipeline/media/goflow.jpg",
            "hasFull": true,
            "locked": true
          },
          {
            "id": "material-rules",
            "eyebrow": "AI NEWS",
            "tool": "Science",
            "headline": "미시 데이터에서 찾아낸 물질의 숨은 거동 법칙",
            "body": "싱가포르국립대 연구진이 미시 데이터 속 숨은 변수를 찾아내 물질의 대규모 거동을 예측하고 계산 비용을 줄였다.",
            "source": "Tech Xplore (National University of Singapore)",
            "url": "https://techxplore.com/news/2026-07-ai-hidden-material-microscopic-large.html",
            "accent": "#7928ca",
            "motif": "sphere",
            "image": "pipeline/media/material-rules.jpg",
            "hasFull": true,
            "locked": true
          }
        ]
      }
    ],
    "lockedCount": 2
  }
};
  window.AX_SECTION_ORDER = [
  "design",
  "music",
  "movies",
  "games",
  "books",
  "gadgets",
  "science"
];
  // back-compat (large-card app reads these until it becomes section-aware):
  window.AX_NEWS = [
  {
    "id": "figma-make",
    "eyebrow": "AI NEWS",
    "headline": "피그마 메이크에 속성 패널과\n주석 기능이 더해졌다",
    "body": "AI가 만든 화면을 속성 패널로 직접 손보고, 다시 프롬프트를 쓰지 않고도 의도를 코드로 넘긴다.",
    "tool": "Figma",
    "source": "Figma",
    "url": "https://www.figma.com/blog/properties-panel-and-annotations-now-in-figma-make/",
    "accent": "#0070f3",
    "motif": "frame",
    "full": {
      "mode": "summary",
      "blocks": [
        {
          "t": "img",
          "src": "https://cdn.sanity.io/images/599r6htc/regionalized/d1366af0a7f2c9945aa6a7a693f319518f22fc63-3840x2160.png"
        },
        {
          "t": "p",
          "x": "피그마 메이크에 시각적 속성 패널과 주석 기능이 들어왔다."
        },
        {
          "t": "p",
          "x": "디자이너는 AI가 만들어 낸 결과물을 곧바로 손볼 수 있고, 프롬프트를 다시 쓰지 않고도 그 의도를 코드 쪽으로 넘긴다."
        },
        {
          "t": "p",
          "x": "디자인에서 코드로 이어지는 고리를 한층 조인, 피그마 AI 빌더의 실제 기능 업데이트다."
        }
      ]
    },
    "image": "pipeline/media/figma-make.png",
    "free": true,
    "hasFull": true
  },
  {
    "id": "perplexity-color",
    "eyebrow": "AI NEWS",
    "headline": "생성형 AI로 발산형\n데이터 색상 체계를 만든다",
    "body": "퍼플렉시티로 발산형 데이터 시각화 팔레트를 짜며, 접근성까지 챙긴 색상 토큰을 만든다.",
    "tool": "Design Tokens",
    "source": "UX Collective",
    "url": "https://uxdesign.cc/perplexity-diverges-with-color-cad28cbe7bad",
    "accent": "#2ec5c5",
    "motif": "swatch",
    "image": "pipeline/media/perplexity-color.png",
    "hasFull": true,
    "locked": true
  },
  {
    "id": "unwanted-ai-images",
    "eyebrow": "AI NEWS",
    "headline": "원치 않는 AI 이미지가\n사람들을 불안하게 한다",
    "body": "아마존과 틴더, 레딧이 사용자 사진을 기본값으로 AI 편집하고, 거부는 사용자 몫으로 남긴다.",
    "tool": "AI Workflow",
    "source": "Creative Bloq",
    "url": "https://www.creativebloq.com/ai/from-amazon-to-tinder-and-reddit-tech-platforms-are-giving-users-ai-images-they-didnt-ask-for",
    "accent": "#ff5a4d",
    "motif": "frame",
    "image": "pipeline/media/unwanted-ai-images.jpg",
    "hasFull": true,
    "locked": true
  },
  {
    "id": "ai-fluency",
    "eyebrow": "AI NEWS",
    "headline": "AI 능숙함은\n결승선이 아니다",
    "body": "제품 제작자 90%가 AI 역량을 필수로 꼽지만, 피그마는 팀이 엉뚱한 능력에 매달린다고 짚는다.",
    "tool": "AI Workflow",
    "source": "Figma",
    "url": "https://www.figma.com/blog/ai-fluency-isnt-the-finish-line/",
    "accent": "#3b6bff",
    "motif": "frame",
    "image": "pipeline/media/ai-fluency.png",
    "hasFull": true,
    "locked": true
  },
  {
    "id": "creative-technologists",
    "eyebrow": "AI NEWS",
    "headline": "크리에이티브 테크놀로지스트가\n중심으로 옮겨간다",
    "body": "AI가 디자인과 코드의 간극을 좁히며, 직접 만드는 디자이너가 변방에서 팀의 기본값으로 옮겨간다.",
    "tool": "AI Workflow",
    "source": "UX Collective",
    "url": "https://uxdesign.cc/creative-technologists-are-moving-from-the-margins-to-the-center-4fcfaa3cf2f6",
    "accent": "#eb367f",
    "motif": "frame",
    "image": "pipeline/media/creative-technologists.png",
    "hasFull": true,
    "locked": true
  }
];
  window.AX_DAYS = [
  {
    "date": "2026-07-28",
    "cards": [
      {
        "id": "pincushion-ui-feedback",
        "eyebrow": "AI NEWS",
        "tool": "AI Workflow",
        "headline": "라이브 앱에 남긴 지적이 사람 손질 없이 PR이 된다",
        "body": "라이브 앱에 꽂은 핀이 선택자와 뷰포트까지 담아 코딩 에이전트가 MCP로 받아 PR로 만든다.",
        "source": "DEV Community",
        "url": "https://dev.to/matttdamon/from-feedback-to-merged-pr-making-ui-feedback-agent-actionable-12a8",
        "accent": "#ff5a4d",
        "motif": "frame",
        "image": "pipeline/media/pincushion-ui-feedback.png",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "ai-websites-samey",
        "eyebrow": "AI NEWS",
        "tool": "AI Workflow",
        "headline": "AI로 뽑아낸 웹사이트가 하나같이 똑같아 보이는 까닭",
        "body": "똑같은 히어로와 카드 그리드가 반복되는 건 모델이 디자인 대신 흔한 패턴을 되풀이해서다.",
        "source": "DEV Community",
        "url": "https://dev.to/lyd_lyd_d4869af25d33ce0eb/why-do-ai-generated-websites-all-look-the-same-k2j",
        "accent": "#3b6bff",
        "motif": "cube",
        "image": "pipeline/media/ai-websites-samey.png",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "netflix-genai-boycott",
        "eyebrow": "AI NEWS",
        "tool": "AI Workflow",
        "headline": "생성형 AI가 싫다면 넷플릭스를 떠날 이유는 충분하다",
        "body": "넷플릭스가 올해에만 약 300편에 생성형 AI를 끌어들였다고 주주 서한에서 밝혔다.",
        "source": "Creative Bloq",
        "url": "https://www.creativebloq.com/ai/hate-generative-ai-maybe-its-time-to-boycott-netflix",
        "accent": "#2ec5c5",
        "motif": "swatch",
        "image": "pipeline/media/netflix-genai-boycott.jpg",
        "hasFull": true,
        "locked": true
      }
    ]
  },
  {
    "date": "2026-07-29",
    "cards": [
      {
        "id": "macpaw-eney",
        "eyebrow": "AI NEWS",
        "tool": "Design Tokens",
        "headline": "채팅창을 벗어난 AI 조수 MacPaw의 캐릭터 실험",
        "body": "MacPaw는 텍스트 창 대신 표정을 지닌 원형 캐릭터 Eney를 만들어 AI 조수를 다시 설계했다.",
        "source": "Smashing Magazine",
        "url": "https://www.smashingmagazine.com/2026/07/digital-design-ai-era/",
        "accent": "#2ec5c5",
        "motif": "swatch",
        "image": "pipeline/media/macpaw-eney.jpg",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "no-handoff",
        "eyebrow": "AI NEWS",
        "tool": "Figma",
        "headline": "디자이너가 AI를 지휘해 핸드오프 없이 직접 만든다",
        "body": "디자이너 Merav Shaked는 AI를 팀처럼 지휘해 하룻밤 만에 포트폴리오를 직접 다시 만들었다.",
        "source": "DEV Community",
        "url": "https://dev.to/meravish/i-design-products-then-i-make-them-there-is-no-handoff-2bof",
        "accent": "#0070f3",
        "motif": "frame",
        "image": "pipeline/media/no-handoff.png",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "octane-neural",
        "eyebrow": "AI NEWS",
        "tool": "KeyShot",
        "headline": "OctaneRender 2027.1 신경망 렌더링을 알파 공개",
        "body": "Otoy는 낮은 샘플에서도 노이즈가 거의 없는 신경망 렌더링을 OctaneRender 알파에 담았다.",
        "source": "CG Channel",
        "url": "https://www.cgchannel.com/2026/07/otoy-releases-octanerender-2027-1-in-alpha/",
        "accent": "#f5a623",
        "motif": "sphere",
        "image": "pipeline/media/octane-neural.jpg",
        "hasFull": true,
        "locked": true
      }
    ]
  },
  {
    "date": "2026-07-30",
    "cards": [
      {
        "id": "agent-native-actions",
        "eyebrow": "AI NEWS",
        "tool": "Figma",
        "headline": "UI가 하는 일은 모두 에이전트도 할 수 있다",
        "body": "모든 기능을 액션 하나로 묶어, 화면에서 되는 일이면 에이전트도 똑같이 처리한다.",
        "source": "Builder.io",
        "url": "https://www.builder.io/blog/agent-first-apps",
        "accent": "#0070f3",
        "motif": "frame",
        "image": "pipeline/media/agent-native-actions.jpg",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "where-ai-belongs-games",
        "eyebrow": "AI NEWS",
        "tool": "KeyShot",
        "headline": "AI가 게임 개발에서 진짜 있어야 할 자리",
        "body": "디켄은 생성형 AI의 쓸모가 콘텐츠 자동화보다 저마다 다른 경험에 있다고 본다.",
        "source": "80 Level",
        "url": "https://80.lv/articles/game-ai-expert-explains-where-ai-actually-belongs-in-game-development-and-the-risks",
        "accent": "#f5a623",
        "motif": "sphere",
        "image": "pipeline/media/where-ai-belongs-games.jpg",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "nexthena-121-i18n",
        "eyebrow": "AI NEWS",
        "tool": "Design Tokens",
        "headline": "AI 화이트보드 넥스테나 다국어와 테마를 다듬다",
        "body": "넥스테나 1.2.1이 영어·중국어 전환을 더해, 화이트보드가 OS 명암을 따른다.",
        "source": "DEV Community",
        "url": "https://dev.to/blackstar/nexthena-121-released-2alp",
        "accent": "#2ec5c5",
        "motif": "swatch",
        "image": "pipeline/media/nexthena-121-i18n.png",
        "hasFull": true,
        "locked": true
      }
    ]
  },
  {
    "date": "2026-07-31",
    "cards": [
      {
        "id": "nanobanana-earth",
        "eyebrow": "AI NEWS",
        "tool": "KeyShot",
        "headline": "나노 바나나가 구글 어스에서 과거와 미래를 그려낸다",
        "body": "나노 바나나가 구글 어스에 들어가 지도 위에서 옛 유적과 지어질 건물을 실사처럼 그려낸다.",
        "source": "Engadget",
        "url": "https://www.engadget.com/2226451/nano-banana-image-generation-comes-to-google-earth/",
        "accent": "#f5a623",
        "motif": "sphere",
        "image": "pipeline/media/nanobanana-earth.jpg",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "shieldfont-poison-ai",
        "eyebrow": "AI NEWS",
        "tool": "Figma",
        "headline": "AI 학습을 오염시키는 무료 폰트 실드폰트",
        "body": "타이포 디자이너들이 긁어간 글과 이미지로 AI가 학습하지 못하게 오염시키는 무료 폰트를 공개했다.",
        "source": "Creative Bloq",
        "url": "https://www.creativebloq.com/design/fonts-typography/type-designers-have-created-a-free-font-that-poisons-ai",
        "accent": "#0070f3",
        "motif": "frame",
        "image": "pipeline/media/shieldfont-poison-ai.jpg",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "bull-bear-design-ai",
        "eyebrow": "AI NEWS",
        "tool": "Design Tokens",
        "headline": "AI가 디자이너에게 줄 자율과 드러날 빈틈",
        "body": "앤디 버드는 AI가 디자이너에게 더 큰 자율을 주는 동시에, 감춰 온 실력 격차를 드러낸다고 본다.",
        "source": "Smashing Magazine",
        "url": "https://smashingmagazine.com/2026/07/bull-and-bear-case-digital-design-age-ai/",
        "accent": "#2ec5c5",
        "motif": "swatch",
        "image": "pipeline/media/bull-bear-design-ai.jpg",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "get-out-of-their-way",
        "eyebrow": "AI NEWS",
        "tool": "Figma",
        "headline": "AI를 이미 아는 팀에게 자리를 내주어라",
        "body": "모두 같은 AI 도구를 쥔 지금, 승부는 그 도구를 이미 이해한 실무자를 믿고 맡기는 팀에서 갈린다.",
        "source": "UX Collective",
        "url": "https://uxdesign.cc/your-people-get-ai-get-out-of-their-way-131370c157f8",
        "accent": "#3b6bff",
        "motif": "frame",
        "image": "pipeline/media/get-out-of-their-way.jpg",
        "hasFull": true,
        "locked": true
      }
    ]
  },
  {
    "date": "2026-08-01",
    "cards": [
      {
        "id": "google-earth-rollback",
        "eyebrow": "AI NEWS",
        "tool": "KeyShot",
        "headline": "구글, 지도에 붙인 생성 AI 도구를 되돌리다",
        "body": "구글이 지도의 신뢰를 해친다는 반발에 구글 어스의 생성형 이미지 도구를 며칠 만에 거둬들였다.",
        "source": "Engadget",
        "url": "https://www.engadget.com/2228142/google-rolls-back-the-needless-ai-generation-tools-it-added-to-google-earth/",
        "accent": "#f5a623",
        "motif": "sphere",
        "image": "pipeline/media/google-earth-rollback.jpg",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "rebelle-brush",
        "eyebrow": "AI NEWS",
        "tool": "KeyShot",
        "headline": "생성 AI 대신 붓의 감각을 택한 리벨",
        "body": "리벨 8.3은 생성 AI를 좇는 대신 물리적으로 사실적인 붓과 수채 시뮬레이션에 더 깊이 파고든다.",
        "source": "Creative Bloq",
        "url": "https://www.creativebloq.com/art/digital-art-software/rebelle-8-3-proves-the-future-of-digital-painting-isnt-ai-its-making-brushes-feel-real",
        "accent": "#7928ca",
        "motif": "sphere",
        "image": "pipeline/media/rebelle-brush.jpg",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "jakobs-law-chatbox",
        "eyebrow": "AI NEWS",
        "tool": "Figma",
        "headline": "화면이 채팅창 하나로 합쳐질 때의 야코프 법칙",
        "body": "AI가 여러 화면을 채팅창 하나로 합치는 지금, 사용자가 길을 잃지 않게 지킬 익숙함의 규칙을 다시 짚는다.",
        "source": "UX Collective",
        "url": "https://uxdesign.cc/jakobs-law-how-to-apply-it-as-ai-collapses-surfaces-into-one-chat-box-d8ebc9a727db",
        "accent": "#0070f3",
        "motif": "frame",
        "image": "pipeline/media/jakobs-law-chatbox.png",
        "hasFull": true,
        "locked": true
      },
      {
        "id": "rethinking-friction",
        "eyebrow": "AI NEWS",
        "tool": "AI Workflow",
        "headline": "AI 시대에 다시 묻는 마찰의 쓸모",
        "body": "AI가 무엇이든 즉시 해내는 지금, 사용자에게 통제권을 남기려면 마찰을 의도적으로 되돌려야 한다고 짚는다.",
        "source": "UX Collective",
        "url": "https://uxdesign.cc/rethinking-friction-in-an-ai-world-8f361d62ab5e",
        "accent": "#ff5a4d",
        "motif": "frame",
        "image": "pipeline/media/rethinking-friction.png",
        "hasFull": true,
        "locked": true
      }
    ]
  }
];
})();
