#!/usr/bin/env python3
"""Maintain the append-only card archive and emit archive-data.js.

news_data.json only carries today + the last 5 deck days per section, so the
site forgets everything older. This script keeps `pipeline/archive.json` — a
permanent, teaser-level record of every card ever published (date, headline,
body, source, url, accent, image; NEVER the premium `full` payload) — and
emits `archive-data.js` (window.AX_ARCHIVE) for the /archive.html page.

Usage:
    python3 pipeline/build_archive.py                # fold current news_data in, emit JS
    python3 pipeline/build_archive.py --backfill     # also replay the full git
                                                     # history of news_data.json first

Idempotent, append-only, earliest-wins: a (section, id) or (section, url)
already in the archive keeps its original date and copy on re-runs.
"""
import argparse
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

SECTION_ORDER = ["design", "music", "movies", "games", "books", "gadgets",
                 "science", "politics"]
SECTION_LABELS = {"design": "Design", "music": "Music", "movies": "Movies",
                  "games": "Games", "books": "Books", "gadgets": "Gadgets",
                  "science": "Science", "politics": "Politics"}

KEEP = ("id", "headline", "body", "tool", "source", "url", "accent", "motif",
        "image")


def iter_day_cards(data):
    """Yield (date, section, card) for every dated card in a news_data dict.
    Accepts both the sectioned schema and the old design-only {today, days}."""
    sections = data.get("sections")
    if sections is None:
        sections = {"design": {"today": data.get("today") or {},
                    "days": data.get("days", [])}}
    for sec, s in sections.items():
        today = s.get("today") or {}
        entries = list(s.get("days", []))
        if today.get("date"):
            entries.append(today)
        for day in entries:
            date = day.get("date")
            if not date:
                continue
            for card in day.get("cards", []):
                yield date, sec, card


def teaser(card):
    """Strip a card to archive fields — the premium `full` payload must never
    reach the public archive."""
    return {k: card.get(k) for k in KEEP if card.get(k) is not None}


def fold(archive, data):
    """Merge one news_data dict into the archive index. Earliest-wins on
    (section, id) and (section, url). Returns number of new cards."""
    by_id = {(c["section"], c["id"]): c for c in archive}
    by_url = {(c["section"], c.get("url")): c for c in archive if c.get("url")}
    added = 0
    for date, sec, card in iter_day_cards(data):
        cid, url = card.get("id"), card.get("url")
        if not cid:
            continue
        old = by_id.get((sec, cid)) or (url and by_url.get((sec, url)))
        if old:
            if date < old["date"]:  # earliest-wins if history replays out of order
                old["date"] = date
            continue
        rec = teaser(card)
        rec["date"], rec["section"] = date, sec
        archive.append(rec)
        by_id[(sec, cid)] = rec
        if url:
            by_url[(sec, url)] = rec
        added += 1
    return added


def backfill(archive):
    """Replay every committed revision of news_data.json, oldest first."""
    rel = "pipeline/news_data.json"
    shas = subprocess.run(
        ["git", "log", "--reverse", "--format=%H", "--", rel],
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout.split()
    total = 0
    for sha in shas:
        blob = subprocess.run(["git", "show", f"{sha}:{rel}"], cwd=ROOT,
                              capture_output=True, text=True)
        if blob.returncode != 0:
            continue
        try:
            data = json.loads(blob.stdout)
        except json.JSONDecodeError:
            continue
        total += fold(archive, data)
    return total, len(shas)


def prune_missing_images(archive):
    """An image path that no longer exists in the tree renders a broken tile —
    null it so the page falls back to the accent placeholder."""
    for c in archive:
        img = c.get("image")
        if img and not os.path.exists(os.path.join(ROOT, img)):
            c["image"] = None


def to_js(archive):
    cards = sorted(archive, key=lambda c: (c["date"], c["section"], c["id"]),
                   reverse=True)
    dump = lambda o: json.dumps(o, ensure_ascii=False, indent=1)
    return ("// GENERATED by pipeline/build_archive.py — do not edit.\n"
            "(function () {\n"
            "  window.AX_ARCHIVE = " + dump(cards) + ";\n" +
            "  window.AX_ARCHIVE_SECTIONS = " + dump(
                [{"key": s, "label": SECTION_LABELS[s]} for s in SECTION_ORDER]) + ";\n"
            "})();\n").replace("</", "<\\/")


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--backfill", action="store_true",
                    help="replay the git history of news_data.json first")
    ap.add_argument("--archive", default=os.path.join(HERE, "archive.json"))
    ap.add_argument("--news", default=os.path.join(HERE, "news_data.json"))
    ap.add_argument("--out", default=os.path.join(ROOT, "archive-data.js"))
    a = ap.parse_args(argv)

    archive = []
    if os.path.exists(a.archive):
        archive = json.load(open(a.archive, encoding="utf-8"))["cards"]

    picked_up = 0
    if a.backfill:
        picked_up, revs = backfill(archive)
        print(f"backfill: {revs} revisions replayed, +{picked_up} cards")

    with open(a.news, encoding="utf-8") as f:
        added = fold(archive, json.load(f))

    prune_missing_images(archive)
    archive.sort(key=lambda c: (c["date"], c["section"], c["id"]))
    with open(a.archive, "w", encoding="utf-8") as f:
        json.dump({"cards": archive}, f, ensure_ascii=False, indent=1)
    with open(a.out, "w", encoding="utf-8") as f:
        f.write(to_js(archive))

    per = {}
    for c in archive:
        per[c["section"]] = per.get(c["section"], 0) + 1
    print(f"archive: {len(archive)} cards (+{added} today)  {per}")


if __name__ == "__main__":
    main(sys.argv[1:])
