"""Generate axbrief-data.js from news_data.json (JSON source of truth).

news_data.json is section-keyed:
  { "sections": { "design": {today, days}, "music": {...}, ... } }

Emits:
  window.AX_SECTIONS = { "<section>": { "news": [...today cards...], "days": [...deck...] }, ... }
  window.AX_NEWS / window.AX_DAYS = the `design` section (back-compat for the
  large-card app until it becomes section-aware).
"""
import argparse, json, sys

HEADER = ("/* AUTO-GENERATED by pipeline/build_data.py — do not hand-edit.\n"
          "   Source of truth: pipeline/news_data.json */\n")

# Section display order + labels for the UI tabs.
SECTION_ORDER = ["design", "music", "movies", "games", "books"]
SECTION_LABELS = {"design": "Design", "music": "Music", "movies": "Movies",
                  "games": "Games", "books": "Books"}

class DuplicateCardError(ValueError):
    pass

def assert_no_duplicates(section, today, days):
    """Within ONE section: no two cards (today + every deck day) may share a URL —
    hard build failure. A shared thumbnail is allowed but warned (distinct articles
    may reuse a source's site-wide OG image)."""
    cards = [("today", c) for c in today.get("cards", [])]
    for day in days:
        cards += [(day["date"], c) for c in day["cards"]]
    seen_url, seen_img, dups = {}, {}, []
    for where, c in cards:
        u, img = c.get("url"), c.get("image")
        if u in seen_url:
            dups.append(f"[{section}] duplicate URL {u!r}: {seen_url[u]} & {where}")
        else:
            seen_url[u] = where
        if img:
            if img in seen_img:
                print(f"WARN: [{section}] shared thumbnail {img!r}: {seen_img[img]} & {where} "
                      f"(distinct articles — consider a per-article image)", file=sys.stderr)
            else:
                seen_img[img] = where
    if dups:
        raise DuplicateCardError("; ".join(dups))

def to_js(data):
    # Back-compat: accept an old non-sectioned file too.
    sections = data.get("sections")
    if sections is None:
        sections = {"design": {"today": data.get("today", {"cards": []}), "days": data.get("days", [])}}

    ax_sections = {}
    for sec in SECTION_ORDER:
        s = sections.get(sec) or {"today": {"cards": []}, "days": []}
        today = s.get("today") or {"cards": []}
        days = s.get("days", [])
        assert_no_duplicates(sec, today, days)
        ax_sections[sec] = {"label": SECTION_LABELS.get(sec, sec.title()),
                            "news": today.get("cards", []), "days": days}

    design = ax_sections.get("design", {"news": [], "days": []})

    def dump(obj):
        return json.dumps(obj, ensure_ascii=False, indent=2)
    return (HEADER +
            "(function () {\n" +
            "  window.AX_SECTIONS = " + dump(ax_sections) + ";\n" +
            "  window.AX_SECTION_ORDER = " + dump(SECTION_ORDER) + ";\n" +
            "  // back-compat (large-card app reads these until it becomes section-aware):\n" +
            "  window.AX_NEWS = " + dump(design["news"]) + ";\n" +
            "  window.AX_DAYS = " + dump(design["days"]) + ";\n" +
            "})();\n")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", default="news_data.json")
    ap.add_argument("--out", dest="out", default="../axbrief-data.js")
    a = ap.parse_args()
    data = json.load(open(a.inp, encoding="utf-8"))
    open(a.out, "w", encoding="utf-8").write(to_js(data))

if __name__ == "__main__":
    main()
