"""Generate axbrief-data.js from news_data.json (JSON source of truth)."""
import argparse, json, sys

HEADER = ("/* AUTO-GENERATED by pipeline/build_data.py — do not hand-edit.\n"
          "   Source of truth: pipeline/news_data.json */\n")

class DuplicateCardError(ValueError):
    pass

def assert_no_duplicates(data):
    """Duplicates are judged by URL only: no two cards anywhere (today + every deck
    day) may share a URL — that is a hard build failure. A shared banner image is NOT
    a duplicate (distinct articles may reuse a source's site-wide OG image), but two
    cards with the same thumbnail still read as repetitive, so we WARN (non-fatal) to
    nudge toward a distinct in-article image."""
    cards = [("today", c) for c in data["today"]["cards"]]
    for day in data.get("days", []):
        cards += [(day["date"], c) for c in day["cards"]]
    seen_url, seen_img, dups = {}, {}, []
    for where, c in cards:
        u, img = c.get("url"), c.get("image")
        if u in seen_url:
            dups.append(f"duplicate URL {u!r}: {seen_url[u]} & {where}")
        else:
            seen_url[u] = where
        if img:
            if img in seen_img:
                print(f"WARN: shared thumbnail {img!r}: {seen_img[img]} & {where} "
                      f"(distinct articles — consider a per-article image)", file=sys.stderr)
            else:
                seen_img[img] = where
    if dups:
        raise DuplicateCardError("; ".join(dups))

def to_js(data):
    assert_no_duplicates(data)
    news = data["today"]["cards"]
    # The deck is the past-day archive only (no today entry — today lives in the
    # hero, and the app provides a "back to today" control when viewing a past day).
    days = data["days"]
    def dump(obj):
        return json.dumps(obj, ensure_ascii=False, indent=2)
    return (HEADER +
            "(function () {\n" +
            "  window.AX_NEWS = " + dump(news) + ";\n" +
            "  window.AX_DAYS = " + dump(days) + ";\n" +
            "})();\n")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", default="news_data.json")
    ap.add_argument("--out", dest="out", default="../axbrief-data.js")
    a = ap.parse_args()
    data = json.load(open(a.inp, encoding="utf-8"))
    open(a.out, "w", encoding="utf-8").write(to_js(data))

if __name__ == "__main__":
    main()
