"""Generate axbrief-data.js from news_data.json (JSON source of truth).

news_data.json is section-keyed:
  { "sections": { "design": {today, days}, "music": {...}, ... } }

Emits:
  window.AX_SECTIONS = { "<section>": { "news": [...today cards...], "days": [...deck...] }, ... }
  window.AX_NEWS / window.AX_DAYS = the `design` section (back-compat for the
  large-card app until it becomes section-aware).
"""
import argparse, html, json, os, shutil, sys

HEADER = ("/* AUTO-GENERATED by pipeline/build_data.py — do not hand-edit.\n"
          "   Source of truth: pipeline/news_data.json */\n")

DEFAULT_BASE_URL = "https://axitdesign.simonksy.workers.dev"

# Section display order + labels for the UI tabs.
SECTION_ORDER = ["design", "music", "movies", "games", "books"]
SECTION_LABELS = {"design": "Design", "music": "Music", "movies": "Movies",
                  "games": "Games", "books": "Books"}

class DuplicateCardError(ValueError):
    pass

def assert_no_duplicates(section, today, days):
    """Within ONE section: no two cards (today + every deck day) may share a URL —
    hard build failure. A shared thumbnail is allowed but warned (distinct articles
    may reuse a source's site-wide OG image)."""
    cards = [("today", c) for c in today.get("cards", [])]
    for day in days:
        cards += [(day["date"], c) for c in day["cards"]]
    seen_url, seen_img, dups = {}, {}, []
    for where, c in cards:
        u, img = c.get("url"), c.get("image")
        if u in seen_url:
            dups.append(f"[{section}] duplicate URL {u!r}: {seen_url[u]} & {where}")
        else:
            seen_url[u] = where
        if img:
            if img in seen_img:
                print(f"WARN: [{section}] shared thumbnail {img!r}: {seen_img[img]} & {where} "
                      f"(distinct articles — consider a per-article image)", file=sys.stderr)
            else:
                seen_img[img] = where
    if dups:
        raise DuplicateCardError("; ".join(dups))

def to_js(data):
    # Back-compat: accept an old non-sectioned file too.
    sections = data.get("sections")
    if sections is None:
        sections = {"design": {"today": data.get("today", {"cards": []}), "days": data.get("days", [])}}

    ax_sections = {}
    for sec in SECTION_ORDER:
        s = sections.get(sec) or {"today": {"cards": []}, "days": []}
        today = s.get("today") or {"cards": []}
        days = s.get("days", [])
        assert_no_duplicates(sec, today, days)
        ax_sections[sec] = {"label": SECTION_LABELS.get(sec, sec.title()),
                            "news": today.get("cards", []), "days": days}

    design = ax_sections.get("design", {"news": [], "days": []})

    def dump(obj):
        return json.dumps(obj, ensure_ascii=False, indent=2)
    return (HEADER +
            "(function () {\n" +
            "  window.AX_SECTIONS = " + dump(ax_sections) + ";\n" +
            "  window.AX_SECTION_ORDER = " + dump(SECTION_ORDER) + ";\n" +
            "  // back-compat (large-card app reads these until it becomes section-aware):\n" +
            "  window.AX_NEWS = " + dump(design["news"]) + ";\n" +
            "  window.AX_DAYS = " + dump(design["days"]) + ";\n" +
            "})();\n")

SHARE_TMPL = """<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} · Design AX Brief</title>
<meta name="description" content="{desc}">
<meta property="og:type" content="article">
<meta property="og:site_name" content="Design AX Brief">
<meta property="og:locale" content="ko_KR">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:url" content="{ogurl}">{img_tags}
<meta name="twitter:card" content="{tw_card}">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{desc}">{tw_img}
<link rel="canonical" href="{appurl}">
<meta http-equiv="refresh" content="0; url={appurl}">
<script>location.replace({appurl_js})</script>
</head>
<body style="margin:0;height:100vh;display:flex;align-items:center;justify-content:center;background:#f1ece4;font-family:Pretendard,system-ui,sans-serif;color:#171717">
<a href="{appurl}" style="color:#171717;text-decoration:none;font-size:15px">Design AX Brief — 카드 열기 →</a>
</body>
</html>
"""

def emit_share_pages(sections, base_url, share_root):
    """Per-card static share pages at <share_root>/s/<section>/<id>.html with OG/Twitter
    meta (so pasted links unfurl with the card's image + headline) + a redirect into the
    app at /?c=<section>:<id>. Regenerated fresh each build (stale pages are cleared)."""
    base = base_url.rstrip("/")
    s_root = os.path.join(share_root, "s")
    shutil.rmtree(s_root, ignore_errors=True)
    n = 0
    for sec, payload in sections.items():
        cards = list(payload.get("news", []))
        for day in payload.get("days", []):
            cards += day.get("cards", [])
        seen = set()
        for c in cards:
            cid = c.get("id")
            if not cid or cid in seen:
                continue
            seen.add(cid)
            e = lambda s: html.escape(str(s or ""), quote=True)
            title = e((c.get("headline") or "").replace("\n", " ").strip())
            desc = e((c.get("body") or "").strip())
            appurl = f"{base}/?c={sec}:{cid}"
            ogurl = f"{base}/s/{sec}/{cid}"
            img = c.get("image")
            if img:
                imgurl = e(f"{base}/{str(img).lstrip('/')}")
                img_tags = (f'\n<meta property="og:image" content="{imgurl}">'
                            f'\n<meta property="og:image:alt" content="{title}">')
                tw_img = f'\n<meta name="twitter:image" content="{imgurl}">'
                tw_card = "summary_large_image"
            else:
                img_tags, tw_img, tw_card = "", "", "summary"
            page = SHARE_TMPL.format(title=title, desc=desc, ogurl=e(ogurl),
                                     appurl=e(appurl), appurl_js=json.dumps(appurl),
                                     img_tags=img_tags, tw_img=tw_img, tw_card=tw_card)
            d = os.path.join(s_root, sec)
            os.makedirs(d, exist_ok=True)
            open(os.path.join(d, f"{cid}.html"), "w", encoding="utf-8").write(page)
            n += 1
    return n

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", default="news_data.json")
    ap.add_argument("--out", dest="out", default="../axbrief-data.js")
    ap.add_argument("--share-root", default=None,
                    help="if set, also emit per-card OG share pages under <root>/s/")
    ap.add_argument("--base-url", default=DEFAULT_BASE_URL,
                    help="absolute origin for OG urls/images in share pages")
    a = ap.parse_args()
    data = json.load(open(a.inp, encoding="utf-8"))
    open(a.out, "w", encoding="utf-8").write(to_js(data))
    if a.share_root:
        sections = data.get("sections") or {
            "design": {"news": data.get("today", {}).get("cards", []), "days": data.get("days", [])}}
        # normalize old/sectioned shapes to {news,days}
        norm = {}
        for sec, s in sections.items():
            if "news" in s:
                norm[sec] = s
            else:
                norm[sec] = {"news": (s.get("today") or {}).get("cards", []), "days": s.get("days", [])}
        n = emit_share_pages(norm, a.base_url, a.share_root)
        print(f"share pages: {n}")

if __name__ == "__main__":
    main()
